### ISSUE TITLE
Can't login Mojang

### ISSUE THREAD

**Issue by iceBear67** [Voxelum/x-minecraft-launcher#129]
![图片](https://user-images.githubusercontent.com/48877375/114259912-020ec080-9a04-11eb-9959-40df71d81642.png)

**Comment by ci010** [comment]
I will investigate this in these two days. I think the new version will be released tomorrow.
 If i have found something today. I think I will update this thread. Thanks a lot.

**Comment by ci010** [comment]
Close due to outdated.
