### ISSUE TITLE
Add native window control buttons on windows

### ISSUE THREAD

**Issue by dimaxiton1** [Voxelum/x-minecraft-launcher#136]

**Comment by ci010** [comment]
Will create a top bar like discord app as the launcher support fullscreen now.

**Comment by ci010** [comment]
Will create a top bar like discord app as the launcher support fullscreen now.

**Comment by ci010** [comment]
Will create a top bar like discord app as the launcher support fullscreen now.

**Comment by ci010** [comment]
Will create a top bar like discord app as the launcher support fullscreen now.

**Comment by ci010** [comment]
This should be added in https://github.com/Voxelum/x-minecraft-launcher/pull/149
