### ISSUE TITLE
Doesn't install curseforge modpacks

### ISSUE THREAD

**Issue by dimaxiton1** [Voxelum/x-minecraft-launcher#137]
![image](https://user-images.githubusercontent.com/25724885/123312602-3e48bc00-d531-11eb-9657-10ff9ceb6912.png)

There is no progress bar so I can't even be sure that it does something. Please implement more comprehensive UI, there is a lot of cool frameworks / lib that can you with that. https://github.com/sindresorhus/p-progress can help with implementing the logic. And [material-ui progress](https://material-ui.com/components/progress/#linear-determinate) has a beautiful UI that I'd recommend to use.

**Comment by ci010** [comment]
Do you encounter same problem in v0.17.1? I think this should be fixed in new version. You can monitor progress in task dialog:

![image](https://user-images.githubusercontent.com/8425057/151647299-afdcc6a6-3a6e-4b42-8877-ff95970a6195.png)
