### ISSUE TITLE
Error with java

### ISSUE THREAD

**Issue by HlebKrah** [Voxelum/x-minecraft-launcher#14]
Java installed, but i have this error
![image](https://user-images.githubusercontent.com/27029154/39777673-0a1b32e4-52b9-11e8-84b2-51e6a79eb94b.png)

**Comment by ci010** [comment]
I wonder which version/branch do you have? Is this the branch store-refactor, or the master branch

**Comment by HlebKrah** [comment]
store-refactor

**Comment by HlebKrah** [comment]
same error on ubuntu 18.04

**Comment by HlebKrah** [comment]
any news?

**Comment by ci010** [comment]
I hope I will have a chance to solve at this problem on this weekend. Sorry about that. (Busy on other things really...)

**Comment by ci010** [comment]
BTW, I'm considering make it work like the official launcher, which downloads a new JRE anyway. (Since forge doesn't really support new version of java) Any suggestion? Which do you think is better
way?

**Comment by ci010** [comment]
I think I fix the problem on ubuntu.... (18.04 in VirtualBox) You can try with the newest version (commit 300a279d42d86765ac094f3f8ba868c920c110f1)

**Comment by HlebKrah** [comment]
> BTW, I'm considering make it work like the official launcher, which downloads a new JRE anyway. (Since forge doesn't really support new version of java) Any suggestion? Which do you think is better
way?

It's will be great, i want see something like this
![image](https://user-images.githubusercontent.com/27029154/40324305-c7d263a2-5d40-11e8-8f83-19f567dc560e.png)

**Comment by HlebKrah** [comment]
Some news?
