### ISSUE TITLE
Support P2P networking

### ISSUE THREAD

**Issue by ci010** [Voxelum/x-minecraft-launcher#154]
Support native networking for lan gaming

[The Design Diagram](https://www.figma.com/file/samelohOYg24BVpxcnPm5k/P2P)

- [x] User can connect to other by webrtc exchange token
- [x] Can detect lan server and redirect to other
- [x] Can handle player join to lan server and redirect all Minecraft network.

Off Session Features

- [ ]  Can auto propagate user connection in network
- [ ] Can sync user mods between peers

Support network provided by @laolarou726.
- Wait llr protocol stable

**Comment by laolarou726** [comment]
yeahhhhh~

**Comment by ci010** [comment]
Close as the feature is implemented
