### ISSUE TITLE
Linux AppImage build cannot use microsoft account to login

### ISSUE THREAD

**Issue by Yricky** [Voxelum/x-minecraft-launcher#170]
Linux AppImage build cannot use microsoft account to login.
Drag to login is also unavailable.

**Screenshots**
![Screenshot_20220224_154601](https://user-images.githubusercontent.com/30372219/155480671-7e3d6f95-ef0b-4894-9baf-2c18c727231c.png)

**Environment**
 - OS: Manjaro linux
 - Version xmcl0.19.0,Firefox97

**Additional context**

**Comment by ci010** [comment]
这个是因为页面很久没刷新出来导致的timeout嘛，还是刷新出来了它还是timeout？这个网页应该是会尝试访问启动器，会弹出一个网页尝试打开xmcl之类的【还是说这个也没有

**Comment by Yricky** [comment]
> 

页面很快就刷新出来了，但是启动器这边一直没反应，直到timeout。点击网页中按钮也没反应。将链接拖动至启动器中时，启动器能识别到链接拖入，但是后续也没反应。没反应的表现就是一直转圈圈直到截图中的timeout。

**Comment by ci010** [comment]
看来是刷出来了但是没有弹出提示打开启动器orz，拖动应该是bug，但是没弹出来跳转可能是浏览器的问题orz？我看看

**Comment by Yricky** [comment]
> 看来是刷出来了但是没有弹出提示打开启动器orz，拖动应该是bug，但是没弹出来跳转可能是浏览器的问题orz？我看看
![图片](https://user-images.githubusercontent.com/30372219/155508735-a1c24837-96cb-4043-99c1-1fe0fa37c14c.png)
Chromium也有此问题，找不到链接的打开方式（点击打开按钮后也没有反应）。

另外问一下，既然这个启动器是基于electron的，那在内建窗口中打开认证登录页面也许是可行的？

**Comment by ci010** [comment]
> > 看来是刷出来了但是没有弹出提示打开启动器orz，拖动应该是bug，但是没弹出来跳转可能是浏览器的问题orz？我看看
> > ![图片](https://user-images.githubusercontent.com/30372219/155508735-a1c24837-96cb-4043-99c1-1fe0fa37c14c.png)
> > Chromium也有此问题，找不到链接的打开方式（点击打开按钮后也没有反应）。
> 
> 另外问一下，既然这个启动器是基于electron的，那在内建窗口中打开认证登录页面也许是可行的？

啊你这个截图里有打开这个的弹出，点了也不work嘛

还有其实可以内置，但是理论上不安全，因为我自己spawn的webview，我是能拿到里面的element的信息的，也就是说我可能窃取用户密码

**Comment by Yricky** [comment]
> 啊你这个截图里有打开这个的弹出 “打开xdg-open”，点了也不work……
点击以后不work，会弹出一个空列表。

**Comment by ci010** [comment]
> 啊你这个截图里有打开这个的弹出 “打开xdg-open”，点了也不work……
> 点击以后不work，会弹出一个空列表。

正常流程应该是点了是打开启动器，会给启动器把浏览器里的code传过去。这么看来有可能是install好了我没有正确注册上`xmcl://` 这个protocol？【【搞个linux我尝试自己repro一下

**Comment by ci010** [comment]
有点头绪了 https://github.com/electron-userland/electron-builder/issues/4035#issuecomment-1041275630 按照这个做了之后在我的wsl2里面可以work了
