### ISSUE TITLE
Minecraft1.12.2 crashed when opening a world.

### ISSUE THREAD

**Issue by Yricky** [Voxelum/x-minecraft-launcher#171]
Minecraft1.12.2 crashed when opening a world.
Forge version:14.23.5.2859（Vanilla 1.12.2 is OK，crashed with forge）
Minecraft version:1.12.2

Here is the crash report:
![图片](https://user-images.githubusercontent.com/30372219/155510925-1b5f1c6b-9233-43dc-ba76-ff1eace507ea.png)
Mods：
![图片](https://user-images.githubusercontent.com/30372219/155512351-4d30a712-0b02-4216-a310-90e9c785eead.png)

**Comment by ci010** [comment]
看上去是参数传错了……？我先试试我能不能repro，你现在是离线登录吧，然后用户名写的是 Yricky.

**Comment by Yricky** [comment]
> 

是的，离线账户，minecraft1.12.2,forge最新推荐版，可以进入游戏主界面，但是进入世界崩溃

**Comment by ci010** [comment]
嗯，感觉我修了，会在最新的PR里体现
