### ISSUE TITLE
游戏界面出现后还在显示启动中

### ISSUE THREAD

**Issue by xX-BERTANT-Xx** [Voxelum/x-minecraft-launcher#206]
版本：0.21.7
系统：Windows 10 21H2
安装方式：解压xmcl-0.21.7-win32-x64.zip
问题：游戏界面出现后还在显示启动中，直到关闭游戏才停止显示
![image](https://user-images.githubusercontent.com/101613578/160046027-1731977a-2d13-451b-b602-50eb290f194c.png)

**Comment by ci010** [comment]
神奇，我还不太好repro这个问题，我先keep monitor一段时间【

**Comment by xX-BERTANT-Xx** [comment]
ok

**Comment by ci010** [comment]
新版本因为支持启动多个Minecraft，这个问题算won't fix了【
