### ISSUE TITLE
版本更新下载按钮显示问题

### ISSUE THREAD

**Issue by xX-BERTANT-Xx** [Voxelum/x-minecraft-launcher#218]
版本：**0.21.8**
系统：**Windows 10 21H2**
安装方式：解压**xmcl-0.21.8-win32-x64.zip**
问题：版本更新中的下载并安装按钮如果位置不够无法显示（不知道**0.21.9**解决了没）

https://user-images.githubusercontent.com/101613578/160219507-66a6c4f5-7929-445b-aca4-86c0dda06b4a.mp4

**Comment by ci010** [comment]
0.22.0解决了
