### ISSUE TITLE
下载并安装无法使用

### ISSUE THREAD

**Issue by xX-BERTANT-Xx** [Voxelum/x-minecraft-launcher#219]
版本：0.21.8
系统：Windows 10 21H2
安装方式：解压xmcl-0.21.8-win32-x64.zip
问题：

https://user-images.githubusercontent.com/101613578/160220155-58d14f9b-f2bd-4fec-853e-17109dc22ff3.mp4

**Comment by LeoBlackMT** [comment]
我点击后会直接跳转到官网

**Comment by xX-BERTANT-Xx** [comment]
你是什么版本

**Comment by LeoBlackMT** [comment]
0.21.8

**Comment by xX-BERTANT-Xx** [comment]
我也是啊

**Comment by LeoBlackMT** [comment]
> 我也是啊

不知道反正我点了直接去官网

**Comment by xX-BERTANT-Xx** [comment]
你点的右下角那个？

**Comment by LeoBlackMT** [comment]
> 你点的右下角那个？

对

**Comment by xX-BERTANT-Xx** [comment]
az

**Comment by ci010** [comment]
AppX 和 appinstaller 因为特殊性（安装后文件只读），会跳转官网上下新的版本【

**Comment by xX-BERTANT-Xx** [comment]
那我这个是啥bug

**Comment by ci010** [comment]
艹等等，我刚看了你的视频，应该是某个state坏了，我修一下【。

**Comment by ci010** [comment]
希望新版解决了【先关了，如果还有再打开
