### ISSUE TITLE
PLEASE DON'T MOVE MY RESOURCE PACK AND SHADER PACKS WITHOUT USER'S PERMISSION

### ISSUE THREAD

**Issue by weearc** [Voxelum/x-minecraft-launcher#229]
I'm sure this is not a bug but the expected behavior of the program, but please don't move my files around. Other launchers, especially official launchers, cannot use soft links. And when I delete the XMCL related folder, it deletes everything I saved! This can be easily replicated in the latest version. PLEASE DO NOT MOVE FILES. You may copy it won't you.

**Comment by ci010** [comment]
Will try to use hard link for resource pack & shader pack if the instance is externally imported.

I have two ways to implement this:

### Real time synchronizes

- Any file add in central resourcepacks/shaderpacks, will be link or copy to local instance resourcepacks/shaderpacks
- Any file add in local resourcepacks/shaderpacks, will be link or copy to center resourcepacks/shaderpacks

This is the ideal case. You will see all the resourcepacks/shaderpacks in folder in place all the time.

### Launch time synchronizes

- All imported resourcepacks/shaderpacks in UI will be imported to central folders.
- Any file add in local resourcepacks/shaderpacks, will be link or copy to center resourcepacks/shaderpacks
- Ensure all central resourcepacks/shaderpacks files are in place in the local folder right before the `launch`

The bad part is only if the launcher launch will synchronize the packs, there might be a chance that some pack is imported but not listed in folder before launch. If user doesn't launch, the change won't sync.

The good part is... This is easiler to implement and less likely to have bugs. (Two way sync can be buggy easily)

I'll need to investigate how this change will impact on the current design.
Might not be fixed really soon. (Maybe 1 or 2 version later).

**Comment by weearc** [comment]
@ci010 Thank for your reply. I apologize for being carried away by anger and using rude language to open the issue.
By the way, sync all resources files automatically may not solve the problem. If the entire import process were transparent and optional to users, some problems might be avoided.
