### ISSUE TITLE
error when just i clone it  and execute 'pnpm i'

### ISSUE THREAD

**Issue by MoLuoPro** [Voxelum/x-minecraft-launcher#233]
**To Reproduce**

1. git clone 
2. cd  x-minecraft-launcher
3. pnpm i 

![20220414084258](https://user-images.githubusercontent.com/55039286/163292369-65f32ba2-6817-4042-9a5d-a16193ae834f.png)

**Environment**
 - OS: linux

**Comment by ci010** [comment]
Please follow the [clone section in CONTRIBUTE docs](https://github.com/Voxelum/x-minecraft-launcher/blob/master/CONTRIBUTING.md#clone).

You need clone submodules with --recurse-submodules, or you will need to initialize submodule manually.

Without that, the pnpm cannot install submodule correctly as they are not in workspace.
