### ISSUE TITLE
无法识别 XGP 版 Minecraft Java Edition

### ISSUE THREAD

**Issue by InsulateJustf** [Voxelum/x-minecraft-launcher#250]
登陆微软账户后提示需要购买 MineCraft Java Edtion，而我是  XGP for PC 用户，应该可以正常登录才对

**Comment by ci010** [comment]
所以你应该能玩 java，但是还是提示你没有账号是么

**Comment by InsulateJustf** [comment]
> 

不是的，我连打开游戏都不行，只能使用离线登录。我的账户使用 MultiMC 和官方启动器都是能正常识别到 XGP 并启动游戏的。

**Comment by ci010** [comment]
这两天我叫我有XGP MC的朋友帮我试试debug吧

**Comment by ci010** [comment]
Should work now
