### ISSUE TITLE
在线安装包：解析应用包时出错。

### ISSUE THREAD

**Issue by UsernameKLNU** [Voxelum/x-minecraft-launcher#251]
**To Reproduce**

打开下载的在线安装包

**Expected behavior**
解析应用包时出错。

**Screenshots**
![image](https://user-images.githubusercontent.com/101550757/168740234-b205d231-5695-4d5f-acea-facb07886307.png)

**Environment**
OS: Windows 11
在官网下载的

**Comment by ci010** [comment]
这个有时候会出现，有可能是因为你开了代理 或者 vpn，这个不在启动器的控制范围内orz

**Comment by UsernameKLNU** [comment]
好的
