### ISSUE TITLE
导入整合包失败

### ISSUE THREAD

**Issue by 5aaee9** [Voxelum/x-minecraft-launcher#252]
**To Reproduce**

从 Zip 导入一个整合包
进行整合包安装

**Expected behavior**
应该能成功安装整合包

**Screenshots**
<img width="680" alt="image" src="https://user-images.githubusercontent.com/7685264/168906582-f746d06d-a121-463f-a5ae-d67d7e25ef36.png">

**Environment**
 - OS: MacOS Monterey 12.1
 - Version v.0.23.2

**Additional context**
看起来获取 CurseForge Mod 的时候使用了 https://addons-ecs.forgesvc.net 的服务？ 但是我这里 curl 返回的结果看起来像是要 Token 才能访问 （顺带一提 https://twitchappapi.docs.apiary.io/ 好像都访问不了了）

~~可以尝试换成 [CurseMeta](https://cursemeta.dries007.net/)？MultiMC 就是使用的这个服务（~~
https://github.com/huanghongxun/HMCL/issues/1490

<img width="609" alt="image" src="https://user-images.githubusercontent.com/7685264/168906889-f2c5ffca-e21b-40dc-aa89-c86bfa45c796.png">

**Comment by ci010** [comment]
APIkey已经申请到了，可是新的API缺了很多功能……比如搜索资源包啥的

**Comment by ci010** [comment]
0.25.0 版本修了一下这个问题，现在整合包起码能下【
