### ISSUE TITLE
Mod无法打开”WorldEdit“

### ISSUE THREAD

**Issue by UsernameKLNU** [Voxelum/x-minecraft-launcher#255]
**To Reproduce**

1. 打开XMCL
2. 单击”Home“图标
3. 左栏出现了三个图标，单击Mod
4. 无法点击WorldEdit

**Expected behavior**
无法点击WorldEdit的打开按钮，可能是被”保存“图标旁边不可见的什么东西挡住了（如果没有保存图标可以正常点）

**Screenshots**
![image](https://user-images.githubusercontent.com/101550757/168940875-6157909b-687b-4fbd-bb74-009128059e31.png)
红圈代表鼠标位置

**Environment**
 - OS: WIndows 11
 - Version 0.24.1

**Additional context**

**Comment by ci010** [comment]
你说的对，应该是被按钮遮掉了
