### ISSUE TITLE
导入实例时遇到的问题

### ISSUE THREAD

**Issue by Jisoadng0** [Voxelum/x-minecraft-launcher#263]
无法导入MultiMC或其他启动器的实例。
导入MultiMC的实例后显示1.18.1且无法启动，
导入其他启动器的实例后显示(Default)且无法启动。
![image](https://user-images.githubusercontent.com/106051667/169747495-0c1fef21-9db8-478c-8056-c39046d415e2.png)
.minecraft文件夹和versions内的版本号文件夹我都尝试了导入，但是都没成功。
还是说我对这个导入按钮的理解错了？

**Comment by ci010** [comment]
应该就是选择.minecraft文件夹，不过我确实没试过和mmc的instance兼容，我可以先去试一下
