### ISSUE TITLE
Support Apple M1

### ISSUE THREAD

**Issue by ci010** [Voxelum/x-minecraft-launcher#264]
Waiting github action to support M1 https://github.com/actions/virtual-environments/issues/2187

**Comment by ci010** [comment]
应该是vue devtool……要么给devtool先放到optionalDependencies里……

**Comment by LiamSho** [comment]
在 M1 芯片的 Mac 上成功编译出了 x64 和 arm64 的版本

![image](https://user-images.githubusercontent.com/28832398/208503845-8cc8212c-d3e4-4c2d-861a-9279961517b1.png)
![image](https://user-images.githubusercontent.com/28832398/208503888-3581fdb6-9bef-49e5-aaf6-3f9aaa5c987a.png)

修改 [xmcl-electron-app/build/electron-builder.config.ts](https://github.com/Voxelum/x-minecraft-launcher/blob/54176a1003d1037422fa2e1071126dc68fbe473c/xmcl-electron-app/build/electron-builder.config.ts) 文件的 Mac 部分，加上 arch 即可：
```
  mac: {
    icon: 'icons/dark.icns',
    darkModeSupport: true,
    target: [
      {
        target: 'zip',
        arch: [
          'x64',
          'arm64',
        ],
      },
      {
        target: 'dmg',
        arch: [
          'x64',
          'arm64',
        ],
      },
    ],
  },
```

编译输出：
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/28832398/208504897-cade8fea-9431-4556-b831-906a001bca54.png">

由于 @vue/devtools 引入了 Electron 7.x 导致在使用 Apple Silicon 的 Mac 上执行 `pnpm i` 会失败，所以我本地测试直接把这个依赖删了。在 x64 的 Mac 上应该没有问题，手头没有这样的设备所以没有测试。

**Comment by ci010** [comment]
新版应该支持了
