### ISSUE TITLE
Maximize button doesnt render properly on 150% Windows scaling

### ISSUE THREAD

**Issue by CodeF53** [Voxelum/x-minecraft-launcher#279]
# description:
when at 150% scaling in windows display settings, the maximize button is just a line

![image](https://user-images.githubusercontent.com/37855219/173662633-ed6aa9f8-bcff-4b51-b0a8-4b5eab361501.png)

# reproduce:
1. set windows display settings to 1920x1080 and 150% scaling
![image](https://user-images.githubusercontent.com/37855219/173662883-84afb411-16a9-497e-ae77-fae825e1c17a.png)
2. open xcml and look at the upper right of the window

**Comment by ci010** [comment]
The icon is changed now.
