### ISSUE TITLE
Modrinth search freezes results after applying enough filters

### ISSUE THREAD

**Issue by CodeF53** [Voxelum/x-minecraft-launcher#280]
# Description of issue
After enabling a bunch of filters, the mod results no longer update to match what you should see

[![ezgif-com-gif-maker.gif](https://i.postimg.cc/Px89ckGb/ezgif-com-gif-maker.gif)](https://postimg.cc/mzBmzJgh)

 # Reproduce:
1. select a game version, environment, modloader, and category in the modrinth search
2. try to (change page number/change sort/change filters/search) 
3. observe that no matter what you do you always just see sodium, fabric api, and lithium

**Comment by trbodev** [comment]
https://github.com/Voxelum/x-minecraft-launcher/blob/c383744a75b3bcc06b1707fcd4e0aef4f245f416/xmcl-keystone-ui/src/windows/main/composables/modrinth.ts#L149 should be `versions:` not `version:`, this should fix this issue
