### ISSUE TITLE
Instead of the first launch setup window, a blank window appear.

### ISSUE THREAD

**Issue by tangymc** [Voxelum/x-minecraft-launcher#284]
So, I downloaded version 0.27.3 from the website using the appx one. But, after installation and launching it up, Instead of showing the setup window, it shows a blank window.

**To Reproduce**

**Expected behavior**
The setup windows should show up.

**Screenshots**

![image](https://user-images.githubusercontent.com/74885686/174490702-c77bfaa5-8760-4045-8d15-858bf8bde34d.png)

**Environment**
 - OS: Windows
 - Version 11

**Comment by ci010** [comment]
I'll fix this ASAP. This is a production only error... I miss this in dev env.

**Comment by ci010** [comment]
Should be resolved in 0.27.4.
