### ISSUE TITLE
版本兼容性误判

### ISSUE THREAD

**Issue by mike-brown8** [Voxelum/x-minecraft-launcher#289]
在一个兼容的版本显示可能不兼容的提示

**To Reproduce**

1. 安装Modrinth整合包Speed Of Light FPS Booster (SOL)
2. 打开Mod列表
3. 鼠标悬浮于一个Mod上
4. 看见错误

**Expected behavior**
不显示提示

**Screenshots**
![image](https://user-images.githubusercontent.com/87358498/175025502-eae19021-f957-45c4-bae9-7ea2714c1856.png)
目前1.19. 推荐>=1.19 显示不兼容 Fabric同理

**Environment**
 - OS: Windows 11 Pro [21H2 22000.675]
 - Version v0.27.4

**Additional context**
None.

**Comment by ci010** [comment]
是的orz，这个我已经在开发版里修了，这周末的release应该就应该包含这个修复了。

这个是因为 mc 的版本 (`1.19`) 不是 semver，用 semver 判断会失效…… 解决办法是发现 `1.19` 这种格式的时候后面手工给他加个 `.0`

**Comment by mike-brown8** [comment]
好的，谢谢！您的启动器使用Mods目录重定向的点子真的很棒！
