### ISSUE TITLE
Add "Dev" Update Channel

### ISSUE THREAD

**Issue by mike-brown8** [Voxelum/x-minecraft-launcher#295]
Hope the developer can add _`Dev`_ Update Channel in order to give users a way to use develop(instead of release) version. Though there may be more bugs, but more tests can form more reports, and the reports can provide better compatibility.

_I am a Chinese, and I may have some grammar errors. Please forgive me._

**Comment by ci010** [comment]
现在又prebuilt artifact做前瞻版
