### ISSUE TITLE
[bug][linux]自动下载java时checksum错误

### ISSUE THREAD

**Issue by proItheus** [Voxelum/x-minecraft-launcher#305]
**To Reproduce**

1. 打开一个不兼容现有java的实例,选择自动下载java
![图片](https://user-images.githubusercontent.com/50539150/177468892-59dec66f-f0e4-4899-a921-594de037c900.png)

2. 报错,如图
![图片](https://user-images.githubusercontent.com/50539150/177469026-b0f956e6-d47b-4e09-9859-b156117d8a0b.png)
![图片](https://user-images.githubusercontent.com/50539150/177469153-3898776c-fc6a-4ae5-98bc-39e426ddbdc1.png)
![图片](https://user-images.githubusercontent.com/50539150/177469485-81494539-9377-4354-a8b6-033e1ac57f9e.png)

**Expected behavior**
正常下载安装

**Environment**
 - OS: arch linux
 - Version:0.28.1

**Additional context**
Using appimage from realease.
网络环境正常,手动下载报错中提到的文件均成功

**Comment by proItheus** [comment]
log里看上去有关系的就是这个了……
```
[INFO] [2022/7/12 下午6:56:56] [JavaService] Acquire singleton JavaService.installDefaultJava()
[INFO] [2022/7/12 下午6:56:56] [JavaService] Try to install official java [object Object] to /home/proitheus/Games/minecraft/jre/jre-legacy/bin/java
[INFO] [2022/7/12 下午6:56:57] [JavaService] Install jre runtime jre-legacy (8) 8u202 2020-11-17T19:26:25+00:00
[WARN] [2022/7/12 下午6:56:59] [TaskManager] Task download(27adbd6f-5363-469e-9c66-8065b7699cee) failed!
[WARN] [2022/7/12 下午6:56:59] [TaskManager] [object Object]
[WARN] [2022/7/12 下午6:57:11] [TaskManager] Task installJre(27adbd6f-5363-469e-9c66-8065b7699cee) failed!
[WARN] [2022/7/12 下午6:57:11] [TaskManager] [object Object]
[INFO] [2022/7/12 下午6:57:11] [TaskManager] Task done and delete record!
[INFO] [2022/7/12 下午6:57:11] [JavaService] Release singleton JavaService.installDefaultJava(). Took 15064ms.
```
0.29.2的appimage
[report.zip](https://upload.disroot.org/r/xx8Btrmk#DQsIrbh377koOcM/tZ7JXgIjzCUID7bUgJU84NUERLY=)

**Comment by ci010** [comment]
奇怪，我在我的wsl里测试好像不是很能repro这个问题，我怀疑是是不是之前一段时间bmclapi有一些网络的抖动？
