### ISSUE TITLE
[FR]允许修改Minecraft的启动参数，如uuid

### ISSUE THREAD

**Issue by proItheus** [Voxelum/x-minecraft-launcher#307]
如题，现在能够在默认的参数后面添加参数，但不能修改原有的启动参数，希望能添加此功能。我想把另一台电脑上的档移过来，但是uuid不一样的话进度（成就）还有一些其他的和身份相关的（比如身份卡）会乱掉。感谢作者做出如此功能强大，并且跨平台的启动器。

**Comment by ci010** [comment]
之前的uuid指的是离线账户吧，确实我之前忽略了
