### ISSUE TITLE
individual content update checking

### ISSUE THREAD

**Issue by bappitybup** [Voxelum/x-minecraft-launcher#313]
This is a feature request.

When any installed content in a profile (Mod/Resource Pack) are of a lower version than the currently latest available version of a mod, an icon would appear beside it in the list that can be clicked, which would automatically remove the old version of the content and install the latest new version of it.

This would have conditions, such as taking into account the content labels (such as "Game Version", "Mod Loader" and "Status"), only showing the icon in a profile if the labels match (Such as the "Mod Loader" of a profile being "Fabric", or the "Game Version" being "1.19"). Ultimately, the latest version of the content matching the conditions would be installed.

**Comment by ci010** [comment]
The new version has some basic function of mod auto update.
