### ISSUE TITLE
Support for mods that have multiple loaders

### ISSUE THREAD

**Issue by Ran-Mewo** [Voxelum/x-minecraft-launcher#325]
Mods that support multiple loaders by using [Forgix](https://github.com/PacifistMC/Forgix) or something similar can't be imported. If you manually try to import then the all of the loader tags don't show up

**To Reproduce**
A good example of this is to import the mod [Distant Horizons](https://www.curseforge.com/minecraft/mc-mods/distant-horizons)
It has support for both Fabric & Forge in the same jar

**Expected behavior**
The mod is supposed to be imported and correctly list all loader tags that it supports

**Environment**
 - OS: Windows
 - Version 11

**Comment by ci010** [comment]
I think we support quilt now
