### ISSUE TITLE
Mods missing in the Mods Tab

### ISSUE THREAD

**Issue by Mukshub** [Voxelum/x-minecraft-launcher#343]
![image](https://user-images.githubusercontent.com/73426407/191965426-f0837ac4-c4e8-4e1f-ac36-e404846dbf07.png)
![image](https://user-images.githubusercontent.com/73426407/191965462-21acadf1-6523-4462-9faf-08a26e30381e.png)
![image](https://user-images.githubusercontent.com/73426407/191965700-21f9e0b3-14d6-4a44-ac6b-f12e4dc45824.png)

My Mods tab isn't showing my launcher

Yesterday it was fine and showing all the mods and texture packs etc etc but now it's showing empty for all, when I launch the game the mods work tho.

**Environment**
 - OS: Windows
 - Version v0.30.5 -> v0.30.5

**Comment by ci010** [comment]
You need to use forge or fabric with mod menu mod to show mod tab
