### ISSUE TITLE
Modrinth模组加载器混入插件

### ISSUE THREAD

**Issue by SulfuricM** [Voxelum/x-minecraft-launcher#361]
![QQ截图20221029172059](https://user-images.githubusercontent.com/115728428/198823959-025c04b3-7919-4806-ad78-28e6f34919af.png)

**Comment by ci010** [comment]
XMCL 暂时不会处理这个。 modrinth 官方 api https://docs.modrinth.com/api-spec/#tag/project_model 目前 project_type 就只区分了 3 种（虽然网页版区分了 plugin），mod modpack 和 resourcepack。没有plugin，目前这些 modloader 也被分到 mod 下面了，等 modrinth 官方更新吧
