### ISSUE TITLE
支持多种账号系统

### ISSUE THREAD

**Issue by XiaohCeale** [Voxelum/x-minecraft-launcher#362]
希望可以自行添加其他的外置登录服务器
我看Readme里写着是可以自行添加的，但是在启动器中似乎没法自行添加

**Comment by ci010** [comment]
是的，这次重写ui之后这部分的ui还没加回来

**Comment by ci010** [comment]
话说你想加什么外置登录服务器，我好debug的时候用

**Comment by XiaohCeale** [comment]
红石皮肤站(mcskin.cn) （
