### ISSUE TITLE
最大化与窗口化按钮改为矩形

### ISSUE THREAD

**Issue by XiaohCeale** [Voxelum/x-minecraft-launcher#363]
我觉得可以把最大化与窗口化按钮改为矩形
（![image](https://user-images.githubusercontent.com/93030615/198863143-d17ebc0c-8420-462a-849c-bfffc6149a05.png)
![image](https://user-images.githubusercontent.com/93030615/198863155-4aad4311-1352-4704-890e-3a2f2603bded.png) 
就像这样），目前这样感觉会误看成最小化按钮

**Comment by ci010** [comment]
好罢，老 issue 了，你会在下一个版本看到它 d0f304790a86d0e816d22f7c81bc999f9ae62b7a
