### ISSUE TITLE
首次启动报错

### ISSUE THREAD

**Issue by xban12** [Voxelum/x-minecraft-launcher#367]
安装后下载完纯净游戏文件后第一次启动就报错：

![image](https://user-images.githubusercontent.com/77780051/199269165-6cd295c3-e461-4408-9c10-f52094e7a7ae.png)

本机用旧版本的启动器和别的启动器可以正常启动游戏

尝试过重装启动器、重新使用一个设置新的数据目录、

看这个截图和主要报错也猜测过权限问题，但后来文件夹权限全开一样依然报这个错
![image](https://user-images.githubusercontent.com/77780051/199269591-9f045511-76a6-4529-8271-5b211a916926.png)

![image](https://user-images.githubusercontent.com/77780051/199270238-a992e694-9f9e-4a70-a6e0-ab356a34f7b8.png)

完整报错信息：
```

ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (C:\Program Files\WindowsApps\XMCL_0.32.7.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:25:6319)
    at C:\Program Files\WindowsApps\XMCL_0.32.7.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:25:5558
    at Immediate._onImmediate (C:\Program Files\WindowsApps\XMCL_0.32.7.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:25:6102)
    at process.processImmediate (node:internal/timers:466:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)

```

完整报错文件：

[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/9911626/report.zip)

幸苦开发大大有空的时候帮忙看看！

**Comment by ci010** [comment]
![image](https://user-images.githubusercontent.com/8425057/199492850-62ee4e27-a588-436c-b901-8bb2ba2db865.png)

看来是authlib injector请求失败……因为现在启动器支持了离线皮肤，所以离线模式会用 authlib injector 让客户端显示皮肤，好像现有的办法你就是多重试几次，说不准就下载下来了，我下个版本会修一下，让这个东西下载失败不至于阻止正常启动

**Comment by ci010** [comment]
#369 新版本应该修复了这个问题，限制authlib injector下载不下来也不会导致不能启动了

**Comment by xban12** [comment]
> #369 新版本应该修复了这个问题，限制authlib injector下载不下来也不会导致不能启动了

好像重装了，还是不行。。

```
TypeError: Cannot read properties of null (reading 'port')
    at Object.getYggdrasilHost (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:233:53750)
    at Proxy.launch (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:220:1291)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ServiceManager.startServiceCall (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:217:23843)
    at async node:electron/js2c/browser_init:193:551TypeError: Cannot read properties of null (reading 'port')
    at Object.getYggdrasilHost (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:233:53750)
    at Proxy.launch (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:220:1291)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ServiceManager.startServiceCall (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:217:23843)
    at async node:electron/js2c/browser_init:193:551TypeError: Cannot read properties of null (reading 'port')
    at Object.getYggdrasilHost (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:233:53750)
    at Proxy.launch (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x
[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/9943793/report.zip)
64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:220:1291)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ServiceManager.startServiceCall (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:217:23843)
    at async node:electron/js2c/browser_init:193:551
```

[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/9943796/report.zip)

最新的报错，好像和之前的差不多

还有一个新bug，就是迁移文件夹的时候报错，然后新建的要迁移进去的文件夹会自动删除。
重装之前我记得是没问题的
![image](https://user-images.githubusercontent.com/77780051/200120271-a2af3f0e-c91d-4302-9a40-07e9c40b4fdf.png)

**Comment by ci010** [comment]
> > #369 新版本应该修复了这个问题，限制authlib injector下载不下来也不会导致不能启动了
> 
> 好像重装了，还是不行。。
> 
> ```
> TypeError: Cannot read properties of null (reading 'port')
>     at Object.getYggdrasilHost (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:233:53750)
>     at Proxy.launch (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:220:1291)
>     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async ServiceManager.startServiceCall (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:217:23843)
>     at async node:electron/js2c/browser_init:193:551TypeError: Cannot read properties of null (reading 'port')
>     at Object.getYggdrasilHost (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:233:53750)
>     at Proxy.launch (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:220:1291)
>     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async ServiceManager.startServiceCall (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:217:23843)
>     at async node:electron/js2c/browser_init:193:551TypeError: Cannot read properties of null (reading 'port')
>     at Object.getYggdrasilHost (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:233:53750)
>     at Proxy.launch (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x
> [report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/9943793/report.zip)
> 64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:220:1291)
>     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async ServiceManager.startServiceCall (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:217:23843)
>     at async node:electron/js2c/browser_init:193:551
> ```
> 
> [report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/9943796/report.zip)
> 
> 最新的报错，好像和之前的差不多
> 
> 还有一个新bug，就是迁移文件夹的时候报错，然后新建的要迁移进去的文件夹会自动删除。 重装之前我记得是没问题的 ![image](https://user-images.githubusercontent.com/77780051/200120271-a2af3f0e-c91d-4302-9a40-07e9c40b4fdf.png)

不是一个问题了……现在这个好像是因为本地服务器没起来导致的orz，authlib已经下载完了。迁移的问题我瞅瞅

**Comment by xban12** [comment]
> > > #369 新版本应该修复了这个问题，限制authlib injector下载不下来也不会导致不能启动了
> > 
> > 
> > 好像重装了，还是不行。。
> > ```
> > TypeError: Cannot read properties of null (reading 'port')
> >     at Object.getYggdrasilHost (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:233:53750)
> >     at Proxy.launch (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:220:1291)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
> >     at async ServiceManager.startServiceCall (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:217:23843)
> >     at async node:electron/js2c/browser_init:193:551TypeError: Cannot read properties of null (reading 'port')
> >     at Object.getYggdrasilHost (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:233:53750)
> >     at Proxy.launch (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:220:1291)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
> >     at async ServiceManager.startServiceCall (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:217:23843)
> >     at async node:electron/js2c/browser_init:193:551TypeError: Cannot read properties of null (reading 'port')
> >     at Object.getYggdrasilHost (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:233:53750)
> >     at Proxy.launch (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x
> > [report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/9943793/report.zip)
> > 64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:220:1291)
> >     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
> >     at async ServiceManager.startServiceCall (C:\Program Files\WindowsApps\XMCL_0.32.8.0_x64__ncdvebj03zfcm\app\resources\app.asar\dist\index.js:217:23843)
> >     at async node:electron/js2c/browser_init:193:551
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/9943796/report.zip)
> > 最新的报错，好像和之前的差不多
> > 还有一个新bug，就是迁移文件夹的时候报错，然后新建的要迁移进去的文件夹会自动删除。 重装之前我记得是没问题的 ![image](https://user-images.githubusercontent.com/77780051/200120271-a2af3f0e-c91d-4302-9a40-07e9c40b4fdf.png)
> 
> 不是一个问题了……现在这个好像是因为本地服务器没起来导致的orz，authlib已经下载完了。迁移的问题我瞅瞅

今天瞎整了一下两个问题好像都解决了 麻烦开发者大大了😥
