### ISSUE TITLE
希望能支持Apple Silicon，为Mac端新增arm64支持。

### ISSUE THREAD

**Issue by hetaozdh** [Voxelum/x-minecraft-launcher#374]
如题

**Comment by Choneas** [comment]
~~句号好评~~

**Comment by hetaozdh** [comment]
能否自定义JWJGL以支持1.19以下的老版本运行
同时增加macos下的arm64发行版

**Comment by LiamSho** [comment]
#264

**Comment by ci010** [comment]
大家可以试一试下载这个 https://github.com/Voxelum/x-minecraft-launcher/suites/11029267666/artifacts/559983239 看看在mac m1上支不支持，我没有m1所以没法试。

**Comment by ci010** [comment]
新版应该已经支持m1了，只不过mc arm64的库还需要手工替换
