### ISSUE TITLE
能够选择把mod放到xmcl单独的地方或者是这个.minecraft文件夹

### ISSUE THREAD

**Issue by Choneas** [Voxelum/x-minecraft-launcher#376]
*我用了很久的其他启动器了 并且有两个.minecraft目录相互依存(让我活下去doge)*
所以能出一个新功能: 直接加载.minecraft里的assets mods以及更多吗?
建议:
在设置里做一个选项 可以调整读取.xmcl或者当前的.minecraft目录

**Comment by Choneas** [comment]
@ci010 uwu😘😭😭😭

**Comment by ci010** [comment]
现在是可以添加其他.minecraft文件夹作为独立实例的，不过这方面确实需要看看具体的场景
