### ISSUE TITLE
希望不要直接显示微软账户邮箱

### ISSUE THREAD

**Issue by Choneas** [Voxelum/x-minecraft-launcher#377]
A clear and concise description of what you want to have.
点击左上角的头像的时候 能不能把右侧的头像改为玩家名 显示一个赤裸裸的邮箱如果拍视频推荐XMCL或者其他(共享屏幕)可能会被盗号的

**Comment by ci010** [comment]
现在有直播/录屏，打开之后不显示完整的账号
