### ISSUE TITLE
更方便的模组下载

### ISSUE THREAD

**Issue by SulfuricM** [Voxelum/x-minecraft-launcher#381]
![image](https://user-images.githubusercontent.com/115728428/209453435-37858b5b-31f8-489b-9200-f7164e98b4a5.png)
右键模组弹出右键菜单，下载，跳转，搜索

**Comment by ci010** [comment]
下载可以理解，跳转搜索是啥

**Comment by SulfuricM** [comment]
> 下载可以理解，跳转搜索是啥

跳转是在默认浏览器打开这个模组的页面
搜索是在所选平台用该模组的名字进行搜索

**Comment by SulfuricM** [comment]
hmm，也许还能加个复制模组名称

**Comment by ci010** [comment]
下个版本这些会加上

**Comment by ci010** [comment]
在 #400 这里新增了cf和modr的右键菜单
