### ISSUE TITLE
Installing FTB Modpack gives Cannot resolve file

### ISSUE THREAD

**Issue by ThatzOkay** [Voxelum/x-minecraft-launcher#383]
When i try to install the FTP modpack Oceanblock it get error Cannot resolve file! ./mods//AttributeFix-1.16.5-10.1.4.jar
I used winget to install the launcher
Tested with other FTB modpacs. Getting the same error
**To Reproduce**
Go to FTB tab. Click on ocean block and click install then create
Go to FTB tab
Click on any modpack
Click on install
Click on create
it will say Import FTB Inferno-1.3.0 failed
with error 
Cannot resolve file! ./mods//AEInfinityBooster-1.18.2-1.1.0+9.jar

**Expected behavior**
The profile to be succesfully created and all the mods to be downloaded

**Screenshots**
![image](https://user-images.githubusercontent.com/6585530/210141102-c8101885-5cc5-4c6e-a66e-a4601396b6e3.png)

**Environment**
 - OS: Windows 11
 - Version: v0.33.1

**Comment by ci010** [comment]
This should be fixed in https://github.com/Voxelum/x-minecraft-launcher/commit/aef5e45f96119a92e5843943f73dd90a573f424e
