### ISSUE TITLE
#BUG 關於正版帳號验证時間过期刷新問題的反馈

### ISSUE THREAD

**Issue by bowes332frank** [Voxelum/x-minecraft-launcher#386]
點擊刷新鍵沒有刷新验证信息

![屏幕截图 2022-11-14 163149](https://user-images.githubusercontent.com/61142430/210829741-72d9a9b4-7ed7-47fb-af94-45b9a7ec69d1.png)

[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/10353776/report.zip)

**Comment by ci010** [comment]
Client network socket disconnected before secure TLS connection was established

从 log 里看出貌似是完了过问题……？你重试几次会不会成功？
