### ISSUE TITLE
Modrinth大变样！

### ISSUE THREAD

**Issue by SulfuricM** [Voxelum/x-minecraft-launcher#387]
如图
![image](https://user-images.githubusercontent.com/115728428/211235626-3a881149-4195-423e-a6ee-d6af723d1fa3.png)

**Comment by SulfuricM** [comment]
模组 插件 数据包 光影 资源包 整合包

**Comment by SulfuricM** [comment]
新增两种视图

**Comment by SulfuricM** [comment]
![image](https://user-images.githubusercontent.com/115728428/211236108-958dcad0-62ec-4b26-a6d7-295f9e44b89d.png)
![image](https://user-images.githubusercontent.com/115728428/211236112-4792ea04-00f5-4f48-b6ff-23ceb3918987.png)
![image](https://user-images.githubusercontent.com/115728428/211236115-dcb89457-a108-4f59-a96a-4dfbaaf03d1f.png)

**Comment by ci010** [comment]
下个版本加 Modrinth shaderpack，但是样式暂时不变

![image](https://user-images.githubusercontent.com/8425057/211608957-3376a7b2-b335-4bd8-b411-7b6d20962aeb.png)
