### ISSUE TITLE
Improve Mod Page (mod栏大变样)

### ISSUE THREAD

**Issue by KewSauce** [Voxelum/x-minecraft-launcher#391]
mod那里能弄成双栏吗 我是这么想的 一栏是本实体所以的下载内容包括前置附属 第二栏是别的实体的 并且每个实体都有个框 包住里面的mod

**Comment by ci010** [comment]
Let's collect the improve mods manage page idea in this thread

**Comment by KewSauce** [comment]
![无标题](https://user-images.githubusercontent.com/105436747/211769727-2910a7fd-faab-4da5-aa5c-d3dfd07faf4c.png)
我的想法s

**Comment by KewSauce** [comment]
还有能在启动的时候可以可以强制关闭

**Comment by ci010** [comment]
总结现在几个 issue，我觉得一些可能的做法有：
- Mod界面只显示当前实例下 mods 文件夹中的 mod 文件
- 开关按钮变成给文件加 .disabled 后缀效果
- Mod界面右上角新增添加按钮点击后进入添加 Mod 界面

添加Mod界面只显示没安装过的。
- 上面的过滤变成搜索，会从curseforge modrinth中搜索出相关结果（匹配当前版本，当前forge，fabric等）
- 每个卡片后面变成加号（+）？
- 点击添加后将会把mod添加到安装列表里（类似于“购物车”）
   - 购物车的ui还没完全想好，可以设计一下
- 在列表最后点击确定（或者）安装，这样的好处是可以解决
  - 频繁切换modrinth/curseforge页面导致内存过大的问题
  - 还可以解决安装不同版本导致一堆依赖的问题（因为批量计算）

**Comment by ci010** [comment]
![image](https://user-images.githubusercontent.com/8425057/225506195-a46b1f65-255f-4f50-999b-dc17ba4c529d.png)

Current status on UI

**Comment by TsaiTou2926** [comment]
> ![image](https://user-images.githubusercontent.com/8425057/225506195-a46b1f65-255f-4f50-999b-dc17ba4c529d.png)
> 
> Current status on UI

這東西都存到哪去啦

**Comment by ci010** [comment]
> 存到 .xmcl/mods 文件夹下
