### ISSUE TITLE
修改游戏图标

### ISSUE THREAD

**Issue by KewSauce** [Voxelum/x-minecraft-launcher#395]
修改游戏本体图标

**Comment by KewSauce** [comment]
抱歉，第一次用，下次不会了，谢谢提醒。
Sorry for the first time, not next time, thanks for the reminder.
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Tianyu ***@***.***>
发送时间: 2023年1月10日 23:02
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Voxelum/x-minecraft-launcher] 修改游戏图标 (Issue #395)


你这样发Issues等于搞Spam，所有的Watchers都会被邮件轰炸，请自重

―

**Comment by ci010** [comment]
resolved in 0.35.3
