### ISSUE TITLE
XMCL 简体中文的 Modrinth 搜索框为空时显示"搜素"

### ISSUE THREAD

**Issue by COUNTRYSMAQUE** [Voxelum/x-minecraft-launcher#396]
如题,看起来就挺奇怪的

**重现步骤**

1.语言设为"简体中文"
2.前往 Modrinth 主界面
3.在不输入的情况下看搜索框

**期望结果**
搜索框不再显示"搜素"而是"搜索"

**版本**
 - 系统: Windows
 - 版本: Windows 10 专业版 21H2
 - XMCL: v0.33.1

**Comment by ci010** [comment]
应该是typo打错了【
