### ISSUE TITLE
在minecraft 1.8和1.7上安装forge失败

### ISSUE THREAD

**Issue by Broken-Deer** [Voxelum/x-minecraft-launcher#397]
在minecraft 1.8 和 1.7上安装forge失败，使用@xmcl/installer这个npm包安装同样失败

**To Reproduce**

1. 新建本地游戏
2. minecraft版本选择1.7.2，forge任选一个版本
3. 创建后安装游戏

**Expected behavior**
正常地安装游戏

**Screenshots**
![image](https://user-images.githubusercontent.com/64290747/212848986-207bbff6-f61d-457f-920d-6dfefa5d7cdd.png)

**Environment**
 - OS: Windows_NT
 - Version 10.0.19045

**Additional context**
使用@xmcl/installer安装也是同样的报错

**Comment by Broken-Deer** [comment]
补充错误报告
[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/10432886/report.zip)

**Comment by ci010** [comment]
啊，下个版本修

**Comment by ci010** [comment]
https://github.com/Voxelum/x-minecraft-launcher/commit/9dc504c401dc650f0a1084c54fbc46b3ad0d2a09
这个应该修了，话说启动器现在暂时还不会提示这个版本的forge不兼容java8……恐怕得用户自己注意

**Comment by Broken-Deer** [comment]
好的，谢谢！
