### ISSUE TITLE
Launch Failed: Error: spawn UNKNOWN at ChildProcess.spawn 

### ISSUE THREAD

**Issue by yodaluca23** [Voxelum/x-minecraft-launcher#402]
On a school computer, (Network is leveled at Symmetric NAT) so that may be the problem, but, I finally found a way to install java, but when I launch it gives me this screen:
![image](https://user-images.githubusercontent.com/67206487/216711555-28a8ad75-862b-4671-a88e-b1daf2da7c51.png)
I have tried Fabric, Vanilla, Optifine, etc.

**Expected behavior**
It launch with no issues...

**Environment**
 Edition	Windows 10 Education
Version	21H2
Installed on	‎8/‎10/‎2022
OS build	19044.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0
 - Version v0.33.1, latest

**Additional context**
It gives the option to generate a report it is below:
[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/10582842/report.zip)

**Comment by ci010** [comment]
Can you check the java you are using `C:\\Users\\s621306\\.jdks\\temurin-17.0.6\\bin\\java.exe`. Is this file a correct java executable?

As from previous log

```log
[INFO] [2/3/2023, 9:02:20 AM] [JavaService] Try resolve java C:\Users\s621306\.jdks\temurin-17.0.6\bin\java.exe
[INFO] [2/3/2023, 9:02:20 AM] [JavaService] Release singleton JavaService.refreshLocalJava(). Took 1063ms.
[INFO] [2/3/2023, 9:02:20 AM] [JavaService] Found in memory valid java 17.0.6 in C:\Users\s621306\.jdks\temurin-17.0.6\bin\java.exe
```

The java exe should be a valid executable.

Whereas the error `spawn UNKNOWN` is the case that the file is not executable.
I'm sure it's not caused by "file not found" or passing an undefined value (nullpointer) to spawn process function.

**Comment by yodaluca23** [comment]
> Can you check the java you are using `C:\\Users\\s621306\\.jdks\\temurin-17.0.6\\bin\\java.exe`. Is this file a correct java executable?
> 
> 
> 
> As from previous log
> 
> 
> 
> ```log
> 
> [INFO] [2/3/2023, 9:02:20 AM] [JavaService] Try resolve java C:\Users\s621306\.jdks\temurin-17.0.6\bin\java.exe
> 
> [INFO] [2/3/2023, 9:02:20 AM] [JavaService] Release singleton JavaService.refreshLocalJava(). Took 1063ms.
> 
> [INFO] [2/3/2023, 9:02:20 AM] [JavaService] Found in memory valid java 17.0.6 in C:\Users\s621306\.jdks\temurin-17.0.6\bin\java.exe
> 
> ```
> 
> 
> 
> The java exe should be a valid executable.
> 
> 
> 
> Whereas the error `spawn UNKNOWN` is the case that the file is not executable.
> 
> I'm sure it's not caused by "file not found" or passing an undefined value (nullpointer) to spawn process function.
> 
> 
> 
> So I don't have much idea now... The case is really interesting...
> 
> 
> 
> 

I mean, there is a Java executable there if that's what you mean… could it be that my user doesn't have the privileges to run any executable files? But that wouldn't explain why other launchers like [rolaunch](https://github.com/rajansrohit/java-rolaunch-minecraft-launcher) work…
