### ISSUE TITLE
Add offline account support back

### ISSUE THREAD

**Issue by pawa2401** [Voxelum/x-minecraft-launcher#403]
Why was it removed? I liked having a second non premium account that I could use as an alt.
Please add it back, or if this i bug and it is not appearing, then please fix it

**Comment by CornetPanique86** [comment]
The launcher had to remove cracked account support to be promoted by modrinth as an app which uses its API.
However if you purchased a premium account you can also create cracked accounts, and there's also a bypass by using other authentification services like littleskin.cn. At least that's what I understood, maybe some of what I said is incorrect

**Comment by NerdsForGaming** [comment]
As of now, I am currently working on a fork that adds cracked support back. It seems to me that it just works without having to do anything. I can send a test sample , but it will only be on ubuntu.

**Comment by NerdsForGaming** [comment]
> As of now, I am currently working on a fork that adds cracked support back. It seems to me that it just works without having to do anything. I can send a test sample , but it will only be on ubuntu.

and i would legitimately not want to do that cause github.

**Comment by pawa2401** [comment]
> As of now, I am currently working on a fork that adds cracked support back. It seems to me that it just works without having to do anything. I can send a test sample , but it will only be on ubuntu.

Hey. Thanks for the offer, but unfortunately I use Windows, so I'll have to pass

**Comment by pawa2401** [comment]
> The launcher had to remove cracked account support to be promoted by modrinth as an app which uses its API. However if you purchased a premium account you can also create cracked accounts, and there's also a bypass by using other authentification services like littleskin.cn. At least that's what I understood, maybe some of what I said is incorrect

How can I create cracked accounts? I'm logged in to the launcher via the Microsoft login and I still don't see Cracked option when adding a new account.

**Comment by pawa2401** [comment]
Ok. I am dumb. I apparently tried to add the offline account before adding my premium one, because the option shows up now. Thanks.
