### ISSUE TITLE
Add support for pre-realease versions of minecraft 

### ISSUE THREAD

**Issue by LittleBigBug** [Voxelum/x-minecraft-launcher#404]
Allow installing earlier versions of minecraft, like [beta 1.7.3](https://minecraft.fandom.com/wiki/Java_Edition_Beta_1.7.3), or indev for example

(not sure if this ticket has already been created, I dont speak chinese)

**Comment by ci010** [comment]
Just like @SulfuricM mentioned, you can select pre-release in the Minecraft version select dropdown when you click the "bug" icon on the top left. Does this resolve your issue?
