### ISSUE TITLE
ely.by login error 

### ISSUE THREAD

**Issue by ZackSilba** [Voxelum/x-minecraft-launcher#405]
whenever i want to login it says wrong password even though it's correct 
also clicking on forget password sends me to minecraft login page :)
ely.by login option is not working so i had to login via mojang

**Comment by ci010** [comment]
Can you provide a report file to me? I cannot repro this issue.
Click the question mark on the titlebar:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/8425057/219565807-714b517b-f148-4bb7-8eec-181c6893745a.png">

**Comment by ZackSilba** [comment]
sorry for the late report here it is

**Comment by ZackSilba** [comment]
[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/10813325/report.zip)

**Comment by ci010** [comment]
Should be fixed in new version
