### ISSUE TITLE
聚焦布局将导致警告挡住实列启动按钮

### ISSUE THREAD

**Issue by SulfuricM** [Voxelum/x-minecraft-launcher#406]
![image](https://user-images.githubusercontent.com/115728428/217495735-cb01ae3a-e069-43fb-982b-c1b75180764f.png)

**Comment by SulfuricM** [comment]
坏，Java11也不让用

**Comment by NerdsForGaming** [comment]
两个 java 版本都是允许的，我可以得到一些日志吗？您可以通过单击右上角的帮助图标来生成它们

I am using google translate so please excuse my trash translations

**Comment by SulfuricM** [comment]
[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/10724582/report.zip)
我希望这不会泄漏我的个人信息

**Comment by SulfuricM** [comment]
> 

I found the problem

**Comment by SulfuricM** [comment]
And the translation looks great

> 两个 java 版本都是允许的，我可以得到一些日志吗？您可以通过单击右上角的帮助图标来生成它们
> 
> I am using google translate so please excuse my trash translations

I found the problem. And the translation looks great.

**Comment by SulfuricM** [comment]
> 两个 java 版本都是允许的，我可以得到一些日志吗？您可以通过单击右上角的帮助图标来生成它们
> 
> I am using google translate so please excuse my trash translations

I found the problem. And the translation looks great.

**Comment by ci010** [comment]
Should resolved by #408
