### ISSUE TITLE
No offline option

### ISSUE THREAD

**Issue by EliasMonte** [Voxelum/x-minecraft-launcher#407]
**No offline option in 0.34 version**
**the offline option is present on 0.33.1 and olders versions, but in 0.34 the offline option is no avaliable why?**

**Screenshots**
Version 0.34
https://i.imgur.com/N8uDVJX.png
Version 0.33.1
https://i.imgur.com/i0pILHV.png

**Environment**
 - OS: Windows
 - Version [11]

**Comment by NerdsForGaming** [comment]
This is not a bug. This has been done intentionally, To add this launcher to https://github.com/modrinth/awesome/ , the author had to remove cracked support. He is currently planning to add back cracked but for people who have already logged in with a premium account. Still it would not be helpful for people who have cracked accounts. Hence I am trying to add back cracked support in a fork. To see the progress on the fork , Join the official X Minecraft Launcher discord. https://discord.gg/HSrgSkyuhS

**Comment by ci010** [comment]
In new version, enable developer mode should see the offline mode.
