### ISSUE TITLE
模组管理功能加强

### ISSUE THREAD

**Issue by SXN2580** [Voxelum/x-minecraft-launcher#413]
在拥有多个不同版本实例时，在模组设置界面拥有大量其他实例模组，且总mods文件夹和实例mods文件夹重复，它占用了我大量的空间，能否添加可以将不同实例完全隔开的功能，在拥有多个整合包时，模组列表大量的模组难以分辨。或者说有这个功能，只是我没有发现，且资源包和光影文件夹也是一样，在不同版本时，当我打开资源包设置，里面总是有大量其他版本的资源包。

**Comment by SXN2580** [comment]
我非常喜欢这个启动器的UI和不同版本管理，但是当我删除位于.xmcl\instances\Minecraft\mods文件夹的模组时，位于.xmcl\mods文件夹内的模组依然存在，这导致我的模组设置界面非常乱

**Comment by ci010** [comment]
#391 会重新设计mod管理界面，并尝试解决mod管理不方便的问题。目前的想法是实例mod界面只显示instances\Minecraft\mods 中有的mod。用户需要点击安装（可能是加号）来添加更多的mod，这时候才显示所有的mod。这个更新最快也要一周后出来了

**Comment by ci010** [comment]
现在 Mod 管理的界面重做了 ~抄袭了 VSCode~

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/8425057/2db2abf8-5670-4bf6-903e-a5ca8b0d7726)

希望这个能解决你的问题
