### ISSUE TITLE
Downloading dependencies, modlists

### ISSUE THREAD

**Issue by Reloecc** [Voxelum/x-minecraft-launcher#420]
I am not sure if it's implemented or not, we may delete this if so. But those functions are so obvious I believe I am rather bad at using them:

1) I believe I got how to correctly download mod, I create game instance, and "Manage mods" to it. I see version checks in mod list.. but when Mowzie's mobs depends on Geckolib.. am I supposed to download it separately by my own? Why is the launcher not doing it for me?

2) Same apply to mod lists.. man.. I have no idea how to work with them. There [ + ] buttons in the "Files" section of every modlist. Clicking popup window, where I am supposed to enter a name, pick mc version and forge / fabric versions etc. Why the launcher doesn't select correct mc and forge versions for me? And.. what to do next? This popup creates a vanilla mc instance for me and no mods from modlist are added.. So again: Is the launcher cappable of one-button downloading the modlist? Please how?

I am really sorry if have not found those features and they are present. But without this behaviour, I really don't get how is the launcher usefull, so I have to ask. Thank you..

**Comment by ci010** [comment]
Current managing mod & install mod features are just the basic implementation.

I'm working on a designed UI to improve the mod installation #391.
