### ISSUE TITLE
Can't make worlds on certain modpacks

### ISSUE THREAD

**Issue by goo-09** [Voxelum/x-minecraft-launcher#422]
Unable to create worlds in certain modpacks
When trying to create worlds in certain modpacks. An error will pop up (screenshot below), when investigating further, it seems that datapacks from all modpacks/instances are synced into this one. I have no idea which datapacks are intended to pair with the specified modpack (look below) which means I am unable to manually select the correct datapacks.

**To Reproduce**

1. Launch DawnCraft or Encrypted_ (tested positive for issue)
2. Click on Singleplayer (launching modpack and everything else should be fine)
3. Click on Create World
4. An error would appear suggesting you to generate world with only vanilla datapacks (which also doesn't work) or return to title screen

**Expected behavior**
Only Intended datapacks should be loaded and world creation should happen without any problems.

**Screenshots**
![image](https://user-images.githubusercontent.com/25366582/227441337-650620e0-a7d3-4aef-a7f1-496cd627ce9f.png)
![image](https://user-images.githubusercontent.com/25366582/227440264-affde421-6918-4ca8-8323-298b8026ed7e.png)
![image](https://user-images.githubusercontent.com/25366582/227440727-5149c67e-1bf5-42f8-b708-fc4dfc3e00ca.png)

**Environment**
 - OS: Windows 10
 - Version: v0.34.1

**Additional context**
This only happens with some modpacks.

**Comment by goo-09** [comment]
update: like the idiot i am i left the steps to reproduce as comments, the steps to reproduce can be seen now. sorry about that

**Comment by ci010** [comment]
Are you sure that's not a bug for that modpack

**Comment by goo-09** [comment]
There's a few modpacks(cant rmbr) that have the same issue but not on other launchers without the universal mod/resourcepack/datapack thing. Currently using prism launcher for DawnCraft right now and it works.
