### ISSUE TITLE
新增一個開關設定關於資源包的

### ISSUE THREAD

**Issue by LiuTouo** [Voxelum/x-minecraft-launcher#423]
能增加一個開關，讓資源包可以個別實例獨立出來，或是像預設的就是都是用捷徑的方式。
覺得用捷徑的方式讓每個實例共通這個想法不錯，只是資源包跟實例多了後，就會很亂，很難找到要用的或是不知道是不是這個模組包可以用的資源包。

**Comment by ci010** [comment]
修完现在的bug考虑搞搞

**Comment by ci010** [comment]
现在已经有了
