### ISSUE TITLE
consider migratation to another framework

### ISSUE THREAD

**Issue by softonicblip** [Voxelum/x-minecraft-launcher#424]
It doesn't make me comfortable at all seeing a launcher using Electron.

Tauri it's very much like Electron, but it doesn't bundle Chrome on every application (instead it uses WebView2), consumes much less RAM than Electron, it's more secure, and cross-platform too.
I don't really know how much work it needs to migrate but if you can, then better not only for me but for anyone who download this.
And if Tauri isn't enough, there's some other alternatives like [Wails](https://wails.io/), [Neutralino](https://neutralino.js.org/), i just came across this one called [conveyor](https://www.hydraulic.software/), etc.

**Comment by ci010** [comment]
Not considered at the moment.
