### ISSUE TITLE
Linux安装后桌面图标为透明

### ISSUE THREAD

**Issue by CDmking** [Voxelum/x-minecraft-launcher#425]
安装deb版本的安装包后发现desktop文件透明，不显示图标。

经排查，发现opt文件夹下可执行文件'xmcl'本身不携带图标文件。

建议制作Linux安装包时将图标文件单独引用，如：`Icon=/opt/'X Minecraft Launcher'/xmcl.png`

**Comment by ci010** [comment]
我没linux，非常欢迎PR来修复这个问题

**Comment by CDmking** [comment]
由于无法以修改源代码方式解决问题，故关闭该议题。
