### ISSUE TITLE
The latest version opens with a full black window after installation

### ISSUE THREAD

**Issue by Tartuffe-X** [Voxelum/x-minecraft-launcher#427]
<! -- **The latest version opens with a full black window after installation** -->
<! --AppX installation, either overwritten or uninstalled, opens with a black window and no interaction, but of course I haven't tried restarting the PC afterwards. -->

**To reproduce**

<! -- 1. Install the latest version. -->
<! -- 2. Launch (ಥ_ಥ -->

**Expected behavior**
Normal use.

**Screenshot**
![image](https://user-images.githubusercontent.com/53497455/236621764-459c3141-f3f0-4af9-83c6-ff130ea63eeb.png)
emm i know this screenshot is completely useless, but only put up to express my feelings

**Environment**
 - Operating system: [win11].
 - Version [22H2].

**Comment by ci010** [comment]
Fixed in 5dbf1dabe8640fd7d1a73dd35aa4007444286e40
