### ISSUE TITLE
XMCL Can't hide kde plasma close/maximize/minimize buttons

### ISSUE THREAD

**Issue by Dandraghas** [Voxelum/x-minecraft-launcher#437]
When opened any xmcl page it doesnt hide standart kde buttons.

**To Reproduce**
1. Open XMCL
2. See That Everything Broken

**Expected behavior**
XMCL hide kde buttons

**Screenshots**
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/91272905/ad992cc3-420d-4845-a2bf-bc2a9a756e70)

**Environment**
 - OS: Fedora 38

**Additional context**
How xmcl handle this? did it even designed to run on plasma?

**Comment by ci010** [comment]
Fixed in #436
