### ISSUE TITLE
New version of mod downloader bug (serious)

### ISSUE THREAD

**Issue by TsaiTou2926** [Voxelum/x-minecraft-launcher#438]
Mod Downloader Bug
 Mod Downloader cannot be back to previous page.

**To Reproduce**

 Open Mod Downloader in 0.35.6 (CurseForge or Modrinth) ->
 "<-" button on upper left ->
 cannot be back

**Expected behavior**
Download one mod, resource pack, or mod pack at a time
You need to restart the mod download tool
Seriously affect the user experience

**Screen recording**
[Visit the video](https://drive.google.com/file/d/1OiLGx6ZeOckrgLZY0D6IgKyy_wtLVPHs/view?usp=sharing)

**Environment**
 - OS: Windows 11
 - Version 22H2

**Additional context**
Hope it fix ASAP

**Comment by ci010** [comment]
Should be fixed in #436
