### ISSUE TITLE
无法打开软件

### ISSUE THREAD

**Issue by reana-ovo** [Voxelum/x-minecraft-launcher#442]
软件无法启动
安装完打不开
**To Reproduce**

打开软件

**Environment**
 - OS: Windows 11 Home
 - Version 22H2 Build 22621.1778

**Additional context**

**Comment by ci010** [comment]
看来是修linux titlebar的一个fix导致了这个匪夷所思的问题，win10上居然没问题。今天发新版本修这个。

**Comment by reana-ovo** [comment]
> 看来是修linux titlebar的一个fix导致了这个匪夷所思的问题，win10上居然没问题。今天发新版本修这个。

我属于直接蹲到了更新23333
