### ISSUE TITLE
"Hide News" option resets after restating the launcher

### ISSUE THREAD

**Issue by Soham52** [Voxelum/x-minecraft-launcher#446]
The "Hide News" automatically resets to off, regardless of what the user sets it to, after restarting the launcher.

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/73898737/8c9d9a6e-e318-46fa-b410-bb605947795a)

**Comment by ci010** [comment]
Fixed in 30db47b43c74df317f8169bc067f08b0db4056a3. This will be fixed in 0.35.11
