### ISSUE TITLE
Cant download Forge 1,12,2

### ISSUE THREAD

**Issue by Timasbro** [Voxelum/x-minecraft-launcher#451]
Reproduce:
1) Add instance of Forge 1.12.2 latest version
2) Click Install
3) get error  
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/76243250/85a1be1a-ffce-4fb9-9cc0-8efcc886b3a5)
4) Click fix error
5) Error not fixing

Windows 11
Newest version

**Comment by Timasbro** [comment]
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/76243250/aae48f7b-9801-4efb-a699-82ce16f759c8)

**Comment by ci010** [comment]
Should be mitigated in #452
