### ISSUE TITLE
Mismatch between nodejs version in package.json and contribution guide

### ISSUE THREAD

**Issue by star0202** [Voxelum/x-minecraft-launcher#457]
In Guide: node.js v16
In package.json: "node": ">=18"
This causes below warning when installing deps:
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/61998307/99092487-2b4b-4b66-b371-157f782cd261)

Version info:
node.js: v16.20.0
pnpm: 8.2.0

**Comment by ci010** [comment]
This should not have any actual effect. You can ignore it for now.

Last time I want to try to upgrade the version lower bound but it seems the electron is not ready for that.

I will fix this back when I have time.
