### ISSUE TITLE
在Modrinth页面点开任意一个模组的详细页面均无法返回上一级

### ISSUE THREAD

**Issue by xswadmin24755** [Voxelum/x-minecraft-launcher#458]
**To Reproduce**

1.点击任意一个模组的详情页面
2.左上角的返回按钮就没有用

**Expected behavior**

**Screenshots**

**Environment**
 - OS: Windows 11

**Additional context**

**Comment by ci010** [comment]
又是一个只在生产环境的奇怪bug，今天发新版本修复

**Comment by ci010** [comment]
#456 应该修复了，顺便修复了在主页跳转 cf 或 modrinth 的页面不会被聚焦的问题
