### ISSUE TITLE
Wrong update file type

### ISSUE THREAD

**Issue by pawa2401** [Voxelum/x-minecraft-launcher#461]
**To Reproduce**

Try to update older version of the windows zip launcher version.

**Expected behavior**
Should download the windows zip version and update itself in the folder it's located in.
Instead it downloads an .appinstaller version.

**Screenshots**

**Environment**
 - OS: Windows
 - Version 0.35.5 (Trying to update to 0.35.17)

I know that am using an older version of the launcher, but I didn't see anything related being fixed in update reports of the newer vesions.
Also please inform me how to update the zip version manually. I'd be grateful.

**Comment by ci010** [comment]
Should fixed
