### ISSUE TITLE
Linux端Desktop文件中StartupWMClass应为xmcl

### ISSUE THREAD

**Issue by shenzhuoyan** [Voxelum/x-minecraft-launcher#464]
通过xprop可以看到窗口名为xmcl, 如果StartupWMClass不写成xmcl会导致无法右键锁定到dock栏。

**Comment by BuWH** [comment]
@shenzhuoyan StartupWMClass 具体指的是什么？代码里似乎没有看到设置这个的东西

**Comment by ci010** [comment]
> @shenzhuoyan StartupWMClass 具体指的是什么？代码里似乎没有看到设置这个的东西

linux 的一些设置，主要是现在没有linux主力机，目前已知的情况还有linux下安装桌面图标不对的问题

**Comment by ci010** [comment]
> 通过xprop可以看到窗口名为xmcl, 如果StartupWMClass不写成xmcl会导致无法右键锁定到dock栏。

这个我好像找到在哪改了，顺便问一下现在的desktop文件图标显示是对的么

**Comment by ci010** [comment]
#462 should fix this.
