### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by SulfuricM** [Voxelum/x-minecraft-launcher#468]
窗口化全屏应用，重启应用后变回窗口化

设置
重启应用后保存的 第三方玩家信息服务 清空

实列设置
有两个选项默认不是全局，且重启应用后本已设置为全局的Java内存将变回实列配置
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/115728428/f49556b0-a603-46e0-aad0-5fcb6fa05fbc)

Modrinth
游戏版本乱序
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/115728428/9e208ed6-7da8-4477-b861-a3c2ee1c5829)
模组加载器不正确
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/115728428/e71c4c05-ff89-40d1-a77c-b01f9f0d429e)
下载会下载所有文件
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/115728428/43e5a9ff-52b2-4e31-9aa4-2639854db248)

**Comment by Orange-Summer** [comment]
我也有类似的问题，自己手动添加的 Java 路径，然后删了里面自动检测到的几个，每次重新启动以后就又恢复一开始了
