### ISSUE TITLE
Global Options for both MC and JVM seems not to work

### ISSUE THREAD

**Issue by MessyGhost** [Voxelum/x-minecraft-launcher#470]
**Description**
![global options is specified](https://github.com/Voxelum/x-minecraft-launcher/assets/39986054/5402b359-4a3a-469f-9f69-67344085a713)
![but isn't used](https://github.com/Voxelum/x-minecraft-launcher/assets/39986054/b33ab554-51b4-4a54-b2fc-9d338f7f9bff)
I have specified global options for mc (to set a resolution), but it doesn't work. As printed in the preview, the options weren't used to launch the client. However, instance options work good.

**Environment**
 - OS: Windows 11 22621.1848

 - Version 0.35.18

**Comment by MessyGhost** [comment]
I have found that this problem is caused by initializing `mcOptions` and `vmOptions` by empty arrays instead of `undefined`, while whether they're `undefined` indicates whether global options should be used. 
I thought it was a simple problem, but I was wrong. Since I know little about the project, I think it would be better to redesign the logic of "whether to use global options" by one who knows it better.

**Comment by ci010** [comment]
will take a look soon

**Comment by ci010** [comment]
Should fixed in https://github.com/Voxelum/x-minecraft-launcher/commit/67c28a7fda2c5c307316774b9cebd57040489e7e. Wait for next release or you can try the build artifacts on master branch
