### ISSUE TITLE
Linux Mint 没图标

### ISSUE THREAD

**Issue by shenzhuoyan** [Voxelum/x-minecraft-launcher#475]
在Linux Mint中，没有图标

**Environment**
 - OS: Linux Mint 
 - Version 21.2
 - DE: Cinnamon 5.8.3
 - Icons: Papirus

**Additional context**
我看DEB包是把图标放在了`/usr/share/icons/hicolor/0x0/apps/xmcl.png`，然后我看vscode是把图标放在了`/usr/share/pixmaps`，我就试着把`xmcl.png`也复制过去：`sudo cp /usr/share/icons/hicolor/0x0/apps/xmcl.png /usr/share/pixmaps`，然后图标就正常了。

**Comment by ci010** [comment]
我对linux的安装方式不太了解，deb安完了也是靠 desktop 文件指定图标的么，还是这个是其他的机制

**Comment by ci010** [comment]
https://github.com/electron-userland/electron-builder/issues/2654 尝试一下这个 f3b74fdd1093b67d3947b6ee02a347df9f85ab88. 看看这个 build 出来的 deb 是不是正常的图标

**Comment by shenzhuoyan** [comment]
> [electron-userland/electron-builder#2654](https://github.com/electron-userland/electron-builder/issues/2654) 尝试一下这个 [f3b74fd](https://github.com/Voxelum/x-minecraft-launcher/commit/f3b74fdd1093b67d3947b6ee02a347df9f85ab88). 看看这个 build 出来的 deb 是不是正常的图标

build出来的deb是正常的图标，没问题
