### ISSUE TITLE
Modpacks won't install

### ISSUE THREAD

**Issue by crystalclean69** [Voxelum/x-minecraft-launcher#479]
**To Reproduce**

**Expected behavior**
Modpack installation

**Screenshots**
![ddUqJgRYSi](https://github.com/Voxelum/x-minecraft-launcher/assets/140109790/4c443719-7c6d-494b-b3c7-a7a10778b114)
![X_Minecraft_Launcher_LLTG2XxQQn](https://github.com/Voxelum/x-minecraft-launcher/assets/140109790/9a7acd28-2a03-4be8-8193-0e6d31765659)

**Environment**
 - OS: Windows 11
 - Version 22h2

**Additional context**

**Comment by ci010** [comment]
Closed due to the issue is not repro
