### ISSUE TITLE
Console / logger screen. 

### ISSUE THREAD

**Issue by coolbot100s** [Voxelum/x-minecraft-launcher#482]
The current logger (none) is very difficult to parse with the naked eye, which can make developing while using the launcher much harder compared to other launchers which have a clean console viewer with search and syntax highlighting functionality built in. 
This would be a hugely helpful QOL feature as without it, developing mods and modpacks is more difficult.

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/76798835/4474c52c-8d55-4d27-8d4e-c22d73b9c697)
_PrismLauncher Minecraft Console as example_

**Comment by ci010** [comment]
The launcher has the log screen.

You need to enable it here.
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/8425057/ac076799-e3d0-45bb-a5db-d443d93f3bfa)
