### ISSUE TITLE
Add a option to change the instance icon :D

### ISSUE THREAD

**Issue by AnikioRevived** [Voxelum/x-minecraft-launcher#487]
I want a option to change the instance icon like in the original minecraft launcher with some presets and a option to add a custom by yourself 
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/134894133/47940bd0-f648-4525-a8e5-23d519fe3092)

**Comment by ci010** [comment]
We can change the icon before the set name option 

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/8425057/4a6c7689-46af-4153-a5eb-273da3c04630)

**Comment by AnikioRevived** [comment]
:0 i didnt see that
