### ISSUE TITLE
cant find a option to turn off hard/symbolic links to install resources in instances

### ISSUE THREAD

**Issue by CodeKartonka** [Voxelum/x-minecraft-launcher#488]
cant find a option to turn off hard/symbolic links to install resources in instances.

many bugs:
some mods vanish, then there turn enabled, or in mods folder are mods that i did in instance folder delete.

turn off hard/symbolic links vor me would be perfect, just dont need it.

sry for bad english.

i like u work!

**Comment by ci010** [comment]
now we could switch between link or not link by clicking button
