### ISSUE TITLE
Microsoft Auth No Longer works

### ISSUE THREAD

**Issue by AngellusMortis** [Voxelum/x-minecraft-launcher#495]
**To Reproduce**

1. Upgrade to 0.36.0 (with a working Microsoft account setup)
2. Start forge modpack from 0.35.19
3. Cannot join servers

(also tried removing/adding new account)

**Expected behavior**

Microsoft Account login should work

**Environment**
 - OS: Windows 11 (appx install)
 - 0.36.0

**Additional context**

Downgrading to 0.35.19 and removing/re-adding the account fixes it.

**Comment by ci010** [comment]
#497 should fix

**Comment by ci010** [comment]
@AngellusMortis Can you try to download the build from https://github.com/Voxelum/x-minecraft-launcher/suites/17187117952/artifacts/982127063 to verify if this issue is resolved?

This will download a zip and you just need to unzip it to run

**Comment by AngellusMortis** [comment]
Looks good. Thanks! Really excited for the launcher to get more stable and features. It is already way better than the other open-source alternatives. Keep up the great work!
