### ISSUE TITLE
Better Mod Metadata Management (Curseforge/Modrinth)

### ISSUE THREAD

**Issue by AngellusMortis** [Voxelum/x-minecraft-launcher#503]
It would be nice to have the mod metadata be combined for mods. It is awesome I can search both Curseforge and Modrinth for mods, but if I am trying to build or maintain a modpack, that poses a bit of a challenge. 

So, it would be great if each mod entry just could know about both sources for the mod. 

Example, one mod that has Curseforge metadata and one that has Modrinth metadata, however, both mods exist in both locations. So instead of showing "search on __" for the other one, it should just know the location for both. 

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/490848/ca8be14e-12c1-4547-91b9-d70741011a14)
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/490848/2cfb427f-ae7e-42ec-8e7b-a7811392bea2)

Similarly, if the launcher knows about both mod sources, it can show descriptions from both sources. So probably something around here pick between them. It can of course default to the default metadata source as configured by the user. 

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/490848/d69f0b73-8b33-4a19-bcfa-1400d00baed0)

Part of this would likely also be being able to "link" a mod entry to a metadata source/mod ID. I do not have a good example of a mod loader that allows this, but Plex has something similar for TV/movies:

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/490848/c7815fb1-c99a-433b-b0e6-f7b8ac325c21)
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/490848/4d98defe-6e48-4ff0-a3a5-5195e8b5000a)

**Comment by AngellusMortis** [comment]
Yeah, then it sounds like the big thing that is missing is the ability to add a metadata source for a mod. I think having an automatic link is great (like if you have the Curseforge metadata you automatically add the Modrinth metadata).

I do still think manual linking from the user interface is a good idea. If a user manually download a JAR and put into mods folder, it will not have any metadata at all.

**Comment by ci010** [comment]
I think this issue is partially resolved as currently, both modrinth and curseforge can match from the API.
