### ISSUE TITLE
资源包无法正确加载

### ISSUE THREAD

**Issue by ddzzkunye** [Voxelum/x-minecraft-launcher#523]
### To Reproduce
在某个1.20.2版本的资源包页面, 对一个资源包点击启用

### Expected behavior
无任何文件或硬链接在 "_版本_"的资源包目录下创建

### Environment
 - OS: [Windows10]
 - Version [0.37.8]

### 其他
在1.20.2下, 光影包也有类似问题

**Comment by ci010** [comment]
This issue should be fixed in new version.
