### ISSUE TITLE
Issue with installing mods from modrinth tab

### ISSUE THREAD

**Issue by XSentinelu** [Voxelum/x-minecraft-launcher#525]
**Description**
After downloading a mod from the Modrinth tab, and then trying to add the mod to the pack, nothing happens. However, it helps to exit the mod page and go back to it, after which the mod can be added. The Cursforge tab works correctly.

1. Go to 'Modrinth tab'
2. Click on any mod you want to install
3. Install (download) a mod
4. Try to add mod to the pack
5. Nothing happens

**Expected behavior**
The mod is actually being added.

**Environment**
 - OS: Windows 11
 - Version 0.37.8

**Comment by ci010** [comment]
Not repro in 0.39.x

**Comment by XSentinelu** [comment]
Still present in 0.39.x. If you visiting mod page for the first time through modrinth tab, mod can't be added to the instance

**Comment by ci010** [comment]
> Still present in 0.39.x. If you visiting mod page for the first time through modrinth tab, mod can't be added to the instance

I tried the 0.39.7. It works fine. I guess you encountered some permission issues? You can generate a report and send me so I can know what's actually happening.

**Comment by XSentinelu** [comment]
> > Still present in 0.39.x. If you visiting mod page for the first time through modrinth tab, mod can't be added to the instance
> 
> I tried the 0.39.7. It works fine. I guess you encountered some permission issues? You can generate a report and send me so I can know what's actually happening.

I generated a report:
 [report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/13837749/report.zip)
