### ISSUE TITLE
issu I build my own launcher and curseforge api token error i set the .env file can you explain how to fix  it ?

### ISSUE THREAD

**Issue by aislxflames** [Voxelum/x-minecraft-launcher#526]
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

**Additional context**
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/120901302/70519a0f-da6d-4627-95f2-a18ed9d38a2e)

**Comment by ci010** [comment]
now the post install script handle the case
