### ISSUE TITLE
NeoForge Error

### ISSUE THREAD

**Issue by gfbbkon** [Voxelum/x-minecraft-launcher#528]
NeoForge error.
This bug is downloading NeoForge from Forge repo

**To Reproduce**

How to do it:

1) select NeoForge
2) click "install"
3) Get error, because XMCL though that you want install Forge and get error on download

**Expected behavior**
Change link to NeoForge site

**Environment**
 - OS: Windows 10
 - Version 0.37.8

**Comment by ci010** [comment]
Should not repro in new version
