### ISSUE TITLE
添加模组自动更新功能

### ISSUE THREAD

**Issue by xiaozhuo256** [Voxelum/x-minecraft-launcher#531]
如题，会自动检测该实例模组在同版本下是否有更新的版本号可供下载，并自动更新，已经搭载此项功能的启动器有prisim启动器，可供参考。这项功能将提升游戏体验，不必经常关注模组更新，可以省去很多工作。

**Comment by ci010** [comment]
我想问一下这个是说打开实例模组的自动更新后，定时自动检查，查到了之后就自动更新么？更新过程不用过问用户完全自动操作

**Comment by xiaozhuo256** [comment]
是的，还有mod转移功能，比如我想把1.16.5版本的整合包变成1.19的整合包，无需重新一个个查找对应mod，而是会自动查找新版本的mod并安装，我仅需一个mod列表，而不是一个个重新搜索。

**Comment by ci010** [comment]
安排！

> 是的，还有mod转移功能，比如我想把1.16.5版本的整合包变成1.19的整合包，无需重新一个个查找对应mod，而是会自动查找新版本的mod并安装，我仅需一个mod列表，而不是一个个重新搜索。

这个功能，你觉得我做怎么样的界面比较好，需要一些灵感

**Comment by xiaozhuo256** [comment]
可以添加一个“mod表单”概念，就是说把一个mod整合视为一份表单，并可以在每个实例的界面去“复制mod表单”，然后可以把mod表单套用在别的实例内，“套用该mod表单”

**Comment by xiaozhuo256** [comment]
可以把mod表单栏添加到这里
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/91036800/29e4ce6d-754c-4d2c-96b2-7d3ebc75656c)
或者把他作为mods的一个子集

**Comment by xiaozhuo256** [comment]
然后里面有一项一项的表单可供选择

**Comment by xiaozhuo256** [comment]
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/91036800/47de9f94-3d31-4d12-8f26-7a3e9bf5811f)

**Comment by ci010** [comment]
虽然关掉这个了，但是下一个新的功能可能和这个类似
