### ISSUE TITLE
启动器下载整合包后无法立即识别

### ISSUE THREAD

**Issue by ApartTUSITU** [Voxelum/x-minecraft-launcher#549]
**再现：**

1.点击“个人中心”，点击“Modrinth”
2.随便搜一个整合包，下载它

**报告：**
[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/13800434/report.zip)

**环境**
 - OS: macOS
 - 版本 11.7.10

下载完Modrinth整合包后，不会出现加号，还是下载按钮，需要再次打开启动器，才能够正确识别并添加整合包。

**Comment by ApartTUSITU** [comment]
版本：0.39.3

**Comment by ci010** [comment]
我先看一看，现在我建议通过整合包商店页面来安装整合包
