### ISSUE TITLE
MacOS 上无法使用arm64版本

### ISSUE THREAD

**Issue by baka-world** [Voxelum/x-minecraft-launcher#563]
无dmg版本，下载压缩包提取app到applications，双击运行打开后无法获取数据库
[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/13926897/report.zip)

**Comment by ci010** [comment]
我没有arm64，去尝试https://github.com/Voxelum/x-minecraft-launcher/releases/tag/v0.39.16 吧，看看好没好

**Comment by ci010** [comment]
应该已经修了
