### ISSUE TITLE
why i dont see second layer 

### ISSUE THREAD

**Issue by Spacy80893** [Voxelum/x-minecraft-launcher#565]
I dont see second layer 
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/140869972/4a210d80-9f0a-49c7-a92e-111bc0d59f03)

And i cant change skin in launcher 
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/140869972/de8d23c7-397c-41e1-bea1-d514135fca32)

**Comment by ci010** [comment]
Fixed
