### ISSUE TITLE
Can not get response from version json url

### ISSUE THREAD

**Issue by Koishi-Satori** [Voxelum/x-minecraft-launcher#567]
### Perhaps a bug? Or I really need some help?

**Expected behavior**
* It seems like xmcl can not GET response from version Json URL. (i've waiting from about, 4 or 5mins? But it says the task has failed, the reason: Connection timeout to server. )
* And, the upgrade checking takes it a few minute as well
* Meanwhile, other applications relied on networks still work normally, such as my Packing Tools.

**Screenshots**
there is the console output.
![Screenshot_20240122_200713](https://github.com/Voxelum/x-minecraft-launcher/assets/88583686/8d2f6982-aa56-49bc-bd89-d03e36a722fa)
and there is the screenshot.
![Screenshot_20240122_201646](https://github.com/Voxelum/x-minecraft-launcher/assets/88583686/e1ee391e-7eae-4d80-923b-45003796de41)

**Environment**
 - OS: Debian GNU/Linux 12
 - Version: 0.39.16

**Additional context**
None

**Comment by ci010** [comment]
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/8425057/25eb85f9-f39a-446d-b722-1d01f969614e)
从log看获得json的过程都超时了……

很奇怪，你是不是开了代理什么之类的？

**Comment by Koishi-Satori** [comment]
没有代理（或者说就一个fastgithub？） 目前看是偶尔会发生 大部分情况下都正常
