### ISSUE TITLE
curseforge整合包没有mod

### ISSUE THREAD

**Issue by lwb-2021** [Voxelum/x-minecraft-launcher#568]
如题，curseforge整合包下载完之后发现没有mod
版本：v0.39.16 .deb
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/91705377/e1436c3c-1153-42d8-9aa5-7141cc58f139)

**Comment by ci010** [comment]
给我个整合包呗，是安装哪个整合包发生这个事情？

**Comment by lwb-2021** [comment]
整合包叫Levitated
还有一个现象，安装的时候预览列表里有所有模组，但是安装的时候没有装上去



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月25日 14:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Voxelum/x-minecraft-launcher] curseforge整合包没有mod (Issue #568) |

给我个整合包呗，是安装哪个整合包发生这个事情？

**Comment by ci010** [comment]
> 整合包叫Levitated 还有一个现象，安装的时候预览列表里有所有模组，但是安装的时候没有装上去
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年01月25日 14:45 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [Voxelum/x-minecraft-launcher] curseforge整合包没有mod (Issue #568) | 给我个整合包呗，是安装哪个整合包发生这个事情？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

不好意思再问个问题，你是通过 Curseforge 的窗口安装的么，还是整合包市场页面？我在整合包市场页面搜索出来安装的是好的

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/8425057/aad83ecc-0da4-4efb-b3bd-ea74de5bbbf2)

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/8425057/40862ec6-f791-47ce-9456-d2423985d3b0)

你要不试试这么安装？

**Comment by ci010** [comment]
0.39.17 应该修了
