### ISSUE TITLE
Nvidia gpu support for linux

### ISSUE THREAD

**Issue by AnAverageBeing** [Voxelum/x-minecraft-launcher#572]
xmcl-electron-app/main/pluginPowerMonitor.ts

This code only works for windows add support for gpu in linux system its pretty easy.
I have no experience with TypeScript so i cant add it myself if u can please add that.

**Comment by ci010** [comment]
I don't have Linux with GPU. Can you guide me how to assign GPU to executable in Linux?

**Comment by AnAverageBeing** [comment]
> I don't have Linux with GPU. Can you guide me how to assign GPU to executable in Linux?

just pass

__NV_PRIME_RENDER_OFFLOAD=1 
__GLX_VENDOR_LIBRARY_NAME=nvidia 

environment variables when running the executable it will automatically use nvidia GPU.

**Comment by ci010** [comment]
> > I don't have Linux with GPU. Can you guide me how to assign GPU to executable in Linux?
> 
> just pass
> 
> __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia
> 
> environment variables when running the executable it will automatically use nvidia GPU.

I did some research. Please correct me if I'm wrong.

[HMCL has similar logic](https://github.com/HMCL-dev/HMCL/blob/7f7068a55690bee069f5ed027e2f2a34b0a48569/HMCLCore/src/main/java/org/jackhuang/hmcl/launch/DefaultLauncher.java#L490
), but it assign the `mesa`.

From the [doc about linux graphic driver](https://github.com/LukeShortCloud/rootpages/blob/5757dd174fab0114b067842e542fbaa0cb6346ea/src/graphics/drivers.rst#mesa) I found, mesa is `a unified collection of open source graphics drivers for UNIX-like operating systems`. From my understanding, `=mesa` and `=nvidia` are two parallel options. Ideally, should I provide both of them according to the system hardware (or as user configurable)?

I also wonder if the `__GLX_VENDOR_LIBRARY_NAME` won't break the other situation. Like user has non-nvidia environment, setting `__GLX_VENDOR_LIBRARY_NAME` to `nvidia` will or will not break the program. If it only affect with the user has nv driver, and won't break other situation. I can add it immediately in next version.

**Comment by AnAverageBeing** [comment]
Ok so here is how it works nvidia publishes closed source propriety drivers so the mesa project started it reverse engineers nvidia drivers and they try to make it work but the main issue is the performance u get like not so good performance with mesa drivers (which are pre installed in most linux distros) Nvidia's drivers are fast. Most modern distros have easy way to install nvidia propriety drivers easily. So it depends weather a user is using nvidia drivers or mesa drivers 

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/84959276/3ad1b8c8-6ae4-4467-af70-dac7eae413af)

u can check drivers with a simple command 

But i think a simple solution would be just to provide the option for users in setting to do it by themself or u can check if nvidia propriety dirvers are installed by running nvidia-smi
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/84959276/09f0302d-bb91-4c8d-a611-7da240ec1026)


so if we receive some error like command not found or any error that means propriety drivers are not installed. but this adds complexity i think simple way would be to just give user option to enable that or just give user option to add custom env variables when running minecraft but if someone new to linux is using he might not get it so add a option to enable the gpu support for nvidia as a option and add a dropdown menu or something to let them select what drivers they are using.

(Also sorry for my bad writing skills i have no experience of writing comments or commit msgs i am just a student)

**Comment by AnAverageBeing** [comment]
`I also wonder if the __GLX_VENDOR_LIBRARY_NAME won't break the other situations. Like user has non-nvidia environment, setting __GLX_VENDOR_LIBRARY_NAME to nvidia will or will not break the program. If it only affect with the user has nv driver, and won't break other situations, I can add it immediately in next version.

`

i dont think so because amd drivers and intel drivers are open source and works out of the box as they are the part of kernel and dont require dynamic loading like nvidia drivers. Also you should just add a option to enable support for nvidia drivers in settings to nvidia users can enable it. 

And for reference you can see this launchers code (its written in java and works great)

https://llaun.ch/source

This is a link to download their source code.

**Comment by AnAverageBeing** [comment]
`https://github.com/bottlesdevs/Bottles/issues/849 I found the case that force setting env can break the program, but not sure if this is also valid for Minecraft. Maybe we should add an option to enable/disable this`


Sorry i have no experience my gpu supports Optimus and i run it in hybrid mode as it gives me freedom to choose what program should run on gpu. I guess providing user option is the best way doing things automatically will be complex. Because if we make automatic detection edge cases will arise because linux is not so unified like there are many ways to do a task someone might be having some specific configuration which might break when using these flags. I guess for now jsut providing a a option to pass env variables and giving option to enable nvidia gpu support with mesa and nvidia as option would be easiest thing to do and later if you want u can work on auto detection system

**Comment by lwb-2021** [comment]
或者考虑一下包装命令，装了BBSwitch可以用optirun，还可以optimus管理器+prime-run软件包

**Comment by xiao-k233** [comment]
哎，nv罪大恶极
