### ISSUE TITLE
Multiplayer works?

### ISSUE THREAD

**Issue by Qr-tz** [Voxelum/x-minecraft-launcher#573]
Can i play with people playing on TLauncher(don't like tl) or with players playing on official launcher?

**Comment by ci010** [comment]
For the common multiplayer (using dedicated server), of course, you can play with other launcher.

However, if you are talking about the "Multiplayer over LAN" feature in XMCL. It's different.
This feature is helping user who don't have dedicated server and want to play with friends not in same local network.
It is creating peer-to-peer connections between XMCL users. If you want to use that feature, your friends and you all need to use XMCL.
