### ISSUE TITLE
每次打开软件都会弹出账号登录页面

### ISSUE THREAD

**Issue by areuo** [Voxelum/x-minecraft-launcher#576]
1.但是又登录不了
2.在用户里面添加并切换到离线账号启动依然弹登录页面（离线账号添加第二个重启后第一个会消失）
3.在用户中添加了微软账户之后问题依旧
4.用户界面删除按钮为灰色删不掉其他账号
5.尝试删除user.json里面“x://00000111112222233333444445555566@microsoft”节点后会自动恢复

希望作者能够修复一下，真的太烦人了，每次启动都弹一个网页，跟牛皮癣广告一样！！！

**Comment by areuo** [comment]
![Snipaste_2024-02-04_14-39-41](https://github.com/Voxelum/x-minecraft-launcher/assets/158800910/3f8c961e-9359-4af0-8751-f9a24b4f15c7)
补个图

**Comment by ci010** [comment]
现在这个问题应该缓解了？不至于每次都弹吧

**Comment by areuo** [comment]
v0.40.1版本无法在线更新，我下载了离线包打开试了一下没有任何变化，甚至网页关太快还会打开第二个。。。🥲

**Comment by areuo** [comment]
![GIF](https://github.com/Voxelum/x-minecraft-launcher/assets/158800910/fa5b9695-72b6-4be2-b131-d262295ace85)
录了个GIF

**Comment by ci010** [comment]
> v0.40.1版本无法在线更新，我下载了离线包打开试了一下没有任何变化，甚至网页关太快还会打开第二个。。。🥲

新版本和之前的存储验证信息的地方变了，所以都需要重新刷新一下token

**Comment by areuo** [comment]
你只要去掉这个默认账号登录验证就好了：x://00000111112222233333444445555566@microsoft
让用户自己登录正版账号，而不是直接弹登录网页
我现在的情况是自己登录账号是没问题的，你弹出来的页面登录就是显示多次密码错误登录被锁定，永远都过不去这一步了
另外你也没考虑过假如有人没有正版账号岂不是也永远都会弹这个页面吗，这个逻辑太不合理了

**Comment by ci010** [comment]
> 你只要去掉这个默认账号登录验证就好了：x://00000111112222233333444445555566@microsoft 让用户自己登录正版账号，而不是直接弹登录网页 我现在的情况是自己登录账号是没问题的，你弹出来的页面登录就是显示多次密码错误登录被锁定，永远都过不去这一步了 另外你也没考虑过假如有人没有正版账号岂不是也永远都会弹这个页面吗，这个逻辑太不合理了

我还以为00000111112222233333444445555566这个真的是你的账号……这条记录是哪里来的呢？详细我们可以加qq或者discord聊

**Comment by areuo** [comment]
> > 你只要去掉这个默认账号登录验证就好了：x://00000111112222233333444445555566@microsoft 让用户自己登录正版账号，而不是直接弹登录网页 我现在的情况是自己登录账号是没问题的，你弹出来的页面登录就是显示多次密码错误登录被锁定，永远都过不去这一步了 另外你也没考虑过假如有人没有正版账号岂不是也永远都会弹这个页面吗，这个逻辑太不合理了
> 
> 我还以为00000111112222233333444445555566这个真的是你的账号……这条记录是哪里来的呢？
> 
> 这个看上去像是一条失败的记录，如果可以的话你可以贴一下 user.json 这条记录的内容
> 
> 详细我们可以加qq或者discord聊
> 
> 我猜测你这条应该是一个空的微软账户，也就是说username是空的。
> 
> 希望我这一条commit能修掉你这个问题 [c09ecfe](https://github.com/Voxelum/x-minecraft-launcher/commit/c09ecfe83a58f6212438eb3d84b4cff562e4fb12)

其实我上面的回复就说的非常清楚了，第一张图片最下面账号过期时间标红的就是问题账号，只不过用户名我打了码
而且我后面也补充了无法正常登录的原因
所以你这个新的改动明显是无法修复问题的，因为你判断的是用户名，除非改成判断”**过期时间**“之类的
。。。
另外你要想复现我这个问题，直接把user.json删掉，然后在启动时弹出登录页面不要输入密码登录不就可以了吗😄

**Comment by ci010** [comment]
> > > 你只要去掉这个默认账号登录验证就好了：x://00000111112222233333444445555566@microsoft 让用户自己登录正版账号，而不是直接弹登录网页 我现在的情况是自己登录账号是没问题的，你弹出来的页面登录就是显示多次密码错误登录被锁定，永远都过不去这一步了 另外你也没考虑过假如有人没有正版账号岂不是也永远都会弹这个页面吗，这个逻辑太不合理了
> > 
> > 
> > 我还以为00000111112222233333444445555566这个真的是你的账号……这条记录是哪里来的呢？
> > 这个看上去像是一条失败的记录，如果可以的话你可以贴一下 user.json 这条记录的内容
> > 详细我们可以加qq或者discord聊
> > 我猜测你这条应该是一个空的微软账户，也就是说username是空的。
> > 希望我这一条commit能修掉你这个问题 [c09ecfe](https://github.com/Voxelum/x-minecraft-launcher/commit/c09ecfe83a58f6212438eb3d84b4cff562e4fb12)
> 
> 其实我上面的回复就说的非常清楚了，第一张图片最下面账号过期时间标红的就是问题账号，只不过用户名我打了码 而且我后面也补充了无法正常登录的原因 所以你这个新的改动明显是无法修复问题的，因为你判断的是用户名，除非改成判断”**过期时间**“之类的 。。。 另外你要想复现我这个问题，直接把user.json删掉，然后在启动时弹出登录页面不要输入密码登录不就可以了吗😄

1. 新版已经不能不输入用户名登录了，修改后也不会出现空的profile
2. 问题是任何authority不输入账户密码没法被记录进 user.json 啊，就算是微软登录，登陆不了是不会记录的
3. 删除键为啥灰的我也不知道，起码我这里删了又加，加了又删也没出现这种情况
4. 删除会自动恢复也是很神奇，我又改了一版让它这个刷新不会弹窗口，只有选中的才有可能弹

**Comment by areuo** [comment]
#741
好好好，启动不弹窗了👍（点一下头像还是会弹并创建一个）
删除按钮能点了，然后我删除掉所有账号再添加账号发现只有<Microsoft/Mojang>两个选项没有offline/LittleSkin等账号选项（空账号的产生会不会跟这里有关呢？）

另外一个关于添加离线账号的
添加第一个："x://OFFLINE@dev" 节点内
添加第二个："OFFLINE"节点内
添加第三个："OFFLINE"节点内
...
重启软件，第一个账号名会消失，第二和之后的被挪到了"x://OFFLINE@dev“节点下，再次添加会如上循环，不知道这个是设定如此还是什么🥲

**Comment by ci010** [comment]
不应该会消失啊，但是他们确实都会加一起，作为不同的角色

**Comment by sunnyyangyangyang** [comment]
仍然每次启动弹出一次登录网页哪怕app显示已经登录，太烦人了
