### ISSUE TITLE
勾选使用设备码登录微软账户后不显示设备码

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [Voxelum/x-minecraft-launcher#577]
**To Reproduce**

登录微软账户，勾选使用设备码登录

**Expected behavior**
出现设备码且可以复制

**Screenshots**
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/42903464/297bd02c-2971-4112-acdf-e93ba8f4bd7c)

**Environment**
 - OS: [Windows 11]
 - Version [0.39.17]

**Comment by lwb-2021** [comment]
Linux 版本似乎也有这个问题（可能是登录api更新或者啥的）
版本最新0.39.17

**Comment by ci010** [comment]
See #580
