### ISSUE TITLE
建议加入包装命令选项

### ISSUE THREAD

**Issue by lwb-2021** [Voxelum/x-minecraft-launcher#578]
像HMCL一样
比如说我在包装命令的选项里输入prime-run（在archlinux下配置特定的软件包后可以用这玩意独显启动游戏）
那么启动命令会被替换成 prime-run java （后面跟原有的其他参数）

**Comment by ci010** [comment]
7b4b7439b282611a72db34074df52e83dca28193 加了，可以试试
