### ISSUE TITLE
The installed icon is not displayed

### ISSUE THREAD

**Issue by PrometheuzzZ** [Voxelum/x-minecraft-launcher#579]
![img-2024-02-08-12-37-56](https://github.com/Voxelum/x-minecraft-launcher/assets/21082056/76008fba-7ac7-4553-bcdf-6bf4e344ec99)

The installed icon is not displayed

**Comment by jiaowobaba02** [comment]
I understand you might be anxious right now, but could you please share how you triggered the issue and its frequency? This would help the developers to debug more conveniently. Although I'm not the developer of the application.

**Comment by ci010** [comment]
This is a bug. I will fix in next version

**Comment by ci010** [comment]
Resolved
