### ISSUE TITLE
<title>spamming crashes and logs on my linux chromebook acer chromebook 315 really stupid version SMP PREEMPT_DYNAMIC and my email is cameronkabatoff@gmail.com and my account name is cameron kabatoff and i used ely.by to connect with x minecraft launcher and am running a modpack called Boosted FPS Forge 1.19.2-1.0.2 and email me by my email cameronkabatoff@gmail.com

### ISSUE THREAD

**Issue by Cameron300** [Voxelum/x-minecraft-launcher#587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.34.1-

### Operating System

Linux

### Architecture

x64

### Current Behavior

this is really annoying and please fix this including when i download a lot of mods like 50 performance mods and a lot of content mods like farmers delight pams harvestcraft 2 food extensted and a lot of mods with two versions 1.18.2/1.19.2 please help me fix this cause its really annoying and spamming my launcher with those crash logs on my acer chromebook 315 
i downloaded the x minecraft launcher from here https://www.9minecraft.net/x-minecraft-launcher/  and i download the deb file

### Expected Behavior

this is really annoying and please fix this including when i download a lot of mods like 50 performance mods and a lot of content mods like farmers delight pams harvestcraft 2 food extensted and a lot of mods with two versions 1.18.2/1.19.2 please help me fix this cause its really annoying and spamming my launcher with those crash logs on my acer chromebook 315 

### Steps To Reproduce

fix this

### Anything else?

please fix this

**Comment by ci010** [comment]
I want to clerify your situation. Are you opening the issue for the **MINECRAFT** crashes, not the **LAUNCHER** crashes right?

The issue is not for Minecraft crashes. For game crash you should change your mods set.

Or did I misunderstand you? I'm still confused about term "spamming crashes and logs". What crashes and what logs are we talking about?

**Comment by Cameron300** [comment]
> I want to clerify your situation. Are you opening the issue for the **MINECRAFT** crashes, not the **LAUNCHER** crashes right?
> 
> The issue is not for Minecraft crashes. For game crash you should change your mods set.
> 
> Or did I misunderstand you? I'm still confused about term "spamming crashes and logs". What crashes and what logs are we talking about?
correct

**Comment by Cameron300** [comment]
> correct and the logs we are talking about is mod logs and modpack crashes and one datapack

**Comment by Cameron300** [comment]
> > correct and the logs we are talking about is mod logs and modpack crashes and one datapack called WASD Moar Swords [Datapack] 1.20.4 and i need to stop the world from not loading with 24 mods or 150 mods i need that fix in this minecraft

**Comment by Cameron300** [comment]
and i need to run 400 mods that show two versions in the launcher minecraft 1.18.2/1.19.2 and forge please i need to download a lot of mods for my launcher and my minecraft so fix this today or tommorrow
