### ISSUE TITLE
Java Crashing With Specific Mods Enabled

### ISSUE THREAD

**Issue by ShadowAndNitrix** [Voxelum/x-minecraft-launcher#602]
Check Newest Comment For Info!

**Comment by ShadowAndNitrix** [comment]
Well For Me It Don't Work. I Keep Getting The Java Error.

**Comment by ShadowAndNitrix** [comment]
Ok I Have Reopened This For A Reason! My Launcher Has Crashed A Few Times From Certian Mods For Some Reason

**Comment by ci010** [comment]
> Ok I Have Reopened This For A Reason! My Launcher Has Crashed A Few Times From Certian Mods For Some Reason

Then please tell me what are the mods

**Comment by ShadowAndNitrix** [comment]
FNAF Universe, CFM, CGM, Fisk Super Hero's And Transformers. These Have Crashed It A Few Times
