### ISSUE TITLE
After this update v0.42.3 in the fabric instance forge mod installing automatically when i install fabric mod

### ISSUE THREAD

**Issue by aislxflames** [Voxelum/x-minecraft-launcher#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

v0.42.3

### Operating System

Windows

### Architecture

x64

### Current Behavior

the fabric instance forge mod installing automatically when i install fabric mod

### Expected Behavior

It should only install fabric mod in fabric instance

**Comment by Peperehobbits01** [comment]
Do you still have the issues?
