### ISSUE TITLE
微软账号登陆提示 Fetch Failed

### ISSUE THREAD

**Issue by CDmking** [Voxelum/x-minecraft-launcher#608]
### 是否已经有人报告过这个问题？

- [X] 我已经搜索过现有的问题

### 启动器版本

0.43.0

### 操作系统

Linux

### 架构

x64

### 其他信息？

[2024-04-05T06!45!51.982Z.zip](https://github.com/Voxelum/x-minecraft-launcher/files/14881085/2024-04-05T06.45.51.982Z.zip)
![截图_2024-04-05_14-45-45](https://github.com/Voxelum/x-minecraft-launcher/assets/95959972/84267976-8b17-4e74-905b-fa1db2005f61)

**Comment by ci010** [comment]
Fixed in #609
