### ISSUE TITLE
Forge1.16.5安装依赖运行库-404未找到资源

### ISSUE THREAD

**Issue by aether1010** [Voxelum/x-minecraft-launcher#612]
### 是否已经有人报告过这个问题？

- [X] 我已经搜索过现有的问题

### 启动器版本

v0.43.1

### 操作系统

Mac

### 架构

x64

### 当前行为

在安装Minecraft1.16.5-forge-36.2.42时候，总是有一个路径为/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar 的文件无法下载，导致依赖库文件损坏，原因是404未找到资源。

安装依赖运行库
2024/4/7 00:51:30
🔗 https://bmclapi2.bangbang93.com/maven/org/apache/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
404 未找到资源
🔗 https://bmclapi2.bangbang93.com/maven/org/apache/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
📌 文件校验失败！期望哈希值是 f8ff8032903882376e8d000c51e3e16d20fc7df7，实际获取到的是 da39a3ee5e6b4b0d3255bfef95601890afd80709。
🔗 https://maven.minecraftforge.net/org/apache/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
404 未找到资源
🔗 https://maven.minecraftforge.net/org/apache/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
📌 文件校验失败！期望哈希值是 f8ff8032903882376e8d000c51e3e16d20fc7df7，实际获取到的是 da39a3ee5e6b4b0d3255bfef95601890afd80709。
TypeError
🔗 http://files.minecraftforge.net/maven/org/apache/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
📌 文件校验失败！期望哈希值是 f8ff8032903882376e8d000c51e3e16d20fc7df7，实际获取到的是 da39a3ee5e6b4b0d3255bfef95601890afd80709。

MacBook Pro 15-inch, 2018
Sonoma 版本14.3

Minecraft: 1.16.5
Forge: 36.2.42
Java: Java 17.0.2

### 期望行为

在点击"安装"后，下载修复损坏文件

### 复现步骤

1. 点击创建游戏，从服务器创建，Minecraft选择1.16.5，Forge选择36.2.42
2. 点击安装
3. 出现问题，在任务管理器（启动器）里发现了：

安装依赖运行库
2024/4/7 00:51:30
🔗 https://bmclapi2.bangbang93.com/maven/org/apache/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
404 未找到资源
🔗 https://bmclapi2.bangbang93.com/maven/org/apache/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
📌 文件校验失败！期望哈希值是 f8ff8032903882376e8d000c51e3e16d20fc7df7，实际获取到的是 da39a3ee5e6b4b0d3255bfef95601890afd80709。
🔗 https://maven.minecraftforge.net/org/apache/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
404 未找到资源
🔗 https://maven.minecraftforge.net/org/apache/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
📌 文件校验失败！期望哈希值是 f8ff8032903882376e8d000c51e3e16d20fc7df7，实际获取到的是 da39a3ee5e6b4b0d3255bfef95601890afd80709。
TypeError
🔗 http://files.minecraftforge.net/maven/org/apache/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
📌 文件校验失败！期望哈希值是 f8ff8032903882376e8d000c51e3e16d20fc7df7，实际获取到的是 da39a3ee5e6b4b0d3255bfef95601890afd80709。

**Comment by ci010** [comment]
见鬼，我康康

**Comment by ci010** [comment]
在 0.43.2 里修复了
