### ISSUE TITLE
Modpack never install

### ISSUE THREAD

**Issue by Al3xUI** [Voxelum/x-minecraft-launcher#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

v0.43.3

### Operating System

Windows

### Architecture

x64

### Current Behavior

When we try to download a modpack from the launcher's market, the download animation appears, but nothing downloads.

**Comment by SloppyPuppy** [comment]
Same issue here.
Have you tried other modpacks? Which modpack is in question? Is it perhaps always curseforge ones? I constantly get 404 errors and checksum mismatch errors. Even for alternate modpack providers they download certain assets from forgecdn.net
This is the Task Manager tab output from one of the modpacks, curse forged modpacks won't even start downloading.

`🔗 https://edge.forgecdn.net/files/5033/949/Burnt_Forest_1.5_1.18.2.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/5033/949/Burnt_Forest_1.5_1.18.2.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/5033/949/Burnt_Forest_1.5_1.18.2.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/5033/949/Burnt_Forest_1.5_1.18.2.jar
📌 Checksum not matched! Expect 87f09d089d24eaabbb371673cdc6709da7d5f7d8. Actual da39a3ee5e6b4b0d3255bfef95601890afd80709.
🔗 https://edge.forgecdn.net/files/3840/125/Quark-3.2-358.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/3840/125/Quark-3.2-358.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/3840/125/Quark-3.2-358.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/3840/125/Quark-3.2-358.jar
📌 Checksum not matched! Expect 18919f757e7fd1b4d4b4e0e0de1ea978ead34179. Actual da39a3ee5e6b4b0d3255bfef95601890afd80709.
🔗 https://edge.forgecdn.net/files/3745/494/observable-2.2.3-forge.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/3745/494/observable-2.2.3-forge.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/3745/494/observable-2.2.3-forge.jar
📌 Checksum not matched! Expect 78fcd467158ac2d1dffe6e31abda24ad5664f723. Actual da39a3ee5e6b4b0d3255bfef95601890afd80709.
🔗 https://edge.forgecdn.net/files/3953/207/BloodMagic-1.18.2-3.2.6-41.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/3953/207/BloodMagic-1.18.2-3.2.6-41.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/3953/207/BloodMagic-1.18.2-3.2.6-41.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/3953/207/BloodMagic-1.18.2-3.2.6-41.jar
📌 Checksum not matched! Expect 6e28f417a004e43061a20218bcb8e573f5c5d0d7. Actual da39a3ee5e6b4b0d3255bfef95601890afd80709.
🔗 https://edge.forgecdn.net/files/4548/315/supplementaries-1.18.2-1.5.18.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4548/315/supplementaries-1.18.2-1.5.18.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4548/315/supplementaries-1.18.2-1.5.18.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4548/315/supplementaries-1.18.2-1.5.18.jar
📌 Checksum not matched! Expect 77c92894d7482b71bd6489ba43355b6558a024d6. Actual da39a3ee5e6b4b0d3255bfef95601890afd80709.
🔗 https://edge.forgecdn.net/files/4293/291/chipped-forge-1.18.2-2.0.1.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4293/291/chipped-forge-1.18.2-2.0.1.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4293/291/chipped-forge-1.18.2-2.0.1.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4293/291/chipped-forge-1.18.2-2.0.1.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4293/291/chipped-forge-1.18.2-2.0.1.jar
📌 Checksum not matched! Expect 9ee8bc9cf7a95a48447b4f116ed71232610b2d0b. Actual da39a3ee5e6b4b0d3255bfef95601890afd80709.
🔗 https://edge.forgecdn.net/files/4142/172/mowziesmobs-1.5.32.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4142/172/mowziesmobs-1.5.32.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4142/172/mowziesmobs-1.5.32.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4142/172/mowziesmobs-1.5.32.jar
📌 Checksum not matched! Expect d146651162f008ea8d8d6a3a81f742fe1917f23f. Actual da39a3ee5e6b4b0d3255bfef95601890afd80709.
🔗 https://edge.forgecdn.net/files/3936/568/Botania-1.18.2-435.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/3936/568/Botania-1.18.2-435.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/3936/568/Botania-1.18.2-435.jar
📌 Checksum not matched! Expect f85a3757cc6d58896856ce42cd6f8165e576dc5b. Actual da39a3ee5e6b4b0d3255bfef95601890afd80709.
🔗 https://edge.forgecdn.net/files/4631/612/malum-1.18.2-1.5.0.1.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4631/612/malum-1.18.2-1.5.0.1.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4631/612/malum-1.18.2-1.5.0.1.jar
📌 Checksum not matched! Expect 9908f5e7ee7ebe628e604f3e3ab0ca76fc680853. Actual da39a3ee5e6b4b0d3255bfef95601890afd80709.
🔗 https://edge.forgecdn.net/files/4614/465/iceandfire-2.1.12-1.18.2.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4614/465/iceandfire-2.1.12-1.18.2.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4614/465/iceandfire-2.1.12-1.18.2.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4614/465/iceandfire-2.1.12-1.18.2.jar
404 Not Found
🔗 https://edge.forgecdn.net/files/4614/465/iceandfire-2.1.12-1.18.2.jar
📌 Checksum not matched! Expect 67ff486e0dcce19afa49f373d7502181035bac65. Actual da39a3ee5e6b4b0d3255bfef95601890afd80709.`
