### ISSUE TITLE
Restart button after a update as been donwload dosen't do anything

### ISSUE THREAD

**Issue by Peperehobbits01** [Voxelum/x-minecraft-launcher#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.1

### Operating System

Linux

### Architecture

x64

### Current Behavior

The restart button after a update is donwloaded dosen't work.

### Expected Behavior

The launcher restart and apply the update.

### Steps To Reproduce

1. Whit linux amd64.deb version. You go in the settings to update the app.
2. You click the button to update
3. You click the donwload and install button
4. You click the restart button after that, but it dosen't work.

**Comment by ci010** [comment]
I hope [this commit](https://github.com/voxelum/x-minecraft-launcher/blob/afa2079fe9430e7a5a59eb8d9bd52833619b91ca/xmcl-electron-app/main/utils/updater.ts) can help

**Comment by xiao-k233** [comment]
So,can you paste your full env?like kernel version and distribution

**Comment by Peperehobbit01** [comment]
I sure can, and to be fair, the button still dosen't work. So yeah. 
System:    Kernel: 5.4.0-177-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 
           Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una 
           base: Ubuntu 20.04 focal 
Machine:   Type: Desktop System: Alienware product: Alienware X51 v: 00 serial: <filter> Chassis: 
           type: 3 v: 00 serial: <filter> 
           Mobo: Alienware model: 0KM92T v: A00 serial: <filter> UEFI: Alienware v: A07 
           date: 07/26/2012 
CPU:       Topology: Quad Core model: Intel Core i7-3770 bits: 64 type: MT MCP arch: Ivy Bridge 
           rev: 9 L2 cache: 8192 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 54275 
           Speed: 3802 MHz min/max: 1600/3900 MHz Core speeds (MHz): 1: 3792 2: 3742 3: 3754 
           4: 3773 5: 3775 6: 3809 7: 3800 8: 3780 
Graphics:  Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics vendor: Dell 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0162 
           Device-2: NVIDIA GM107 [GeForce GTX 745] vendor: PC Partner Limited / Sapphire 
           driver: nvidia v: 535.171.04 bus ID: 01:00.0 chip ID: 10de:1382 
           Display: x11 server: X.Org 1.20.13 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: NVIDIA GeForce GTX 745/PCIe/SSE2 v: 4.6.0 NVIDIA 535.171.04 
           direct render: Yes 
Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio vendor: Dell 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:1c20 
           Device-2: NVIDIA GM107 High Definition Audio [GeForce 940MX] 
           vendor: PC Partner Limited / Sapphire driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           chip ID: 10de:0fbc 
           Sound Server: ALSA v: k5.4.0-177-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Dell 
           driver: r8169 v: kernel port: d000 bus ID: 02:00.0 chip ID: 10ec:8168 
           IF: enp2s0 state: up speed: 100 Mbps duplex: full mac: <filter> 
           Device-2: Qualcomm Atheros AR9485 Wireless Network Adapter vendor: Dell driver: ath9k 
           v: kernel port: d000 bus ID: 04:00.0 chip ID: 168c:0032 
           IF: wlp4s0 state: down mac: <filter> 
Drives:    Local Storage: total: 1.82 TiB used: 739.39 GiB (39.7%) 
           ID-1: /dev/sda vendor: Seagate model: ST2000DM008-2FR102 size: 1.82 TiB speed: 3.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 1.43 TiB used: 739.39 GiB (50.4%) fs: ext4 dev: /dev/sda4 
           ID-2: swap-1 size: 29.80 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda1 
Sensors:   System Temperatures: cpu: 66.0 C mobo: N/A gpu: nvidia temp: 49 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 36% 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/PreMiD_Linux.list 
           1: deb [signed-by=/etc/apt/keyrings/PreMiD_Linux-archive-keyring.gpg] https: //packagecloud.io/PreMiD/Linux/ubuntu/ hirsute main
           2: deb-src [signed-by=/etc/apt/keyrings/PreMiD_Linux-archive-keyring.gpg] https: //packagecloud.io/PreMiD/Linux/ubuntu/ hirsute main
           Active apt repos in: /etc/apt/sources.list.d/nodesource.list 
           1: deb [arch=amd64 signed-by=/usr/share/keyrings/nodesource.gpg] https: //deb.nodesource.com/node_20.x nodistro main
           Active apt repos in: /etc/apt/sources.list.d/obsproject-obs-studio-focal.list 
           1: deb http: //ppa.launchpad.net/obsproject/obs-studio/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //linux-mint.froonix.org una main upstream import backport
           2: deb http: //ftp.belnet.be/ubuntu focal main restricted universe multiverse
           3: deb http: //ftp.belnet.be/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //ftp.belnet.be/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/vscode.list 
           1: deb [arch=amd64,arm64,armhf] https: //packages.microsoft.com/repos/code stable main
           Active apt repos in: /etc/apt/sources.list.d/winehq-focal.sources 
           1: deb [arch=amd64 i386] https: //dl.winehq.org/wine-builds/ubuntu focal main
Info:      Processes: 282 Uptime: 18m Memory: 7.65 GiB used: 2.55 GiB (33.4%) Init: systemd v: 245 
           runlevel: 5 Compilers: gcc: 9.4.0 alt: 9 Client: Unknown python3.8 client inxi: 3.0.38 

I imagine this is what you where watting (sorry if my english is bad xD).

**Comment by xiao-k233** [comment]
要不我们中文聊吧XD
这还是得看apt方面的log，你查一下看看有没有什么异常，如果没有的话应该是就是xmcl在执行install相关命令时有问题
我arch没法帮你复现



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 27, 2024 16:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Voxelum/x-minecraft-launcher] Restart button after a update asbeen donwload dosen't do anything (Issue #619)




 
I sure can, and to be fair, the button still dosen't work. So yeah.
 System:    Kernel: 5.4.0-177-generic x86_64 bits: 64 compiler: gcc v: 9.4.0
 Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una
 base: Ubuntu 20.04 focal
 Machine:   Type: Desktop System: Alienware product: Alienware X51 v: 00 serial:  Chassis:
 type: 3 v: 00 serial: 
 Mobo: Alienware model: 0KM92T v: A00 serial:  UEFI: Alienware v: A07
 date: 07/26/2012
 CPU:       Topology: Quad Core model: Intel Core i7-3770 bits: 64 type: MT MCP arch: Ivy Bridge
 rev: 9 L2 cache: 8192 KiB
 flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 54275
 Speed: 3802 MHz min/max: 1600/3900 MHz Core speeds (MHz): 1: 3792 2: 3742 3: 3754
 4: 3773 5: 3775 6: 3809 7: 3800 8: 3780
 Graphics:  Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics vendor: Dell
 driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0162
 Device-2: NVIDIA GM107 [GeForce GTX 745] vendor: PC Partner Limited / Sapphire
 driver: nvidia v: 535.171.04 bus ID: 01:00.0 chip ID: 10de:1382
 Display: x11 server: X.Org 1.20.13 driver: modesetting,nvidia
 unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz
 OpenGL: renderer: NVIDIA GeForce GTX 745/PCIe/SSE2 v: 4.6.0 NVIDIA 535.171.04
 direct render: Yes
 Audio:     Device-1: Intel 6 Series/C200 Series Family High Definition Audio vendor: Dell
 driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:1c20
 Device-2: NVIDIA GM107 High Definition Audio [GeForce 940MX]
 vendor: PC Partner Limited / Sapphire driver: snd_hda_intel v: kernel bus ID: 01:00.1
 chip ID: 10de:0fbc
 Sound Server: ALSA v: k5.4.0-177-generic
 Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Dell
 driver: r8169 v: kernel port: d000 bus ID: 02:00.0 chip ID: 10ec:8168
 IF: enp2s0 state: up speed: 100 Mbps duplex: full mac: 
 Device-2: Qualcomm Atheros AR9485 Wireless Network Adapter vendor: Dell driver: ath9k
 v: kernel port: d000 bus ID: 04:00.0 chip ID: 168c:0032
 IF: wlp4s0 state: down mac: 
 Drives:    Local Storage: total: 1.82 TiB used: 739.39 GiB (39.7%)
 ID-1: /dev/sda vendor: Seagate model: ST2000DM008-2FR102 size: 1.82 TiB speed: 3.0 Gb/s
 serial: 
 Partition: ID-1: / size: 1.43 TiB used: 739.39 GiB (50.4%) fs: ext4 dev: /dev/sda4
 ID-2: swap-1 size: 29.80 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sda1
 Sensors:   System Temperatures: cpu: 66.0 C mobo: N/A gpu: nvidia temp: 49 C
 Fan Speeds (RPM): N/A gpu: nvidia fan: 36%
 Repos:     No active apt repos in: /etc/apt/sources.list
 Active apt repos in: /etc/apt/sources.list.d/PreMiD_Linux.list
 1: deb [signed-by=/etc/apt/keyrings/PreMiD_Linux-archive-keyring.gpg] https: //packagecloud.io/PreMiD/Linux/ubuntu/ hirsute main
 2: deb-src [signed-by=/etc/apt/keyrings/PreMiD_Linux-archive-keyring.gpg] https: //packagecloud.io/PreMiD/Linux/ubuntu/ hirsute main
 Active apt repos in: /etc/apt/sources.list.d/nodesource.list
 1: deb [arch=amd64 signed-by=/usr/share/keyrings/nodesource.gpg] https: //deb.nodesource.com/node_20.x nodistro main
 Active apt repos in: /etc/apt/sources.list.d/obsproject-obs-studio-focal.list
 1: deb http: //ppa.launchpad.net/obsproject/obs-studio/ubuntu focal main
 Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
 1: deb http: //linux-mint.froonix.org una main upstream import backport
 2: deb http: //ftp.belnet.be/ubuntu focal main restricted universe multiverse
 3: deb http: //ftp.belnet.be/ubuntu focal-updates main restricted universe multiverse
 4: deb http: //ftp.belnet.be/ubuntu focal-backports main restricted universe multiverse
 5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
 6: deb http: //archive.canonical.com/ubuntu/ focal partner
 Active apt repos in: /etc/apt/sources.list.d/vscode.list
 1: deb [arch=amd64,arm64,armhf] https: //packages.microsoft.com/repos/code stable main
 Active apt repos in: /etc/apt/sources.list.d/winehq-focal.sources
 1: deb [arch=amd64 i386] https: //dl.winehq.org/wine-builds/ubuntu focal main
 Info:      Processes: 282 Uptime: 18m Memory: 7.65 GiB used: 2.55 GiB (33.4%) Init: systemd v: 245
 runlevel: 5 Compilers: gcc: 9.4.0 alt: 9 Client: Unknown python3.8 client inxi: 3.0.38
 
I imagine this is what you where watting (sorry if my english is bad xD).

**Comment by ci010** [comment]
I just want to confirm that you are using deb to install the launcher right?

**Comment by Peperehobbits01** [comment]
> I just want to confirm that you are using deb to install the launcher right?

Yes, that's what I use.
