### ISSUE TITLE
Modpack Market not showing Anything

### ISSUE THREAD

**Issue by LostEtienne** [Voxelum/x-minecraft-launcher#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.3

### Operating System

Windows

### Architecture

x64

### Current Behavior

![Screenshot 2024-05-09 124702](https://github.com/Voxelum/x-minecraft-launcher/assets/120445159/31d1bd8a-bbf7-4f80-b550-b26247a5105b)

### Expected Behavior

Working and Showing Modpacks to download from

### Steps To Reproduce

Just Happend out of Nowhere after a Clean install

### Anything else?

[report.zip](https://github.com/Voxelum/x-minecraft-launcher/files/15261249/report.zip)

Tried to reinstall it, Change settings. Looked up the Firewall settings. Everything seems working Fine. Besides that

**Comment by ci010** [comment]
Try 0.44.4. I think this should be fixed in the latest version.

**Comment by LostEtienne** [comment]
Works like a Charm. Thanks for the Quick Help
