### ISSUE TITLE
linux 只能手动更新

### ISSUE THREAD

**Issue by LQ636721** [Voxelum/x-minecraft-launcher#633]
系统是 Ubuntu 18.04 LTS，下载的是 deb 版本。

点击了设置里的更新，然而下载完成后没有反应。

手动点击重启并安装后仍然没有反映。

进入命令行手动更新是正常的。

感觉不是很舒服……

**Comment by CDmking** [comment]
然而，这在 Linux 中不是很正常吗？

**Comment by LemonFan-maker** [comment]
如果是deb安装，可以考虑自建apt镜像(挂到github上，使用github action每日从github release拉取最新版本)使用apt进行更新。
