### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by Lio-gif** [Voxelum/x-minecraft-launcher#634]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Launcher Version

Newest

### Operating System

Windows

### Architecture

x64

### Current Behavior

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/149175168/3f7857c1-3049-4f62-9cd8-2c26afe0934a)

### Expected Behavior

Launch mc

### Steps To Reproduce

?

### Anything else?

I tried evrything and also selected all java versions on my pc

**Comment by ShadowAndNitrix** [comment]
I Have Gotten This Error Before, What Version Of Minecraft Are You Trying To Install?

**Comment by Lio-gif** [comment]
> I Have Gotten This Error Before, What Version Of Minecraft Are You Trying To Install? Because Sometimes Certain Versions Of MC Will Cause This

i use 1.20.4 fabric 0.15.11

**Comment by ShadowAndNitrix** [comment]
Ok So From My Understanding Of The Launcher Anything Above 1.16.5 Will Not Work For Some Odd Reason Idk If Its Me Tho, But Try 1.16.5 And See If That Works If Not I Can Still try And Help

**Comment by Lio-gif** [comment]
> Ok So From My Understanding Of The Launcher Anything Above 1.16.5 Will Not Work For Some Odd Reason Idk If Its Me Tho, But Try 1.16.5 And See If That Works If Not I Can Still try And Help. (Side Note: Download Java From The Link To See If That Also helps: https://www.java.com/download/ie_manual.jsp)

1.16.5 work thanks but weird that the rest doesnt works

**Comment by ShadowAndNitrix** [comment]
> > Ok So From My Understanding Of The Launcher Anything Above 1.16.5 Will Not Work For Some Odd Reason Idk If Its Me Tho, But Try 1.16.5 And See If That Works If Not I Can Still try And Help. (Side Note: Download Java From The Link To See If That Also helps: https://www.java.com/download/ie_manual.jsp)
> 
> 1.16.5 work thanks but weird that the rest doesnt works

Yw, But I Don't Know Why Anything Above 1.16.5 Won't Work Properly So Just Use Version's 1.16.5 and below otherwise it won't work unfortunately. I'm Always Available If Needed

**Comment by raeedawer** [comment]
Hello, 
If you want to run higher versions I can help

**Comment by Denyscrasav4ik** [comment]
i think higher minecraft version require higher version of java so maybe try updating your [java](https://javadl.oracle.com/webapps/download/AutoDL?BundleId=249833_43d62d619be4e416215729597d70b8ac) and [java development kit](https://download.oracle.com/java/22/latest/jdk-22_windows-x64_bin.exe) this might help

**Comment by ShadowAndNitrix** [comment]
> Hello, If you want to run higher versions I can help

Well Thanks For Offering Help As I Could Use It Because I Can't Get 1.20 To Work

**Comment by Peperehobbits01** [comment]
Now that's weird, seems like a Windows related issues.... tho.

**Comment by ShadowAndNitrix** [comment]
> Now that's weird, seems like a Windows related issues.... tho.

Prob Is Lmao. Ima Stick With What I Have For Now

**Comment by Peperehobbits01** [comment]
> > Now that's weird, seems like a Windows related issues.... tho.
> 
> Prob Is Lmao. Ima Stick With What I Have For Now

I mean as long, as you like what you are using, personaly I think it dosen't matter what you choosed to use. Anyway if you are using Windows to, then it's defenetly Windows related as I use Linux and I never saw that issues.

**Comment by ShadowAndNitrix** [comment]
> > > Now that's weird, seems like a Windows related issues.... tho.
> > 
> > 
> > Prob Is Lmao. Ima Stick With What I Have For Now
> 
> I mean as long, as you like what you are using, personaly I think it dosen't matter what you choosed to use. Anyway if you are using Windows to, then it's defenetly Windows related as I use Linux and I never saw that issues.

Yeah Its A Windows Issue Cuz I Can't Figure This Out Lol
