### ISSUE TITLE
加载界面有错别字，“启动的很慢”应为“启动得很慢”

### ISSUE THREAD

**Issue by Rhino-Nine** [Voxelum/x-minecraft-launcher#636]
![PixPin_2024-05-16_14-57-36](https://github.com/Voxelum/x-minecraft-launcher/assets/110172475/a333e8a8-eff9-4c07-8a1f-5237604656aa)

根据《现代汉语词典》的解释：

1. **“的”** 的基本释义包括：

- 用在定语后，表示领属、修饰等关系，如“我的书”。
- 用在主谓之间，表示判断，如“他是老师”。
- 用在句子末尾，表示肯定或加强语气，如“是的”。

2. **“得”** 的基本释义包括：

- 用在动词或形容词后，表示可能、能够，如“跑得快”。
- 表示动作行为的程度，如“唱得好”。
- 在某些句子中起补充说明作用，如“高兴得跳起来”。

因为“启动”是动词，启动界面句子表达的是“启动可能会很慢”，所以应使用“得”字。

**Comment by ci010** [comment]
快发PR来拯救我这塑料中文

**Comment by lineltd** [comment]
稍后一并提交

**Comment by miaomiaotail** [comment]
改掉了，甚至句子也改了
