### ISSUE TITLE
Background Music For The Launcher

### ISSUE THREAD

**Issue by ShadowAndNitrix** [Voxelum/x-minecraft-launcher#637]
Have Background Music For When The Launcher Is Open, But We Can Choose What Music We Want To Playing But Its Minecraft Music Only.

**Comment by ci010** [comment]
Didn't get your point. What do you mean by "choose the music to play but it's Minecraft music only"? Current background music design is let user select their own music files to play.

**Comment by ShadowAndNitrix** [comment]
didn't know that lol
