### ISSUE TITLE
Cannot login with microsoft account

### ISSUE THREAD

**Issue by Lywnna** [Voxelum/x-minecraft-launcher#641]
I tried a bunch of times but I always get the same message:
"Fail to acquire Microsoft token. This might be a network issue. Please retry."

**Comment by BANSAFAn** [comment]
Try logging in manually, that is, through mail and the authorization app

**Comment by Lywnna** [comment]
i tried but same error

**Comment by Love-in-idleness** [comment]
u can try login in official launcher first, and then it may be ok to xmcl.

**Comment by ci010** [comment]
I wonder does this issue still exist now?
