### ISSUE TITLE
MACOS M1无法启动

### ISSUE THREAD

**Issue by PeroPer0** [Voxelum/x-minecraft-launcher#652]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Launcher Version

0.44.6

### Operating System

Mac

### Architecture

ARM

### Current Behavior

无法显示程序界面，程序坞上有显示应用图标。尝试下载0.44.5也是一样的情况，
这是我的main.log

[INFO] [5/31/2024, 8:15:26 PM] [App] Success to load windows utils!
[INFO] [5/31/2024, 8:15:26 PM] [App] Boot from /Users/us01/Library/Application Support/xmcl
[INFO] [5/31/2024, 8:15:26 PM] [App] Localhost server is listening on port 25555
[INFO] [5/31/2024, 8:15:26 PM] [App] cwd: /. env: production
[INFO] [5/31/2024, 8:15:26 PM] [App] Didn't find the start up url, try to load from config file.
[INFO] [5/31/2024, 8:15:26 PM] [LogConsumer] Set log root to /Users/us01/Library/Application Support/xmcl/logs
[INFO] [5/31/2024, 8:15:26 PM] [Controller] Activate app KeyStone Launcher http://xmcl.runtime/index.html
[INFO] [5/31/2024, 8:15:26 PM] [Telemtry] Telemetry client started
[INFO] [5/31/2024, 8:15:26 PM] [GFW] Detected current in China mainland.
[INFO] [5/31/2024, 8:15:26 PM] [Controller] http://xmcl.runtime/index.html
[INFO] [5/31/2024, 8:15:26 PM] [Controller] Load main window url http://xmcl.runtime/index.html
[INFO] [5/31/2024, 8:15:26 PM] [App] Current launcher core version is 0.44.6.
[INFO] [5/31/2024, 8:15:26 PM] [App] App booted
[INFO] [5/31/2024, 8:15:26 PM] [i18n] Set locale for the app 简体中文,繁體中文,English,Русский язык,Español,Français,Українська мова,Język polski,Nederlands,Galego,Deutsch,Magyar
[INFO] [5/31/2024, 8:15:26 PM] [Services] Create service BaseService
[INFO] [5/31/2024, 8:15:26 PM] [BaseService] Acquire singleton BaseService.checkUpdate()
[INFO] [5/31/2024, 8:15:26 PM] [BaseService] Initialized in 0ms.
[INFO] [5/31/2024, 8:15:26 PM] [BaseService] Check update
[INFO] [5/31/2024, 8:15:26 PM] [ElectronUpdater] Check update via Deprecated. Do not use it.
[INFO] [5/31/2024, 8:15:26 PM] [Services] Create service UserService
[INFO] [5/31/2024, 8:15:26 PM] [Services] Create service JavaService
[INFO] [5/31/2024, 8:15:26 PM] [Services] Create service VersionService
[INFO] [5/31/2024, 8:15:26 PM] [VersionService] Acquire singleton VersionService.refreshVersions()
[INFO] [5/31/2024, 8:15:26 PM] [Services] Create service InstanceService
[INFO] [5/31/2024, 8:15:26 PM] [Services] Create service PeerServiceKey
[INFO] [5/31/2024, 8:15:26 PM] [PeerService] Initialized in 0ms.
[INFO] [5/31/2024, 8:15:26 PM] [Services] Create service LaunchService
[INFO] [5/31/2024, 8:15:26 PM] [Services] Create service ResourceService
[INFO] [5/31/2024, 8:15:26 PM] [Services] Create service YggdrasilService
[INFO] [5/31/2024, 8:15:26 PM] [ResourceService] Initialized in 13ms.
[INFO] [5/31/2024, 8:15:26 PM] [ResourceService] Load /Volumes/SSD/Minecraft/saves toRemove=0 toUpdate=0 toCheck=0
[INFO] [5/31/2024, 8:15:26 PM] [ResourceService] Done to load resource domain saves
[INFO] [5/31/2024, 8:15:26 PM] [ResourceService] Warmed up saves resources
[INFO] [5/31/2024, 8:15:26 PM] [Services] Create service VersionMetadataService
[INFO] [5/31/2024, 8:15:26 PM] [VersionMetadataService] Initialized in 1ms.
[INFO] [5/31/2024, 8:15:26 PM] [Services] Create service PresenceService
[INFO] [5/31/2024, 8:15:26 PM] [ResourceService] Load /Volumes/SSD/Minecraft/modpacks toRemove=0 toUpdate=0 toCheck=0
[INFO] [5/31/2024, 8:15:26 PM] [ResourceService] Done to load resource domain modpacks
[INFO] [5/31/2024, 8:15:26 PM] [ResourceService] Warmed up modpacks resources
[INFO] [5/31/2024, 8:15:27 PM] [VersionService] Scan /Volumes/SSD/Minecraft/versions versions
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Load /Volumes/SSD/Minecraft/unclassified toRemove=0 toUpdate=0 toCheck=0
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Done to load resource domain unclassified
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Warmed up unclassified resources
[INFO] [5/31/2024, 8:15:27 PM] [Services] Create service InstanceScreenshotService
[INFO] [5/31/2024, 8:15:27 PM] [Controller] App Window is ready to show!
[INFO] [5/31/2024, 8:15:27 PM] [PresenceService] Initialized in 61ms.
[INFO] [5/31/2024, 8:15:27 PM] [ResourceWorker] Awake the worker function resourceWorkerEntry_worker_default(options){return new import_worker_threads2.Worker(path22,options)}
[INFO] [5/31/2024, 8:15:27 PM] [JavaService] Loaded 4 java from cache.
[INFO] [5/31/2024, 8:15:27 PM] [JavaService] Acquire singleton JavaService.refreshLocalJava()
[INFO] [5/31/2024, 8:15:27 PM] [JavaService] Re-validate cached 4 java locations.
[INFO] [5/31/2024, 8:15:27 PM] [JavaService] Initialized in 156ms.
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Load /Volumes/SSD/Minecraft/mods toRemove=0 toUpdate=0 toCheck=4805
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Done to load resource domain mods
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Warmed up mods resources
[INFO] [5/31/2024, 8:15:27 PM] [YggdrasilService] Initialized in 255ms.
[WARN] [5/31/2024, 8:15:27 PM] [ResourceService] Fail to load resource [Error: EISDIR: illegal operation on a directory, read] {
  [stack]: [Getter/Setter],
  [message]: 'EISDIR: illegal operation on a directory, read'
}
[WARN] [5/31/2024, 8:15:27 PM] [ResourceService] Fail to load resource [Error: EISDIR: illegal operation on a directory, read] {
  [stack]: [Getter/Setter],
  [message]: 'EISDIR: illegal operation on a directory, read'
}
[WARN] [5/31/2024, 8:15:27 PM] [ResourceService] Fail to load resource [Error: EISDIR: illegal operation on a directory, read] {
  [stack]: [Getter/Setter],
  [message]: 'EISDIR: illegal operation on a directory, read'
}
[WARN] [5/31/2024, 8:15:27 PM] [ResourceService] Fail to load resource [Error: EISDIR: illegal operation on a directory, read] {
  [stack]: [Getter/Setter],
  [message]: 'EISDIR: illegal operation on a directory, read'
}
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Load /Volumes/SSD/Minecraft/shaderpacks toRemove=0 toUpdate=0 toCheck=17
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Done to load resource domain shaderpacks
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Warmed up shaderpacks resources
[WARN] [5/31/2024, 8:15:27 PM] [ResourceService] Fail to load resource [Error: EISDIR: illegal operation on a directory, read] {
  [stack]: [Getter/Setter],
  [message]: 'EISDIR: illegal operation on a directory, read'
}
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Load /Volumes/SSD/Minecraft/resourcepacks toRemove=0 toUpdate=0 toCheck=263
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Done to load resource domain resourcepacks
[INFO] [5/31/2024, 8:15:27 PM] [ResourceService] Warmed up resourcepacks resources
[INFO] [5/31/2024, 8:15:27 PM] [InstanceService] Found 2 managed instances and 0 external instances.
[INFO] [5/31/2024, 8:15:27 PM] [UserService] Load 2 users
[INFO] [5/31/2024, 8:15:27 PM] [UserService] Acquire locks: refreshUser
[INFO] [5/31/2024, 8:15:27 PM] [UserService] Acquire locks: refreshUser
[INFO] [5/31/2024, 8:15:27 PM] [UserService] Initialized in 300ms.
[INFO] [5/31/2024, 8:15:27 PM] [UserService] Release locks: refreshUser
[INFO] [5/31/2024, 8:15:27 PM] [UserService] Release locks: refreshUser
[INFO] [5/31/2024, 8:15:27 PM] [InstanceService] Start load instance under /Volumes/SSD/Minecraft/instances/Minecraft
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Replace natives for version 1.12.2
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Replace natives for version 1.16.5
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Replace natives for version 1.18.2
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Replace natives for version 1.12.2-forge-14.23.5.2860
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Replace natives for version 1.12.2-forge1.12.2-14.23.5.2847
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Replace natives for version 1.16.5-forge-36.2.35
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Replace natives for version 1.16.5-forge-36.2.39
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Replace natives for version 1.16.5-forge-36.2.29
[INFO] [5/31/2024, 8:15:27 PM] [InstanceService] Loaded instance /Volumes/SSD/Minecraft/instances/Minecraft
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Replace natives for version 1.18.2-forge-40.2.17
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Replace natives for version 1.18.2-forge-40.2.14
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Replace natives for version 1.18.2-forge-40.2.4
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [VersionService] Found 27 local game versions.
[INFO] [5/31/2024, 8:15:27 PM] [VersionService] Release singleton VersionService.refreshVersions(). Took 324ms.
[INFO] [5/31/2024, 8:15:27 PM] [VersionService] Initialized in 324ms.
[INFO] [5/31/2024, 8:15:27 PM] [InstanceService] Initialized in 327ms.
[INFO] [5/31/2024, 8:15:27 PM] [UserService] Acquire locks: refreshUser
[INFO] [5/31/2024, 8:15:27 PM] [UserService] Release locks: refreshUser
[INFO] [5/31/2024, 8:15:27 PM] [InstanceService] Modify instance /Volumes/SSD/Minecraft/instances/Minecraft (undefined) {
    "lastAccessDate": 1717157727279
}.
[INFO] [5/31/2024, 8:15:27 PM] [Services] Create service InstanceOptionsService
[INFO] [5/31/2024, 8:15:27 PM] [InstanceOptionsService] Start to watch instance options.txt in /Volumes/SSD/Minecraft/instances/Minecraft
[INFO] [5/31/2024, 8:15:27 PM] [Services] Create service InstanceSavesService
[INFO] [5/31/2024, 8:15:27 PM] [Services] Create service InstanceResourcePacksService
[INFO] [5/31/2024, 8:15:27 PM] [InstanceResourcePackService] Acquire locks: resourcepacks//Volumes/SSD/Minecraft/instances/Minecraft
[INFO] [5/31/2024, 8:15:27 PM] [InstanceResourcePackService] Linking the at domain to /Volumes/SSD/Minecraft/instances/Minecraft/resourcepacks
[INFO] [5/31/2024, 8:15:27 PM] [Services] Create service InstanceModsService
[INFO] [5/31/2024, 8:15:27 PM] [Services] Create service InstanceShaderPacksService
[INFO] [5/31/2024, 8:15:27 PM] [InstanceShaderPacksService] Acquire locks: shaderpacks//Volumes/SSD/Minecraft/instances/Minecraft
[INFO] [5/31/2024, 8:15:27 PM] [InstanceShaderPacksService] Linking the at domain to /Volumes/SSD/Minecraft/instances/Minecraft/shaderpacks
[INFO] [5/31/2024, 8:15:27 PM] [Services] Create service InstanceInstallService
[INFO] [5/31/2024, 8:15:27 PM] [InstanceSavesService] Watch saves directory: /Volumes/SSD/Minecraft/instances/Minecraft/saves
[INFO] [5/31/2024, 8:15:27 PM] [InstanceResourcePackService] Skip linking the at domain as it already linked: /Volumes/SSD/Minecraft/instances/Minecraft/resourcepacks
[INFO] [5/31/2024, 8:15:27 PM] [InstanceResourcePackService] Release locks: resourcepacks//Volumes/SSD/Minecraft/instances/Minecraft
[INFO] [5/31/2024, 8:15:27 PM] [InstanceShaderPacksService] Skip linking the at domain as it already linked: /Volumes/SSD/Minecraft/instances/Minecraft/shaderpacks
[INFO] [5/31/2024, 8:15:27 PM] [InstanceShaderPacksService] Release locks: shaderpacks//Volumes/SSD/Minecraft/instances/Minecraft
[INFO] [5/31/2024, 8:15:27 PM] [nativeReplacer] Skip native replacement because it is disabled for modern version.
[INFO] [5/31/2024, 8:15:27 PM] [InstanceModsService] Mounted on instance mods: /Volumes/SSD/Minecraft/instances/Minecraft/mods
[INFO] [5/31/2024, 8:15:27 PM] [InstanceSavesService] Found 0 saves in instance /Volumes/SSD/Minecraft/instances/Minecraft
[INFO] [5/31/2024, 8:15:27 PM] [InstanceService] Saved instance /Volumes/SSD/Minecraft/instances/Minecraft
[INFO] [5/31/2024, 8:15:27 PM] [Services] Create service DiagnoseService
[INFO] [5/31/2024, 8:15:27 PM] [DiagnoseService] Diagnose for version 1.20.4 jar
[INFO] [5/31/2024, 8:15:27 PM] [DiagnoseService] Diagnose for version 1.20.4 libraries
[INFO] [5/31/2024, 8:15:28 PM] [DiagnoseService] Diagnose for version 1.20.4 assets index
[INFO] [5/31/2024, 8:15:28 PM] [DiagnoseService] Diagnose for version 1.20.4 assets
[INFO] [5/31/2024, 8:15:29 PM] [JavaService] Release singleton JavaService.refreshLocalJava(). Took 2496ms.
[INFO] [5/31/2024, 8:15:30 PM] [TaskManager] Task done and delete record!
[INFO] [5/31/2024, 8:15:30 PM] [BaseService] Release singleton BaseService.checkUpdate(). Took 3464ms.
[INFO] [5/31/2024, 8:16:28 PM] [ResourceWorker] Dispose the worker function resourceWorkerEntry_worker_default(options){return new import_worker_threads2.Worker(path22,options)}

**Comment by ci010** [comment]
难受了，我没有ｍ１没法测啊

**Comment by ci010** [comment]
弄到了一个m2的mac mini pro，这周末试试

**Comment by ci010** [comment]
你要不试试最新版？

**Comment by PeroPer0** [comment]
可以打开了，目前使用正常
