### ISSUE TITLE
<title>建议修改linux下的路径名称

### ISSUE THREAD

**Issue by Love-in-idleness** [Voxelum/x-minecraft-launcher#654]
### 是否已经有人报告过这个问题？

- [X] 我已经搜索过现有的问题

### 启动器版本

0.44.6

### 操作系统

Linux

### 架构

x64

### 当前行为

本人ubuntu24.04amd64,无法启动xmcl,但在把安装路径从/opt/X Minecraft Launcher改成/opt/x-minecraft-launcher后，在目录下./xmcl正常运行了。

### 期望行为

路径中有空格很不好影响正常使用，建议把“ ”变成“-”，或者直接改成xmcl,别用全称

**Comment by ci010** [comment]
你这个是什么安装的啊，我没linux没法直接测试，我怀疑这需要调某个build相关的配置

**Comment by Love-in-idleness** [comment]
我是直接下载64位的deb包安装的

**Comment by ci010** [comment]
试试好没好

**Comment by Love-in-idleness** [comment]
啊？我打开0.44.7的deb,发现没变化啊。
![截图 2024-06-07 23-32-38](https://github.com/Voxelum/x-minecraft-launcher/assets/93856868/248c15dc-aaf2-4622-8067-4673c7a445f4)

**Comment by Love-in-idleness** [comment]
安装后一样无法正常打开……但把包名从xmcl改成了x-minecraft-launcher,莫名其妙的变更……

**Comment by ci010** [comment]
> 安装后一样无法正常打开……但把包名从xmcl改成了x-minecraft-launcher,莫名其妙的变更……

 主要是我没linux，现在是改了 build 配置里的 packageName，但名字还是没改说明没改对配置。

**Comment by ci010** [comment]
https://github.com/electron-userland/electron-builder/issues/805 根据这个看还有点烦人啊，electron builder 不打算支持这种改动，我可能得自己hack当前的build流程

**Comment by Love-in-idleness** [comment]
我自己把原来的deb改了改，现在能用了。我把我改的发出来，你看看能不能把现在那个替换一下。https://stuouceducn-my.sharepoint.com/:u:/g/personal/lyj1098_stu_ouc_edu_cn/Ef64W0se7Y5Asejf7DUVlfAB-86Tz1U4g9TWJ1yK_R44dQ?e=6cxF4r

**Comment by ci010** [comment]
看看新版是不是好使了？

**Comment by Love-in-idleness** [comment]
好了，但是你postinst忘记改了
![截图 2024-06-17 22-12-34](https://github.com/Voxelum/x-minecraft-launcher/assets/93856868/12c2ddda-0dac-4ffa-8c10-d22e6a456151)

**Comment by Love-in-idleness** [comment]
最新版没修呢

**Comment by ci010** [comment]
> 最新版没修呢

postinit 这个文件不好使么

**Comment by Love-in-idleness** [comment]
> 好了，但是你postinst忘记改了 ![截图 2024-06-17 22-12-34](https://private-user-images.githubusercontent.com/93856868/340336818-12c2ddda-0dac-4ffa-8c10-d22e6a456151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4OTY1ODAsIm5iZiI6MTcxODg5NjI4MCwicGF0aCI6Ii85Mzg1Njg2OC8zNDAzMzY4MTgtMTJjMmRkZGEtMGRhYy00ZmZhLThjMTAtZDIyZTZhNDU2MTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDE1MTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MDFmOTdlYjExZWVjMzk5YzVmMDQxNDg5NDFlZTM4ZDk3NmViNGE5NWFkNDIxZjdkNWQ5MDQ0ZGQ5YzE1NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i5ZSaX1fokPZHBBorgcEFdNSy1YwTCpiAYlxJRbjgx0)

最新版deb解出来，/DEBIAN/postinst没有变化，其中路径名的X Minecraft Launcher并没改成xmcl,导致chrome-sandbox文件没有权限，从而app无法启动

**Comment by ci010** [comment]
新版本呢【

**Comment by Love-in-idleness** [comment]
完全解决了呢，看来是时候关掉这个issue了。  
xmcl是我用过的最好的mc启动器，希望能越做越好。
