### ISSUE TITLE
shader and modpack conflict

### ISSUE THREAD

**Issue by SJK9906** [Voxelum/x-minecraft-launcher#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.7

### Operating System

Windows

### Architecture

x64

### Current Behavior

i hava a 2 istances of modpacks with defferent resours pack, but the resourse of the third istance are unted with the resourspach of the second (this is applid for shader and resoursepack)

### Steps To Reproduce

enviroment:
an installation of X minecraft loucher with 2 or more instances of minecraft (my installation coitani a vanilla istances and a nstances with prominence II modpack)
1. play prominance II instance
2. play vanilla (or other) istances
3. open resourpack setting
4. you will see prominance II mod resourspacks united with your resoursepack

### Anything else?

to fix this problem i suggest to add possibility to dasable hardlinks separatly for istances

**Comment by ci010** [comment]
There is a button in resource pack page to switch the mode. By default, the resource packs are shared. After you click the button, it will use independent folder to store resource pack.

I will add a button to switch shader packs folder as well later.

**Comment by SJK9906** [comment]
ok thank
