### ISSUE TITLE
提示数据库无法打开，修改数据目录无用

### ISSUE THREAD

**Issue by muyunet** [Voxelum/x-minecraft-launcher#663]
### 是否已经有人报告过这个问题？

- [X] 我已经搜索过现有的问题

### 启动器版本

0.44.5

### 操作系统

Linux

### 架构

x64

### 当前行为

提示：“数据库无法打开！ 启动器将无法正常工作！ 请选择启动器可以访问的数据目录。你可以在设置页面重选数据目录。”
但多次修改数据目录（在设置中修改“数据存储位置”迁移时间过长，因此使用手动删除/home/.xmcl和/home/.config/xmcl后重新设置的方法）同样遇到此问题。

### 复现步骤

打开xmcl后便会遇到此问题

### 其他信息？

使用arch遇到此问题
![屏幕截图_20240616_154353](https://github.com/Voxelum/x-minecraft-launcher/assets/155161286/09aa31b8-90cd-4474-a89f-474b98385106)

**Comment by ci010** [comment]
头疼，你是不是没有用electron29？

我未来可能把sqlite的库切到wasm的，这样你们换electron版本就不会不兼容了（当然也不能太老，不然我用了新的electron api就会爆炸）

**Comment by muyunet** [comment]
> 头疼，你是不是没有用electron29？
> 
> 我未来可能把sqlite的库切到wasm的，这样你们换electron版本就不会不兼容了（当然也不能太老，不然我用了新的electron api就会爆炸）

用paru安装的，应该是吧
