### ISSUE TITLE
request for italian lenguage

### ISSUE THREAD

**Issue by SJK9906** [Voxelum/x-minecraft-launcher#665]
can add italian lenguage support?
(what file i do to modify or create for lenguage UI?)

**Comment by Vorobushekb** [comment]
Everything you need to start working on localization is written here https://docs.xmcl.app/en/guide/i18n

**Comment by ci010** [comment]
Use https://xmcl.app/en/guide/i18n. The docs domain is deprecated.

**Comment by SJK9906** [comment]
how i can add i18n ally yto the sidebar of VScode?, the exstension not work
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/129201282/90022dd2-b33c-479e-bf9b-c7d7e27e09e6)

**Comment by ci010** [comment]
> how i can add i18n ally yto the sidebar of VScode?, the exstension not work ![image](https://private-user-images.githubusercontent.com/129201282/341546908-90022dd2-b33c-479e-bf9b-c7d7e27e09e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NDMxOTgsIm5iZiI6MTcxODk0Mjg5OCwicGF0aCI6Ii8xMjkyMDEyODIvMzQxNTQ2OTA4LTkwMDIyZGQyLWIzM2MtNDc5ZS1iZjliLWM3ZDdlMjdlMDllNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwNDA4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTliMmZjODA4NjNhYjQ1MmJhZDA2OGQ1NmZiOWEwODU4OTBmMjk0YjExNmM2YjgxZTk0NzE2NTI0MmNiZGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mA6tPVbJ40D9KPMKPvkH1HGhWbwtGx-QJ1_kqmW9oSg)
> 
> and how i can resolve it? ![image](https://private-user-images.githubusercontent.com/129201282/341548098-65ada5c6-0225-4c8a-8425-94cba1d18173.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NDMxOTgsIm5iZiI6MTcxODk0Mjg5OCwicGF0aCI6Ii8xMjkyMDEyODIvMzQxNTQ4MDk4LTY1YWRhNWM2LTAyMjUtNGM4YS04NDI1LTk0Y2JhMWQxODE3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwNDA4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWRlNDhjMmM4NTljZjZiMWE5ZWIwNGRjMDI2MGM0NzFlNDZiZDhhZDVkNTY5NTIyZTEzMWRlNGJkODkwMmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4Fow11eyNZfqLy3dFlp2TdDlvHHr41F9vwyKOOFs3yw) i'm using the following guide: https://xmcl.app/en/guide/i18n#install when ready a thirst translation how i can add to main brack?

![image](https://github.com/Voxelum/x-minecraft-launcher/assets/8425057/1301f9b2-ae16-4bc7-831d-1af14a15d83c)
Right click the sidebar icon, check the 'i18n Ally"

The second problem seems to be you didn't install the project. Did you run `pnpm install` to install the dependencies?

**Comment by SJK9906** [comment]
sorry, but i have lauched pnpm install commad and correctly installed the project, (with all dipendencis).
i have installed x minecraft laucher 2 timers
1 for normal usage (downloading fron site to play minecraft)
2 with pnpm install (with windows terminal without admin privileges to star translation) not with vscode terminal

**Comment by SJK9906** [comment]
sorry, but i have lauched pnpm install commad and correctly installed the project, (with all dipendencis).
i have installed x minecraft laucher 2 timers
1 for normal usage (downloading fron site to play minecraft)
2 with pnpm install (with windows terminal with admin privileges to star translation) not with vscode terminal

**Comment by SJK9906** [comment]
how i can resolve it, i'm not a developer, i'm am a translator only but when try to lauche i have this error
All collection items must start at the same column
    at Object.parseForESLint (C:\Users\Satoru Gojo\x-minecraft-launcher\node_modules\.pnpm\yaml-eslint-parser@0.3.2\node_modules\yaml-eslint-parser\lib\parser.js:42:19)
    at parseYAML (C:\Users\Satoru Gojo\x-minecraft-launcher\node_modules\.pnpm\yaml-eslint-parser@0.3.2\node_modules\yaml-eslint-parser\lib\index.js:20:21)
    at generate (C:\Users\Satoru Gojo\x-minecraft-launcher\node_modules\.pnpm\@intlify+bundle-utils@3.4.0_vue-i18n@8.28.2_vue@2.7.16_\node_modules\@intlify\bundle-utils\lib\yaml.js:33:52)
    at generateBundleResources (C:\Users\Satoru Gojo\x-minecraft-launcher\node_modules\.pnpm\@intlify+unplugin-vue-i18n@0.7.3_esbuild@0.18.20_rollup@2.79.1_vite@3.2.10_@types+node@20.14._qvjtxzxvtc3ixx3u76ypi6fgja\node_modules\@intlify\unplugin-vue-i18n\lib\index.cjs:494:24)
    at async Context.load (C:\Users\Satoru Gojo\x-minecraft-launcher\node_modules\.pnpm\@intlify+unplugin-vue-i18n@0.7.3_esbuild@0.18.20_rollup@2.79.1_vite@3.2.10_@types+node@20.14._qvjtxzxvtc3ixx3u76ypi6fgja\node_modules\@intlify\unplugin-vue-i18n\lib\index.cjs:325:22)
    at async Object.load (file:///C:/Users/Satoru%20Gojo/x-minecraft-launcher/node_modules/.pnpm/vite@3.2.10_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-372dab03.js:40584:32)
    at async loadAndTransform (file:///C:/Users/Satoru%20Gojo/x-minecraft-launcher/node_modules/.pnpm/vite@3.2.10_@types+node@20.14.2_terser@5.31.1/node_modules/vite/dist/node/chunks/dep-372dab03.js:36936:24
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/129201282/fe0a5145-4ee4-4789-b256-7c91edf3aa36)

how i can resolve it to test my translation?

**Comment by SJK9906** [comment]
were i do upload modified tralsation file?

**Comment by ci010** [comment]
> were i do upload modified tralsation file?

After you made the change to files, you need to create Pull Request to this repository. Follow the github guide https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by SJK9906** [comment]
ok now you can rewiew at https://github.com/Voxelum/x-minecraft-launcher/pull/667
