### ISSUE TITLE
When installing the neoforge modpack, the modloader is not installed

### ISSUE THREAD

**Issue by Soochaehwa** [Voxelum/x-minecraft-launcher#666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.9

### Operating System

Windows

### Architecture

x64

### Current Behavior

When installing the neoforge modpack, the modloader is not installed

### Expected Behavior

When installing the neoforge modpack, the modloader must be installed together

### Steps To Reproduce

Install neoforge based modpack (e.g. [neotech](https://www.feed-the-beast.com/modpacks/123-ftb-neotech))

### Anything else?

![2034](https://github.com/Voxelum/x-minecraft-launcher/assets/43947445/dc039c8a-7ba5-4782-93f4-d9c7d096f0b7)

**Comment by ci010** [comment]
will fix next version... i didn't play neoforge modpack yet

**Comment by ci010** [comment]
Does this issue still repro in new version?

**Comment by Soochaehwa** [comment]
Modpacks from Neoforge that are downloaded from FTB will now install the modloader normally, but modpacks that are downloaded from Curseforge will still not install the modloader

**Comment by ci010** [comment]
#674 Should fix
