### ISSUE TITLE
Bad English

### ISSUE THREAD

**Issue by JebronLamess** [Voxelum/x-minecraft-launcher#671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

Latest

### Operating System

Windows

### Architecture

x64

### Current Behavior

When I log in to my account the message says "Succeed! Now you can close this window and return to the launcher!"

### Expected Behavior

When I log in to my account the message should say "Success! Now you can close this window and return to the launcher!"

### Steps To Reproduce

1. Login
2. Observe success window

**Comment by ShadowAndNitrix** [comment]
Ok I Have Seen This Just Now And I'm Confused On What Is Happening, Could You Explain A Little Bit More Please?
