### ISSUE TITLE
Some mods say that they are not installed even though they are

### ISSUE THREAD

**Issue by merll002** [Voxelum/x-minecraft-launcher#672]
When you click install on a mod, sometimes it doesn't say that its installed.

**Comment by Peperehobbits01** [comment]
> When you click install on a mod, sometimes it doesn't say that its installed.

Yeah that's bug I had my self, it's very annoying. I don't realy now why it happends tho, and also, you know there was a template you could use to report whit ease the bug? Anyway, hope this one could be fixed, but it needs some looking into first.

**Comment by ci010** [comment]
Hope new version mitigate this issue.

**Comment by Peperehobbits01** [comment]
I hope to, but I am not home. So I can not try that out.

**Comment by Peperehobbits01** [comment]
It does mitigate the issues but de might want to debug a bit to fix thé rest.
