### ISSUE TITLE
下载mod和整合包

### ISSUE THREAD

**Issue by ji1145** [Voxelum/x-minecraft-launcher#676]
1下载mod和整合包不像pcl那么方便
xmcl：
![21-02-10](https://github.com/Voxelum/x-minecraft-launcher/assets/170233649/6febf2ae-2378-46ae-91cf-1d72fbb89a53)
pcl:
![21-04-20](https://github.com/Voxelum/x-minecraft-launcher/assets/170233649/1dc6f7d7-41a3-47c5-ae18-f9424055018b)
![21-02-10](https://github.com/Voxelum/x-minecraft-launcher/assets/170233649/377d4bcd-5010-4bc4-85ca-2f948f0d266e)
![21-04-06](https://github.com/Voxelum/x-minecraft-launcher/assets/170233649/4f86753b-e465-4ae4-a0d1-63e37cbfa3ec)
![21-04-08](https://github.com/Voxelum/x-minecraft-launcher/assets/170233649/03978e0c-0ea3-4ee4-a13f-729468728659)
![21-04-16](https://github.com/Voxelum/x-minecraft-launcher/assets/170233649/12bb1a9e-2f59-4fcb-9a7a-fa9b01fce50f)
2从其他地方加入的原版，整合包等都只会显示是1.20.6版本：
![21-09-15](https://github.com/Voxelum/x-minecraft-launcher/assets/170233649/40c91301-b88e-47b0-818b-71997cf23861)
![21-08-03](https://github.com/Voxelum/x-minecraft-launcher/assets/170233649/a8310d62-52a9-45ff-af9b-f7b42023ca6c)
3创建世界这个界面看不懂思密达：
![21-08-18](https://github.com/Voxelum/x-minecraft-launcher/assets/170233649/aacb2f6c-1996-46fc-bffd-fe982ea0b422)
4
.minecraft要改成.xmcl有点不方便
5假如说我的多个版本装在其他的.minecraft文件夹里就不会导入另一个文件夹的世界了
6一切都很好up加油

**Comment by ji1145** [comment]
4.minecraft改成.xmcl不方便
![21-20-12](https://github.com/Voxelum/x-minecraft-launcher/assets/170233649/5fd59aad-1549-4ab2-9359-90cc6a6fd493)
![21-19-37](https://github.com/Voxelum/x-minecraft-launcher/assets/170233649/3c01551e-98ba-4e1b-b6c2-208069d5646d)

**Comment by ci010** [comment]
注意啊，我之所以不用.minecraft是因为xmcl对游戏文件的处理和.minecraft不兼容！不建议直接改名

**Comment by teaSummer** [comment]
个人认为，第2、3、4点实际上是**不正确的操作**导致的。

与PCL不同的是，XMCL使用实例来保存。

---

另外，如果你想导入游戏，可以通过第3点进行操作，需要注意的是：

- 图中是**创建游戏**，而不是创建世界。
- XMCL 已经提供了**从 .minecraft 导入**的方法，图中也有。
