### ISSUE TITLE
无法导入整合包

### ISSUE THREAD

**Issue by beeyeefox** [Voxelum/x-minecraft-launcher#677]
导入整合包的时间非常长，而且最后提示导入失败

**Comment by ci010** [comment]
导入的是什么整合包

**Comment by beeyeefox** [comment]
> 导入的是什么整合包

乌托邦3

**Comment by ci010** [comment]
> > 导入的是什么整合包
> 
> 乌托邦3

https://www.bilibili.com/video/BV1ZS411w7XC/?vd_source=e288d2bcd63e073c7964806255c3ea1b 这个么

**Comment by beeyeefox** [comment]
> > > 导入的是什么整合包
> > 
> > 
> > 乌托邦3
> 
> https://www.bilibili.com/video/BV1ZS411w7XC/?vd_source=e288d2bcd63e073c7964806255c3ea1b 这个么

是的

**Comment by beeyeefox** [comment]
![QQ20240706-143448](https://github.com/Voxelum/x-minecraft-launcher/assets/109936140/c6a8469f-83eb-4108-83d9-9f95fa28a189)
这个

> > > 导入的是什么整合包
> > 
> > 
> > 乌托邦3
> 
> https://www.bilibili.com/video/BV1ZS411w7XC/?vd_source=e288d2bcd63e073c7964806255c3ea1b 这个么

![Uploading QQ20240706-143448.png…]()

**Comment by beeyeefox** [comment]
![QQ20240706-143624](https://github.com/Voxelum/x-minecraft-launcher/assets/109936140/46752a1c-97b7-42e9-bcbf-d9133ffc5fed)
一直会保持在这种状态

**Comment by ci010** [comment]
#674
