### ISSUE TITLE
Fullscreen at startup (windows)

### ISSUE THREAD

**Issue by Multigriffes** [Voxelum/x-minecraft-launcher#679]
I noticed when i start the launcher, it takes the screen entirely but when we go in a corner (ex : wanna close the window) the pointer is selecting the window to resize it.
We need to click on fullscreen then we can click.
Is that possible to being able to like launching the launcher fullscreen by default.

**Comment by ci010** [comment]
Sounds weird. Do you have gif or video to demo this case?

**Comment by Zgoly** [comment]
@ci010

I think I know this bug.
Here is a full screenshot of my screen after launching the launcher on Windows 11:

![sample](https://github.com/Voxelum/x-minecraft-launcher/assets/46041044/b2306e50-844b-4468-89f5-112d43bcd45b)

And little closer look:
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/46041044/77324ecd-4eba-4b60-ad1d-4de4ce984588)

Launcher does not launch in full screen mode, but in windowed mode and stretched to the full width & height of the screen.
Discord also had similar problem when Windows 11 came out, but now everything works fine.

To fix this, you can try adding `browser.maximize()` somewhere here:
https://github.com/Voxelum/x-minecraft-launcher/blob/72265fbe47ba63f74915bd93512d001af91b945b/xmcl-electron-app/main/ElectronController.ts#L337-L346

This should fix the problem. But I'm not sure whether this will affect other elements of the launcher. In my tests I put it right before `browser.show()` and everything worked fine.

**Comment by ci010** [comment]
Should fixed in the commit mentioned above.

**Comment by Multigriffes** [comment]
Sorry I wasn't here to reply. Thanks for the fix 😁

**Comment by Multigriffes** [comment]
Should I close the issue ?

**Comment by ci010** [comment]
> Should I close the issue ?

You don't have to worry about that. The new release should auto-close this issue.
