### ISSUE TITLE
pressing "RESTART TO INSTALL" does nothing 

### ISSUE THREAD

**Issue by RandomGuyNumber731** [Voxelum/x-minecraft-launcher#682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.12

### Operating System

Linux

### Architecture

x64

### Current Behavior

it does nothing no matter how hard i click it

### Expected Behavior

usual updating sequence 

### Steps To Reproduce

start updating
wait till it shows "restart to install" button
press it

### Anything else?

![Peek 2024-07-09 21-08](https://github.com/Voxelum/x-minecraft-launcher/assets/87827918/54dc9f38-2504-478a-a9b5-5aebbd12dd6a)

**Comment by Zgoly** [comment]
Can confirm, had the same bug on Windows. Restarting launcher manually and pressing this button again helped. But I don't think this is a valid solution

**Comment by ci010** [comment]
What kind of release you are using? Deb? AppImage? tar?

**Comment by Peperehobbits01** [comment]
Jeez it's the same bug I have in #619 , and I don't think it works for me either right now.

**Comment by RandomGuyNumber731** [comment]
> What kind of release you are using? Deb? AppImage? tar?

sorry havent had notification

i use deb package

**Comment by Peperehobbits01** [comment]
I don't now, but I'll go look at some docs later today.

**Comment by Peperehobbits01** [comment]
This might [help](https://wiki.debian.org/EnvironmentVariables), but I look a bit more in detail

**Comment by ci010** [comment]
It add the logic that if the os is linux then I will try to check the full update (works for deb or rpm) first. Then I fallback to common logic (replacing the asar file), and let's see if this is worked. 8bee2c4beb8bae68cbdd0d2ac44673d14eef5db7

**Comment by Peperehobbits01** [comment]
OK :ok_hand:

**Comment by ci010** [comment]
See if deb new version can auto-updated

**Comment by Peperehobbits01** [comment]
> See if deb new version can auto-updated

Well, that dosen't work on my Linux Mint.

**Comment by Peperehobbits01** [comment]
@ci010 Can you assign le to this issues to so I can follow it and remember to go look at docs please?

**Comment by Peperehobbits01** [comment]
OK so, I am getting closer, I found on the docs auto update for [snap](https://www.electronjs.org/docs/latest/tutorial/snapcraft#background-and-requirements). But This is kind of bad because well the ones that don't support snap will not have the launcher auto update. So I will dig a bit more.

**Comment by Peperehobbits01** [comment]
I think it works now but I am going to look in the next update.

**Comment by Peperehobbits01** [comment]
The only weird thing is that, it doesn't close when you click the restart button after the command is executed but except from that. It's good.
