### ISSUE TITLE
no sudo access prompt when starting minecraft instance

### ISSUE THREAD

**Issue by RandomGuyNumber731** [Voxelum/x-minecraft-launcher#684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.13

### Operating System

Linux

### Architecture

x64

### Current Behavior

when starting minecraft instance there is no sudo prompt 

### Expected Behavior

regular launching sequence

### Steps To Reproduce

start any instance
wait till it starts
crash

**Comment by ci010** [comment]
I wonder why we need sudo to start the Minecraft (java process)?

**Comment by RandomGuyNumber731** [comment]
> I wonder why we need sudo to start the Minecraft (java process)?

im pretty sure its java startup thing and i think i fixd it somehow
