### ISSUE TITLE
forge installation still dont work

### ISSUE THREAD

**Issue by RandomGuyNumber731** [Voxelum/x-minecraft-launcher#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.13

### Operating System

Linux

### Architecture

x64

### Current Behavior

installation stuck at 0.00 kb / 0.03 kb

### Expected Behavior

regular installation sequence 

### Steps To Reproduce

select any version of forge in instance settings
proceed with installation

### Anything else?

![Peek2024-07-1013-05](https://github.com/Voxelum/x-minecraft-launcher/assets/87827918/63f0c2bc-6465-44d4-99b2-c9d7a47e5ce6)

**Comment by ci010** [comment]
It's the forge post-processing process. In this process, the forge won't download anything, but generates jars from minecraft and forge files. I wonder if this process stuck forever?

**Comment by RandomGuyNumber731** [comment]
i think forge servers was down it works normal now
