### ISSUE TITLE
Dependencies for Optional Mod Dependencies Show as "Required"

### ISSUE THREAD

**Issue by MikulDev** [Voxelum/x-minecraft-launcher#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

v0.44.13

### Operating System

Linux

### Architecture

x64

### Current Behavior

If a mod has optional dependencies, any library mods that those dependencies rely on will be classified as "required". 
For example:
![image](https://github.com/Voxelum/x-minecraft-launcher/assets/24680934/0762daef-4362-4132-beef-af80e84c79c9)

CristelLib is a dependency of William Wyther's Expanded Ecosphere, an optional dependency of Cold Sweat.
TerraBlender is a dependency of Biomes O' Plenty, another optional dependency of Cold Sweat.

This means that, when downloading a mod, unnecessary dependency mods are downloaded as well.

### Expected Behavior

These "dependencies of dependencies" should not be listed, or at least marked as "optional". 

### Steps To Reproduce

1. Find any mod with optional dependencies, that themselves have required dependencies.
2. Download the mod. The unnecessary dependencies are downloaded as well.

**Comment by ci010** [comment]
I will temporary fix this by marking optional dependencis's dependencies optional.

**Comment by MikulDev** [comment]
That would be good enough for me. Thank you!
