### ISSUE TITLE
News in the "My inventory" isn't fetching the latest news

### ISSUE THREAD

**Issue by Peperehobbits01** [Voxelum/x-minecraft-launcher#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.14

### Operating System

Linux

### Architecture

x64

### Current Behavior

When you get in the "My inventory" section there is a news erea where all the latest news of Minecraft are shown, but here the latest is one from 22 of December 2023, and there is no sign of anything more recent.

### Expected Behavior

When you get in the "My inventory" section the news erea shows the latest news.

### Steps To Reproduce

1. Open the app
2. Go in the "My inventory" tab
3. Look at the news section.
4. You will not found any news newer then the 22 of December 2023.

**Comment by ci010** [comment]
Looks like the https://[launchercontent.mojang.com/news.json](https://launchercontent.mojang.com/news.json) is outdated? I need to capture the network for official launcher to see what's the new api.

**Comment by Peperehobbits01** [comment]
Yep, it seems like it.

**Comment by ci010** [comment]
Resolved in #692
