### ISSUE TITLE
Global settings don't save after restart

### ISSUE THREAD

**Issue by Peperehobbits01** [Voxelum/x-minecraft-launcher#691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.14

### Operating System

Linux

### Architecture

x64

### Current Behavior

When you try to change a settings in the app, it dosen't take effect and dosen't get registered as when the app is restarted, the setting is back to it's prior state.

### Expected Behavior

When changing a global settings, it takes effect (expect if mentions that it dosen't), and when you restart the app. The setting isn't back to it's prior state before you decided to change it.

### Steps To Reproduce

1. Open the app
2. Go to the cogweel (aka the global settings).
3. Try to change any settings (excluding the ones for the music)
4. Restart the launcher
5. Go back to the cogweel (aka the global settings).
6. It's like before you changed the setting.

### Anything else?

This bug dosen't seem to affect all options, I look a bit more in details to see what is, and what isn't affected. This might help to understand the cause of the bug.

**Comment by ci010** [comment]
Should resolved in #692

**Comment by Peperehobbits01** [comment]
Thanks I'll try it out when I am home.
