### ISSUE TITLE
The "Background type" settings dosen't work

### ISSUE THREAD

**Issue by Peperehobbits01** [Voxelum/x-minecraft-launcher#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.15

### Operating System

Linux

### Architecture

x64

### Current Behavior

When you try to put a image, a video, a halo, or particles. The background stays black. This as been a bug for me for a while, but I haven't took the time to report it. Now I am taking it.

### Expected Behavior

Adding images, videos, halos or particles, like before and having them show up.

### Steps To Reproduce

1. Open the launcher
2. Go in the settings
3. Try to change the background to a image, video, halo or particles
4. Nothing happends

**Comment by ci010** [comment]
Interesting... the feature works for me on Windows. Maybe i need a linux to test.

**Comment by CDmking** [comment]
Maybe, you should close "Show background color as overlay".
也许你该关掉“将背景颜色显示为叠加层”。

**Comment by ci010** [comment]
> Maybe, you should close "Show background color as overlay". 也许你该关掉“将背景颜色显示为叠加层”。

Good point. Another thing is if you want "Show background color as overlay" enabled, you can decrease the background color's alpha.

**Comment by Peperehobbits01** [comment]
I'll try and see.

**Comment by Peperehobbits01** [comment]
Thanks you, it works now. I'll close this issues then :wink: !
