### ISSUE TITLE
Launcher closing when the game is running and the option "hide launcher in tray" is set to true

### ISSUE THREAD

**Issue by Peperehobbits01** [Voxelum/x-minecraft-launcher#707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.17

### Operating System

Linux

### Architecture

x64

### Current Behavior

When you open the launcher by using the tray icon, and the game is running, when you will close the launcher whit the "X" button on the window bar. Well it closes the launcher.

### Expected Behavior

When you open the launcher by using the tray icon, and the game is running, when you will close the launcher whit the "X" button on the window bar. Well it minimize the launcher in the system tray.

### Steps To Reproduce

1. open the launcher
2. Run a Minecraft instance
3. Open the launcher from the tray icon by clicking "Show Diagnose".
4. Then close the launcher whit the "X" from the window bar.
5. The launcher will not go in the system tray.

### Anything else?

Also, can you add a "Show launcher" in the tray icons options please, because neading to open diagnose to have access to the launcher while being in game is kind of, not great.

**Comment by ci010** [comment]
I'm not familiar with linux tray. Sounds like you expect it's behave like MacOS's dock? In MacOS, the launcher will not exit if all the windows are closed

**Comment by Peperehobbits01** [comment]
Yeah that's a bit like that

**Comment by ci010** [comment]
Try this in new prebuild

**Comment by Peperehobbits01** [comment]
Sure I'll try

**Comment by Peperehobbits01** [comment]
It works like a charm, thanks dude.
