### ISSUE TITLE
Launcher not going in system tray when minimized in the taskbar when the game launches

### ISSUE THREAD

**Issue by Peperehobbits01** [Voxelum/x-minecraft-launcher#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.44.17

### Operating System

Linux

### Architecture

x64

### Current Behavior

When you launch a game and you click on the "-" before the window of the game as apeard, the launcher whill not get in the system tray, and just stay minimised on the taskbar.

### Expected Behavior

When you minimized the launcher when a game (aka instance) is launching, when the settings "Hide launcher when game starts" is turned on (which is the case here), the launcher gets in the system tray and isn't in the taskbar anymore, like when you don't minimized when the game is launching.

### Steps To Reproduce

1. Open XMCL.
2. Press play to launch any instance you want.
3. Then click on this icon "-" or the green light (I think) on macOS to minimized in the taskbar.
4. Then wait for your instance to launch.
5. When it's done you can look at your taskbar and you will see that the XMCL app is still in it.

### Anything else?

If you need some screenshot to understand more, because I said rubish, please let me now.

**Comment by ShadowAndNitrix** [comment]
Have You Tried To Double Click The Icon To Hide It? If That Don't Work I Can Try To Help Some More

**Comment by Peperehobbits01** [comment]
That dosen't work, but hum... Exept if there is changes in the code, there is no way this is fix... but I can try to provide some logs I guess...

**Comment by Peperehobbits01** [comment]
That's a bit to far 0.35.17 ... but yeah, might wan't to try that.

**Comment by ShadowAndNitrix** [comment]
> That's a bit to far 0.35.17 ... but yeah, might wan't to try that.

The Only Reason I'm Running This Version Is Cause I Can't Get The Update Due To Them Blocking .exe Files So I Can't Update Mine :| But Do Try Go Down A Few Versions And See If That Works

**Comment by Peperehobbits01** [comment]
:joy: You are playing whit it at school, now that's a good xD

**Comment by ShadowAndNitrix** [comment]
> 😂 You are playing whit it at school, now that's a good xD

Yep Lol.

**Comment by ci010** [comment]
You could try this in new prebuilds
