### ISSUE TITLE
XMCL 未能适应 Modrinth 上的项目处于已存档状态

### ISSUE THREAD

**Issue by ddzzkunye** [Voxelum/x-minecraft-launcher#710]
XMCL 未能适应 Modrinth 上的项目处于已存档状态.

举例: Blendium 已经过时且归档, 在Modrinth上有一个醒目的红条, 但是在XMCL的模组页面中并没有类似 Modrinth 上的醒目警示.

**Comment by ci010** [comment]
小问题，下个feature版本加

**Comment by ci010** [comment]
![image](https://github.com/user-attachments/assets/8c1c94f4-a3bb-4ef6-8dc0-35073ea4bac2)

整成这样，应该够用了

**Comment by ddzzkunye** [comment]
很好捏
