### ISSUE TITLE
Mod duplication bug

### ISSUE THREAD

**Issue by 66BA9Q-ME49** [Voxelum/x-minecraft-launcher#712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

v0.45.1

### Operating System

Windows

### Architecture

x64

### Current Behavior

Sometimes, I end up with multiple versions of a same mod. The problem seems to come from dependency management.
I encountered this issue when installing many mods while transferring everything from another launcher as I prefer installing the mods using XMCL rather than copy/pasting the jar files from the old launcher to XMCL.

### Expected Behavior

There should be only one version of a same mod.

### Steps To Reproduce

As I'm installing a large number of mods, I can't really notice when and why it goes wrong.
There are 2 scenarios:
One scenario results in two different enabled versions of the same mod (still trying to reproduce it).
The other scenario (which I've been able to reproduce) results in an enabled and a disabled version of the same mod:
- Install a mod with its dependencies.
- Disable that mod and its dependencies.
- Install another mod that shares at least one of the dependencies of the first mod.
- You'll end up with two versions of the shared dependencies (one disabled and one enabled).

### Anything else?

Here's an example of the second scenario with *Oh The Biomes You'll Go* and *Biomes O' Plenty*:

https://github.com/user-attachments/assets/75cbc5cf-8413-4c1d-acbe-d9ff593d0eb0

**Comment by ShadowAndNitrix** [comment]
Ok I Can Probly Explain It. So The Difference Between .jar And .jar.disabled Is That The Diabled Jar Files Changes And Does Nothing But The .jar File Is The One That Is Active. Need A More Detailed Explanation?
