### ISSUE TITLE
modpack reinstallation

### ISSUE THREAD

**Issue by GyomeiHimejima9906** [Voxelum/x-minecraft-launcher#717]
can add possibility to force redaonlowd for modpack's mods? (without manually delating "library","versions", "istances/istance-name", "mods", ecc)

**Comment by ci010** [comment]
so you want the manually triggering the recheck for:
1. minecraft stuff: version jar, libraries, assets
2. modpack mods & config & other overrides

Is this understanding correct?

**Comment by SJK9906** [comment]
yes,
something on my modpack (prominance II RPG) installation was silently corrupte (bit rotting) but i don't know them. to force a redownload i had to make this workaroud:
1. make data backup
2. manually delate xmcl folder
3. make a clear installation of xmcl
4. restoring data backup

**Comment by FilipNones** [comment]
a corruption check would be helpful, sometimes wierd things happens, especially when you modify ans update the mods inside, and I have to clean and reinstall the modpack

**Comment by ci010** [comment]
This is implemented in new version. If it has bug, please open a separated bug.
