### ISSUE TITLE
When a forge modpack is getting closed the stop button of the instance isn't switching back to play (and the launcher dosen't open)

### ISSUE THREAD

**Issue by Peperehobbits01** [Voxelum/x-minecraft-launcher#718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.45.2

### Operating System

Linux

### Architecture

x64

### Current Behavior

When a forge modpack is getting closed the stop button of the instance isn't switching back to play (and the launcher doesen't open)

### Expected Behavior

When a forge modpack is getting closed the stop button of the instance is switching back to play (and the launcher does open)

### Steps To Reproduce

1. Open XMCL.
2. Launch a Forge instance.
3. Close the Forge instance.
4. The launcher will not open back from tray, and if you use the "show launcher" button (a big thanks again for that honestly), the stop button that should change in play and be green will not change, until you "close the instance".

**Comment by ci010** [comment]
the launch detection is based on log. I guess is the modpack's mods alt the logs format, so the launcher cannot detect the status correctly. What mods are u using?

**Comment by Peperehobbits01** [comment]
Never mind, seems like the bug is fixed.. Sorry for the false report then.
