### ISSUE TITLE
Mrpacks can not be exported on the website

### ISSUE THREAD

**Issue by Peperehobbits01** [Voxelum/x-minecraft-launcher#722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.45.2

### Operating System

Linux

### Architecture

x64

### Current Behavior

Multiple different erros can apear depending on the fact that you chose to make a stric or not and the .mrpack isn't being putted by default.

### Expected Behavior

No erros, I can export the modpack and put it as a release of my modpack on Modrinth.

### Steps To Reproduce

1. Open XMCL
2. Go to a instance you wan't to export.
3. Click the export button and keep the default settings
4. Just change remove the folders you don't wan't and files, like you would do normaly
5. Select your folder for the files to be sent.
6. Try to create a release on your modrinth Project
7. When you will publish it, you will get a error. It can be different depending on the settings you change like not having the modrinth strict settings turn on.

### Anything else?

If you need more info, please let me now, I can share video if you wan't, and hum... this as been a bug for me since I actully installed it, so about the 0.36.0 but because I was using Modrinth Launcher at the same time this wasn't realy worth my time to report but, the app no longer works on my machine so... my only choice was to ask a friend to make the mrpack, and that's terrible so I am reporting the issues now. I should of done it earlyier, let's be honest xD

**Comment by ci010** [comment]
Any error screenshot?

**Comment by Peperehobbits01** [comment]
Sure, i'll send you that when I am home

**Comment by Peperehobbits01** [comment]
OK, so it seems it's just the fact that you need to add the .mrpack extention for it to work, as it isn't added on the name by default. Then it works here is video that show it.
https://youtu.be/Y1ASirkE80o -> Defalut Behavior
https://youtu.be/2fQu3EXB6jI -> The functionning export

**Comment by ci010** [comment]
Try the build ab7613d96974d474cd9ba046f50d8898c21790cd

**Comment by Peperehobbits01** [comment]
Sure, but how can I do that? Could you explain to me. I'll do it when I am home.

**Comment by ci010** [comment]
Go https://xmcl.app/en/prebuilds to download latest prebuilds

**Comment by Peperehobbits01** [comment]
Ok thanks it's noted, I'll try it at home

**Comment by Peperehobbits01** [comment]
It's fixed on the prebuild :+1:
