### ISSUE TITLE
Install Shaders

### ISSUE THREAD

**Issue by coolguy027** [Voxelum/x-minecraft-launcher#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

v0.45.2

### Operating System

Windows

### Architecture

x64

### Current Behavior

Shaders are installed into the resource pack folder when importing a pack

### Expected Behavior

Install shaders into the shaders folder

### Steps To Reproduce

1. Export a modpack
2. Import back into launcher

**Comment by ci010** [comment]
Fixed this issue for some curseforge modpack
