### ISSUE TITLE
Неуспешная авторизация

### ISSUE THREAD

**Issue by YaroslavKai** [Voxelum/x-minecraft-launcher#728]
Не получается авторизоваться через Microsoft аккаунт

**Comment by YaroslavKai** [comment]
Выдает такую ошибку, хотя аккаунт у меня есть (но без лицензии Minecraft): Не удалось получить профиль Minecraft: ProfileNotFoundError, undefined

**Comment by BANSAFAn** [comment]
> Выдает такую ошибку, хотя аккаунт у меня есть (но без лицензии Minecraft): Не удалось получить профиль Minecraft: ProfileNotFoundError, undefined


Сэр, если нет лицензии, ТОТ КАК ВЫ ПЫТАЕТЕСЬ ВОЙТИ !? Вам надо войти через оффлайн, или можете включить режим разработчика и подключиться через ely.by

**Comment by herosh1sh** [comment]
> > Выдает такую ошибку, хотя аккаунт у меня есть (но без лицензии Minecraft): Не удалось получить профиль Minecraft: ProfileNotFoundError, undefined
> 
> Сэр, если нет лицензии, ТОТ КАК ВЫ ПЫТАЕТЕСЬ ВОЙТИ !? Вам надо войти через оффлайн, или можете включить режим разработчика и подключиться через ely.by

В прочем получается, он сделал тему в issues и задал вопрос как авторизоваться через Microsoft, когда у него нет лицензии Minecraft. Считаю вопрос решен, потому что у автора темы нет лицензии.
