### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by Plauz0** [Voxelum/x-minecraft-launcher#729]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Java HotSpot(TM) 64-Bit Server VM' (java) 8 with version 21 or later.
More details:
	 - Mod 'Fabric API' (fabric-api) 0.102.1+1.21.1 requires version 21 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 8!
	 - Mod 'Visuality' (visuality) 0.7.7+1.21 requires version 21 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 8!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Выдало вот эту ошибку
[report.zip](https://github.com/user-attachments/files/16645292/report.zip)

**Comment by BANSAFAn** [comment]
> Incompatible mods found!
> net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
> A potential solution has been determined, this may resolve your problem:
> - Replace 'Java HotSpot(TM) 64-Bit Server VM' (java) 8 with version 21 or later.
> More details:
> - Mod 'Fabric API' (fabric-api) 0.102.1+1.21.1 requires version 21 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 8!
> - Mod 'Visuality' (visuality) 0.7.7+1.21 requires version 21 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 8!
> at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
> at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
> at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
> at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
> at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)




Похоже, у вас возникла проблема с несовместимостью модов в Minecraft. Давайте разберем ошибку и найдем решение:

Основная проблема: У вас установлена устаревшая версия Java (версия 8), в то время как моды требуют Java 21 или выше.
Затронутые моды:

Fabric API (версия 0.102.1+1.21.1)
Visuality (версия 0.7.7+1.21)


Решение: Вам нужно обновить Java до версии 21 или новее.

**Comment by BANSAFAn** [comment]
Чтобы исправить эту ошибку, выполните следующие шаги:

Скачайте и установите последнюю версию Java (Java Development Kit или JDK) с официального сайта Oracle или используйте OpenJDK.
После установки убедитесь, что Minecraft использует новую версию Java. Это можно сделать в настройках лаунчера, который вы используете для запуска игры.
Перезапустите лаунчер и попробуйте запустить игру снова.

Если после обновления Java проблема сохраняется, возможно, потребуется переустановить моды или убедиться, что все они совместимы с вашей версией Minecraft и Fabric Loader.
