### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by erajen228** [Voxelum/x-minecraft-launcher#735]
how to remove launcher?

**Comment by ShadowAndNitrix** [comment]
Its Simple Go Into Your Computers Setting And Wipe It Then Buy Windows Again To Get Rid Of It

**Comment by ShadowAndNitrix** [comment]
> When you've downloaded the launcher, you've extracted a `.zip` file to a folder on your disk. So, to remove the launcher you just need to delete this folder. If you want to fully remove it because you will not use it anymore, you'll also need to delete these folders:
> 
> * To delete the launcher settings, type `%appdata%` in the file explorer and delete the folder called `xmcl`
> * To delete your Minecraft instances, type `%homepath%` and delete the folder called  `.xmcl`
> 
> **Keep in mind that deleting the folder containing your Minecraft instances will delete all the worlds, resource packs, shaders and mods contained in that folder.** If you're not familiar with `%appdata%` and `%homepath%`, `%appdata%` just means `C:\Users\[your username]\AppData\Roaming` and `%homepath%` means `C:\Users\[your username]`

Welcome To The Party! Glad To Have A Few New People To Join

**Comment by BANSAFAn** [comment]
I'm in)


> > When you've downloaded the launcher, you've extracted a `.zip` file to a folder on your disk. So, to remove the launcher you just need to delete this folder. If you want to fully remove it because you will not use it anymore, you'll also need to delete these folders:
> > 
> > * To delete the launcher settings, type `%appdata%` in the file explorer and delete the folder called `xmcl`
> > * To delete your Minecraft instances, type `%homepath%` and delete the folder called  `.xmcl`
> > 
> > **Keep in mind that deleting the folder containing your Minecraft instances will delete all the worlds, resource packs, shaders and mods contained in that folder.** If you're not familiar with `%appdata%` and `%homepath%`, `%appdata%` just means `C:\Users\[your username]\AppData\Roaming` and `%homepath%` means `C:\Users\[your username]`
> 
> Welcome To The Party! Glad To Have A Few New People To Join

**Comment by ShadowAndNitrix** [comment]
> I'm in)
> 
> > > When you've downloaded the launcher, you've extracted a `.zip` file to a folder on your disk. So, to remove the launcher you just need to delete this folder. If you want to fully remove it because you will not use it anymore, you'll also need to delete these folders:
> > > 
> > > * To delete the launcher settings, type `%appdata%` in the file explorer and delete the folder called `xmcl`
> > > * To delete your Minecraft instances, type `%homepath%` and delete the folder called  `.xmcl`
> > > 
> > > **Keep in mind that deleting the folder containing your Minecraft instances will delete all the worlds, resource packs, shaders and mods contained in that folder.** If you're not familiar with `%appdata%` and `%homepath%`, `%appdata%` just means `C:\Users\[your username]\AppData\Roaming` and `%homepath%` means `C:\Users\[your username]`
> > 
> > 
> > Welcome To The Party! Glad To Have A Few New People To Join

Alr, Ur In This Party Now :D
