### ISSUE TITLE
查找 Java 路径时不能正确处理链接

### ISSUE THREAD

**Issue by Broken-Deer** [Voxelum/x-minecraft-launcher#737]
### 是否已经有人报告过这个问题？

- [X] 我已经搜索过现有的问题

### 启动器版本

0.45.2

### 操作系统

Linux

### 架构

x64

### 当前行为

![image](https://github.com/user-attachments/assets/86fc0bf6-af4c-4da5-84bb-aee2c8e6ecc0)
![image](https://github.com/user-attachments/assets/b80169c5-0da8-4495-9afa-0b4de3089700)

如图，在linux中，使用包管理器安装的Java常常会创建符号链接，这导致启动器中重复显示相同的Java

### 期望行为

将链接指向的真实路径作为Java路径，如果重复则去除重复

### 复现步骤

下面的步骤适用于 Fedora 40，其他发行版也有类似的操作

1. 运行命令：sudo dnf install java-21-openjdk
2. 打开启动器，打开实例的基础设置
3. 下拉查看 Java 路径

**Comment by v1mkss** [comment]
If I'm not mistaken, this error is only on **Fedora**, I use CachyOS (based on Arch), it's not there.

**Comment by ci010** [comment]
8e1347e12afb1820118606c358d1cd9c77be4e77 尝试修了

**Comment by Broken-Deer** [comment]
在fedora上仍然不起作用

不过上面有提到说这可能是fedora的问题，我现在也没有装别的发行版，而且这个问题不影响使用，所以我先关闭吧
