### ISSUE TITLE
Translate docs.xmcl.app to russian 

### ISSUE THREAD

**Issue by herosh1sh** [Voxelum/x-minecraft-launcher#738]
I would like to see Russian translation on documentation to make it pleasant and clear to read. If it's possible i want to translate docs with our translators

**Comment by BANSAFAn** [comment]
Он где-то там https://github.com/Voxelum/xmcl-page
если не ошибаюсь )

**Comment by herosh1sh** [comment]
> Он где-то там https://github.com/Voxelum/xmcl-page если не ошибаюсь )

Надо поискать хорошенько :)
