### ISSUE TITLE
<title>彈出minecraft錯誤時 無法回到上一頁

### ISSUE THREAD

**Issue by SWXDC** [Voxelum/x-minecraft-launcher#741]
### 是否已经有人报告过这个问题？

- [X] 我已经搜索过现有的问题

### 启动器版本

0.46.0

### 操作系统

Windows

### 架构

x64

### 当前行为

![Screenshot 2024-08-25 022801](https://github.com/user-attachments/assets/c18c1876-3988-4171-b5a0-b8a307738867)
彈出錯誤時 按esc 和 點空白處 不會返回上一頁
這個視窗會放大縮小的動畫(如圖)

**Comment by ci010** [comment]
By design
