### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by mir65344** [Voxelum/x-minecraft-launcher#745]
how can I change the amount of "memory can be used"?
My mods need 6gb memory but the basicaly can be used only 4 gb

**Comment by mir65344** [comment]
![2024-08-25_17-08-49](https://github.com/user-attachments/assets/ca7fc07f-8a11-4974-8c15-1408e8d9fbbf)
how to change to 8gb???

**Comment by LemonFan-maker** [comment]
*Forgive me if I'm not very good at English.*

**Global settings:**
**Click on Settings** and scroll down the interface, after which you will find **Java Memory**, click on **MANUAL** and drag the progress bar below to modify the required memory.
![截图 2024-08-26 10-49-26](https://github.com/user-attachments/assets/83f696a7-5f5b-4f07-901d-fb9b89847e3f)

**Localized settings**
Click on your game version in the left column, then in the upper right corner to find a similar settings icon (Base Settings), click on this icon, slide down the interface, after which you will find **Java Memory**, click on the **MANUAL** to manually modify the memory of this game version!
![截图 2024-08-26 10-54-35](https://github.com/user-attachments/assets/1a4f64d9-e6df-4987-b245-4df2ba44623d)

**Comment by mir65344** [comment]
THANK YOU!

**Comment by mir65344** [comment]
> _Forgive me if I'm not very good at English._
> 
> **Global settings:** **Click on Settings** and scroll down the interface, after which you will find **Java Memory**, click on **MANUAL** and drag the progress bar below to modify the required memory. ![截图 2024-08-26 10-49-26](https://private-user-images.githubusercontent.com/115965270/361288048-83f696a7-5f5b-4f07-901d-fb9b89847e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDc2MjcsIm5iZiI6MTcyNDY0NzMyNywicGF0aCI6Ii8xMTU5NjUyNzAvMzYxMjg4MDQ4LTgzZjY5NmE3LTVmNWItNGYwNy05MDFkLWZiOWI4OTg0N2UzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwNDQyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWNlODZlYmIwNzAyZGIwYmIxZjZmNTk5ZWM2MWE0MzQyZjg3MTRjYTE0ZjI4MTE0ODY1OGM4Mjk1YjA5YWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X07pFJ9-YfaR76UeM5s9rPs6Tpuqz7o_5ZzIEeRJ9JM)
> 
> **Localized settings** Click on your game version in the left column, then in the upper right corner to find a similar settings icon (**Base Settings**), click on this icon, scroll down the interface, after which you will find **Java Memory**, click on the **MANUAL** to manually modify the memory of this game version. **Please don't forget to click save below!** ![截图 2024-08-26 10-54-35](https://private-user-images.githubusercontent.com/115965270/361289171-1a4f64d9-e6df-4987-b245-4df2ba44623d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDc2MjcsIm5iZiI6MTcyNDY0NzMyNywicGF0aCI6Ii8xMTU5NjUyNzAvMzYxMjg5MTcxLTFhNGY2NGQ5LWU2ZGYtNDk4Ny1iMjQ1LTRkZjJiYTQ0NjIzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwNDQyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGFiNjMyZTQzZGNjZTM4OGExMmMyM2M4YmQ3YTc0ZWViODMxMDQ3ODMyOGZkYjdlMDE3YWY3YzNhYTU1ZTc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u1Lcz4fbxo2uxx4cdPg80iaJTE1ngKX_jztOa59n-dU)

Thank you!!!
