### ISSUE TITLE
Невозможно скачать OptiFine

### ISSUE THREAD

**Issue by AIRLord19** [Voxelum/x-minecraft-launcher#748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.46.1

### Operating System

Windows

### Architecture

x64

### Current Behavior

При выборе OptiFine выходит такая ошибка.
![image](https://github.com/user-attachments/assets/78abcb53-c61f-42af-a11c-ef55f296e4f8)

**Comment by herosh1sh** [comment]
скачайте optifine как мод, а не версию https://optifine.net

**Comment by BANSAFAn** [comment]
> ### Существует ли существующая проблема по этому поводу?
> 
>     * [x]  Я искал существующие проблемы
> 
> 
> ### Версия лаунчера
> 
> 0.46.1
> ### Операционная система
> 
> Окна
> ### Архитектура
> 
> х64
> ### Текущее поведение
> 
> При выборе OptiFine выходит такая ошибка. ![image](https://private-user-images.githubusercontent.com/159710609/361377747-78abcb53-c61f-42af-a11c-ef55f296e4f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTAxMjgsIm5iZiI6MTcyNDg0OTgyOCwicGF0aCI6Ii8xNTk3MTA2MDkvMzYxMzc3NzQ3LTc4YWJjYjUzLWM2MWYtNDJhZi1hMTFjLWVmNTVmMjk2ZTRmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQxMjU3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzZmZDRlMmExZDA0YTZhMjRhMjI1MTU3MTUyYWUxNTU1YzZmYWVmOGQxZGVhYzY0Y2VmMGVmZGY2NzM5MGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nHAv1O3h60OQJ00cRv_ngEPY8oLtxmJw0UaiogD7epo)
> ### Ожидаемое поведение
> 
> _Нет ответа _
> ### Шаги по воспроизведению
> 
> _Нет ответа _
> ### Что-нибудь еще?
> 
> _Нет ответа _

Good day ! Now there are problems on the side of BMCL API ! It will take 3-4 weeks to recover, I advise you to download Optifine through their website !
