### ISSUE TITLE
Add new feature to change icon with our pics

### ISSUE THREAD

**Issue by herosh1sh** [Voxelum/x-minecraft-launcher#757]
new button to add icon to instance, in my opinion this feature can be useful and others may not get lost in instance (like in this picture)
![image](https://github.com/user-attachments/assets/1a715b86-8752-4337-a8a9-f0715b611998)

**Comment by ci010** [comment]
We could change icon in instance settings page. Adding icon here might be a redirect to setting page

**Comment by herosh1sh** [comment]
> We could change icon in instance settings page. Adding icon here might be a redirect to setting page

okey, and I have one more question. How to open docs page on local machine? ЯI've translated most of the guide into Russian, but I can't review how it turned out?

**Comment by FilipNones** [comment]
I think is fair to have a shortcut there

**Comment by ci010** [comment]
Fixed in 3b90d1f177f265b20af010cd8ba1af80250ddbdc
