### ISSUE TITLE
Problem with OptiFine

### ISSUE THREAD

**Issue by CasinoRoyal666** [Voxelum/x-minecraft-launcher#769]
Hi! Can you help me with solving this problem? I can't download optifine
![image](https://github.com/user-attachments/assets/792cb473-9ffb-4a09-9a54-c816aac8a5a5)

**Comment by herosh1sh** [comment]
Sup, in settings change "Use BMCL Api" to official servers
![{440F49D6-69EB-4688-A6FC-B8B3C3F79037}](https://github.com/user-attachments/assets/daf00e3e-ed04-437a-a95e-9941ef87612f)

**Comment by CasinoRoyal666** [comment]
Hi, I'm sorry to bother you again, but unfortunately your advice didn't help. The server denies me access, I tried using a VPN and a proxy but it didn't help
![image](https://github.com/user-attachments/assets/b36ed8da-c4fe-41a1-9ad2-976e6f668dc1)

**Comment by CasinoRoyal666** [comment]
Hi, I'm sorry to bother you again, but unfortunately your advice didn't help. The server denies me access, I tried using a VPN and a proxy but it didn't help
![image](https://github.com/user-attachments/assets/50083aa6-1e11-47da-85da-aafbd04f3ce7)

**Comment by BANSAFAn** [comment]
> Hi, I'm sorry to bother you again, but unfortunately your advice didn't help. The server denies me access, I tried using a VPN and a proxy but it didn't help ![image](https://private-user-images.githubusercontent.com/127800297/367752419-50083aa6-1e11-47da-85da-aafbd04f3ce7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDEzNTUsIm5iZiI6MTcyNjUwMTA1NSwicGF0aCI6Ii8xMjc4MDAyOTcvMzY3NzUyNDE5LTUwMDgzYWE2LTFlMTEtNDdkYS04NWRhLWFhZmJkMDRmM2NlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQxNTM3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTdlMjY4YmJiNGQ0NzYwZmNlMzM3ZDk1NGYyYmNjYTgyOTliODRjZDcyYjYyNzYyMTkyZTdjNWJlZDE4MzY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K8hJpV_FDSpABDtSOX-dt1sSSSt8oDQVN543RhFZ4ko)

Это ошибка щас со стороны BMCL API

**Comment by BANSAFAn** [comment]
> I'm also having the same issue as OP even if I'm neither in China nor using the BMCL API.
> 
> ```
>  Error: Failed to load https://bmclapi2.bangbang93.com/optifine/versionList
>     at Jr (http://xmcl.runtime/assets/index.3449731a.js:1:36062)
>     at async fetcher (http://xmcl.runtime/assets/index.3449731a.js:1:41147)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/4675132/371735515-f9f54968-be32-4d47-a63c-b5c6ee927138.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MDQwODMsIm5iZiI6MTcyNzUwMzc4MywicGF0aCI6Ii80Njc1MTMyLzM3MTczNTUxNS1mOWY1NDk2OC1iZTMyLTRkNDctYTYzYy1iNWM2ZWU5MjcxMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMDYwOTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWM5ZTc2ZjJkZWQ3OTFkN2U3MDM1NzI2ZTVjNTUyMTBhNzUwNmNiODU4MzNmNTU5N2U5YmY5ODAxNzBhOTcwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.elcFliRJmsMh8R7IDgBrCjWXcNS2usQDT0Va87qDZuc)
> 
> ![image](https://private-user-images.githubusercontent.com/4675132/371735626-acf39ec2-54c1-4149-8bb8-fbce6243e494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MDQwODMsIm5iZiI6MTcyNzUwMzc4MywicGF0aCI6Ii80Njc1MTMyLzM3MTczNTYyNi1hY2YzOWVjMi01NGMxLTQxNDktOGJiOC1mYmNlNjI0M2U0OTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMDYwOTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTBhNDlmNGFlOGMyNDA1ODlhMWM4ODE2NmVlNzRiZGExNzRiZWFhMzgwZTIwNmU4ZTRhMDhlODkyNmY3YWQ3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.8Z_bqy9puKKUp-h5HBt2R4uYLH-ZGtul9Yc1KPcjjRI)

Are you using VPN?
