### ISSUE TITLE
need some new function

### ISSUE THREAD

**Issue by lijinsheng999** [Voxelum/x-minecraft-launcher#776]
need microphone function for macOS

**Comment by ci010** [comment]
Can you describe it more clear? Why do we need microphone for a Minecraft Launcher?

**Comment by BANSAFAn** [comment]
> Can you describe it more clear? Why do we need microphone for a Minecraft Launcher?

Perhaps he wants a type of overlay in the launcher, like LunarClient (DEV), but I would not advise to do such a thing, it is very heavy on the computer and in addition we have Discord for example for communication.
