### ISSUE TITLE
Automatically refresh token

### ISSUE THREAD

**Issue by Entropy159** [Voxelum/x-minecraft-launcher#777]
The launcher displays when the microsoft token will expire, and allows you to refresh it, but it is annoying having to do that every time it expires. I think the launcher should detect when the token expires and automatically refresh it.

**Comment by herosh1sh** [comment]
I thing it's refreshing automatically refreshing

**Comment by Entropy159** [comment]
Never mind - I think I had turbo launch turned on, it works great now!

**Comment by sunnyyangyangyang** [comment]
@herosh1sh is there anyway to not refreshing the token. I don't want to go to chrome to authenticate everytime i start the launcher. I tested that if i did not refresh the token i can login into servers , keeping the launcher open , even after a re launch a few minutes later . However if i close the launcher and relaunch then it refresh the topen and i am forced to re authenticate again!
