### ISSUE TITLE
Simple Voice Chat 模组支持（MacOS）

### ISSUE THREAD

**Issue by AL-Pinecore** [Voxelum/x-minecraft-launcher#781]
目前添加simple voice chat模组（MacOS系统）进入服务器之后，simple voice chat 说 “你的启动器不支持MacOS麦克风权限“，然后就用不了。
如图：
![micperm](https://github.com/user-attachments/assets/8972c36f-c4c0-41c5-bf09-470c180d9ec3)
这个模组需要MacOS的麦克风权限，所以可能需要启动器获取麦克风权限

或者可以看看这个页面：
https://modrepo.de/minecraft/voicechat/wiki/macos

**Comment by AL-Pinecore** [comment]
这个是Simple Voice Chat模组的Github链接：
https://github.com/henkelmax/simple-voice-chat

**Comment by AL-Pinecore** [comment]
这个也是Issue #776 可能提到的东西

**Comment by ci010** [comment]
7fc48cef3d0469883db428aadf1078a0365c7329 理论上应该修了

**Comment by AL-Pinecore** [comment]
已实测，prebuilds 957 已经解决了该问题
