### ISSUE TITLE
Ram problem.

### ISSUE THREAD

**Issue by gisaandrej** [Voxelum/x-minecraft-launcher#787]
Help I can't use more than 4 GB of RAM, even though I've allocated 8 GB. I can send you screenshots.
![Скриншот 06-10-2024 122807](https://github.com/user-attachments/assets/23a4179d-dba7-4a69-9a6b-b1ec191a1980)
![Скриншот 06-10-2024 123147](https://github.com/user-attachments/assets/84bffa9f-14c7-4bb0-aa3c-4fc013220e2e)
[report.zip](https://github.com/user-attachments/files/17268887/report.zip)

**Comment by ci010** [comment]
In your instance setting, did you set the instance memory?

**Comment by ci010** [comment]
fixed in new version
