### ISSUE TITLE
App Package throws error when trying to install

### ISSUE THREAD

**Issue by Soham52** [Voxelum/x-minecraft-launcher#789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

47.0

### Operating System

Windows

### Architecture

x64

### Current Behavior

Trying to update to Version 47.0 of the launcher using the app installer throws an error. 
![image](https://github.com/user-attachments/assets/818129ef-51e2-429f-a2ab-0314d0b13b7a)

### Expected Behavior

The app installer should install without any error

### Steps To Reproduce

-Download the Appinstaller file or update the launcher from the settings
-See error

**Comment by ci010** [comment]
fixed in 9c9123937cba229e6df9271eabfdefc3d325e000
