### ISSUE TITLE
Custom Font Size [Feature Request]

### ISSUE THREAD

**Issue by Soham52** [Voxelum/x-minecraft-launcher#793]
**Summary:** Allow users to set and adjust custom font sizes within the application, providing greater control over text readability and presentation.

Currently, the application offers the ability to add custom fonts. Adding the ability to input custom font sizes (e.g., via a slider or numerical input) would enhance the user experience by allowing for more personalized adjustments. This feature would benefit users with varying visual needs and improve accessibility by enabling a broader spectrum of font sizes.

**Priority:** Medium

Thank you for considering this feature!

**Comment by ci010** [comment]
I've tried to add this, but the effect does not look good though...

**Comment by Soham52** [comment]
> I've tried to add this, but the effect does not look good though...

Would you mind elaborating what you mean by not good enough?

**Comment by ci010** [comment]
> > I've tried to add this, but the effect does not look good though...
> 
> Would you mind elaborating what you mean by not good enough?

I've check several way to scale all the text size in the app, but it seems changing root element font-size should be the preference.

I'm picking the unit for changing font size. You could try out in your launcher too!

Open the devtool
![image](https://github.com/user-attachments/assets/88f63f13-b861-4c95-ac8b-d1c585dc93fc)
Select the root html element, and change font-size at the sidebar right.
![image](https://github.com/user-attachments/assets/8166f718-ff98-47c5-9d4f-d9380a6d06d1)

Please tell me what unit you think it's better, like increment/decrement by 0.1 px.

**Comment by Soham52** [comment]
> > > I've tried to add this, but the effect does not look good though...
> > 
> > 
> > Would you mind elaborating what you mean by not good enough?
> 
> I've check several way to scale all the text size in the app, but it seems changing root element font-size should be the preference.
> 
> I'm picking the unit for changing font size. You could try out in your launcher too!
> 
> Open the devtool ![image](https://private-user-images.githubusercontent.com/8425057/377717437-88f63f13-b861-4c95-ac8b-d1c585dc93fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDI5MzksIm5iZiI6MTcyOTQ0MjYzOSwicGF0aCI6Ii84NDI1MDU3LzM3NzcxNzQzNy04OGY2M2YxMy1iODYxLTRjOTUtYWM4Yi1kMWM1ODVkYzkzZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTY0MzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTUzZDNlM2I5ZThiNjVlYmIxYjg2NTFjMTcwMzJlY2Y0MzA2YTI1NDRjM2Y1NmM1NDFkNDJlMzIwZTM2MDk2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.yqD7vME1WWBz7Qm4VrtTGjrtnfzvmUNYZuof2kjD_Tg) Select the root html element, and change font-size at the sidebar right. ![image](https://private-user-images.githubusercontent.com/8425057/377717592-8166f718-ff98-47c5-9d4f-d9380a6d06d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDI5MzksIm5iZiI6MTcyOTQ0MjYzOSwicGF0aCI6Ii84NDI1MDU3LzM3NzcxNzU5Mi04MTY2ZjcxOC1mZjk4LTQ3YzUtOWQ0Zi1kOTM4MGE2ZDA2ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTY0MzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZhMzg2NmE0YzlmY2FkZTkzZDEwN2Q2NjRhYTJjZjJiZDEyOWU0MGEzOGE2ZmU5YTg1MDYzNzkzNGY3YjVjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.htO-iNfVIHtZSuiK5kbloAPwxX0Iv3sP8phRB6VoI3g)
> 
> Please tell me what unit you think it's better, like increment/decrement by 0.1 px.

I Think an increment/decrement by 1 px or 0.125 rem would be good enough.

**Comment by Soham52** [comment]
@ci010 Have you thought of anything else?

**Comment by ci010** [comment]
> @ci010 Have you thought of anything else?

https://xmcl.app/zh/prebuilds try latest prebuild. I just add several controls to change the fonts.
