### ISSUE TITLE
更新v0.47.3后，已安装的游戏会提示缺少游戏资源目录

### ISSUE THREAD

**Issue by bileizhen** [Voxelum/x-minecraft-launcher#796]
### 是否已经有人报告过这个问题？

- [X] 我已经搜索过现有的问题

### 启动器版本

v0.47.3

### 操作系统

Windows

### 架构

x64

### 当前行为

更新后，已安装好的整合包会提示缺少游戏资源目录，点击安装无反应

**Comment by bileizhen** [comment]
![Uploading QQ20241011-214420.png…]()

更新之前的版本是v0.47.1，可以正常启动游戏，更新后提示缺少游戏资源目录

**Comment by ci010** [comment]
0.47.4 呢

**Comment by bileizhen** [comment]
> 0.47.4 呢

已修复
