### ISSUE TITLE
Should I convert the Launcher to LOLCAT ?)

### ISSUE THREAD

**Issue by BANSAFAn** [Voxelum/x-minecraft-launcher#809]
I thought about it and decided to ask, how do you like the idea if I translate this Launcher to LOLCAT, but I better ask the developer first, in case against such a language.

**Comment by ci010** [comment]
I've never heard of that language... what's that?

**Comment by BANSAFAn** [comment]
> I've never heard of that language... what's that?

https://en.m.wikipedia.org/wiki/Lolcat

**Comment by BANSAFAn** [comment]
> > I've never heard of that language... what's that?
> 
> https://en.m.wikipedia.org/wiki/Lolcat

By the way minecraft itself is translated to it )

**Comment by ci010** [comment]
LGTM

**Comment by BANSAFAn** [comment]
> LGTM

okey)))
