### ISSUE TITLE
Updating or downgrading mods can create duplicates

### ISSUE THREAD

**Issue by 66BA9Q-ME49** [Voxelum/x-minecraft-launcher#816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.47.7

### Operating System

Windows

### Architecture

x64

### Current Behavior

Sometimes, changing the version of a mod from a same source can create duplicates.

### Expected Behavior

The version should be switched without leaving the previous version in the mod folder.

### Steps To Reproduce

It occurred when downgrading the fabric Replay mod on a forge instance from Modrinth. I also noticed it when updating mods, but I wasn't able to reproduce it.
See the video for the steps.

### Anything else?

In this video, I'm trying to downgrade the Replay Mod to 2.6.17, and it leaves the 2.16.19 file. Then, when I try to delete the 2.16.19 version, it deletes the 2.16.17 version instead.

https://github.com/user-attachments/assets/f2cceae2-9f5d-4b56-85e8-ee7c936d9199

**Comment by ci010** [comment]
Yes this is observed by many people, but it didn't repro in my debug environment. I will keep track this issue
