### ISSUE TITLE
Unverified App Package Installer

### ISSUE THREAD

**Issue by Soham52** [Voxelum/x-minecraft-launcher#819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.47.8.997

### Operating System

Windows

### Architecture

x64

### Current Behavior

Updating Using the app installer throws this error
![image](https://github.com/user-attachments/assets/a6b1e159-1e3c-4ada-b169-37ce5970ef21)

**Comment by BANSAFAn** [comment]
> ### Is there an existing issue for this?
> 
>     * [x]  I have searched the existing issues
> 
> 
> ### Launcher Version
> 
> 0.47.8.997
> ### Operating System
> 
> Windows
> ### Architecture
> 
> x64
> ### Current Behavior
> 
> Updating Using the app installer throws this error ![image](https://private-user-images.githubusercontent.com/73898737/378206923-a6b1e159-1e3c-4ada-b169-37ce5970ef21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDMyMTEsIm5iZiI6MTcyOTQ0MjkxMSwicGF0aCI6Ii83Mzg5ODczNy8zNzgyMDY5MjMtYTZiMWUxNTktMWUzYy00YWRhLWIxNjktMzdjZTU5NzBlZjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE2NDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZDNjNzNkZjBjNzExYjk2ZDkwMWJmNWFjYWI1YjQ2YTk0MzE4YWQ1YjY5YWZlODRkNjAwNWE0OTI0ZGQ2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.In8fhll6HWJvYt0ibySyuFAVHQYCxe0MY3DHqKbB_js)
> ### Expected Behavior
> 
> _No response_
> ### Steps To Reproduce
> 
> _No response_
> ### Anything else?
> 
> _No response_

Use the zip version for now, because the signature won't be functional for another month

**Comment by ShadowAndNitrix** [comment]
Wait What......
