### ISSUE TITLE
Switch to fomantic-ui in docs pages

### ISSUE THREAD

**Issue by lubber-de** [Voxelum/x-minecraft-launcher#82]
Semantic UI hasn't been maintained since 2018, but the active community fork https://fomantic-ui.com already got 500 bugfixes and new features like calendar, slider, toast, etc.

it is backward compatible, the current code should work as it is.

https://fomantic-ui.com
https://github.com/fomantic/fomantic-ui

**Comment by ci010** [comment]
Looks good! I'll update the docs and post some screenshot on it, and at that point I'll transfer the ui to the fomantic!

**Comment by ci010** [comment]
Resolved by [this comment](https://github.com/Voxelum/x-minecraft-launcher/commit/d2df41ab62e926f517f37ad54bd48d0be562f081).
