### ISSUE TITLE
UI bugs in the account menu

### ISSUE THREAD

**Issue by 66BA9Q-ME49** [Voxelum/x-minecraft-launcher#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.47.8

### Operating System

Windows

### Architecture

x64

### Current Behavior

- The name tag floating on top of the player's skin preview in the account menu of the launcher has a weird font
- The icon of the delete button is incorrectly aligned

### Expected Behavior

- The name tag should have the same font as the rest of the UI
- The icon of the delete button should be correctly centered

### Steps To Reproduce

1. Log in to an account (I used an offline account)
2. The name tag has a weird font
3. Hover the delete button
4. The icon is incorrectly aligned

### Anything else?

![image](https://github.com/user-attachments/assets/caab64e1-3ffc-401d-a3de-5d7f6da85ae7)

**Comment by ci010** [comment]
> The buttons are fixed in 0.47.10 but the name tag still has a weird font.

The player name tag is rendered in canvas by webGL. Aligning font will require ton of extra work. So I won't fix it for now.
