### ISSUE TITLE
Modrinth screenshots are blurry while Curseforge screenshots are sharp

### ISSUE THREAD

**Issue by 66BA9Q-ME49** [Voxelum/x-minecraft-launcher#825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.47.10

### Operating System

Windows

### Architecture

x64

### Current Behavior

When I look at the screenshots of a mod, resource pack or shaders from Modrinth, they are blurry like a low-resolution image. When I switch the source to Curseforge, the screenshots are normal high-resolution images.

### Expected Behavior

Images from Modrinth should appear like high-resolution images.

### Steps To Reproduce

1. Search for a modrinth mod, resource pack or shaders
2. Go to the `Gallery` tab
3. Click on a screenshot to enlarge it

### Anything else?

Example with Complementarty Unbound shaders:

https://github.com/user-attachments/assets/efcb7212-ca83-493b-b855-3d65f3239f95

**Comment by ci010** [comment]
it seems modrinth updated the api to split image into 2 urls, one high-res and on low-res
