### ISSUE TITLE
IME Support

### ISSUE THREAD

**Issue by MoYingJi** [Voxelum/x-minecraft-launcher#830]
Some mods show up as Chinese names, but I can't use Fcitx to search for them by typing in Chinese
I tried adding `--enable-wayland-ime` and that didn't work
I don't know if this is supported

xmcl-launcher 0.47.10-1
linux 6.11.5.arch1-1
wayland 1.23.1-1
plasma-desktop 6.2.2-1

**Comment by ci010** [comment]
你是下了prebuild么，搜索其实还是搜英文，只是显示中文，按alt或者页面右上方有按钮来切换是否使用本地语言

**Comment by MoYingJi** [comment]
好的谢谢（
