### ISSUE TITLE
Unable to change instance memory amount

### ISSUE THREAD

**Issue by 66BA9Q-ME49** [Voxelum/x-minecraft-launcher#832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.47.10

### Operating System

Windows

### Architecture

x64

### Current Behavior

Each time I try to change the amount of allocated memory for my instance, it resets back to the original value. The popup asking to save the changes doesn't appear so I think that's why the changes are not saved.

### Expected Behavior

I should be able to save the changes made to the instance configuration.

### Steps To Reproduce

1. Open or create an instance
2. Try to set the allocated memory amount to a new value
3. Close and reopen the instance settings
4. The values resets to the previous value

### Anything else?

https://github.com/user-attachments/assets/2791c3b8-1e62-4016-adf4-9a3819594cce

**Comment by ci010** [comment]
This is werid. I didn't repro this issue in dev env....

The save button not pop-up is by-design. I refactor the logic here. The non-version related setting will not need to save anymore.

**Comment by ci010** [comment]
ah i think that's a ui logic issue. Your global setting is 0-0 manual memory. When the page load, it will use global. You can try to switch your instance memory type as workaround.

**Comment by ci010** [comment]
Fixed in f0ed969be2020d9e0fb139667e5fce19f1bacac2
