### ISSUE TITLE
High amount of junk in resources.sqlite

### ISSUE THREAD

**Issue by 66BA9Q-ME49** [Voxelum/x-minecraft-launcher#833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.47.10

### Operating System

Windows

### Architecture

x64

### Current Behavior

While searching for a workaround for #832, I noticed a high amount of junk in the `resources` table of resources.sqlite (the db where XMCL stores mod info).
It seems that XMCL keeps the entries of every mod jar, even after they are deleted, uninstalled or updated.
It's not a very urgent bug (my db is just 4.56Mb) and it may be intentional (caching?).

### Expected Behavior

I think XMCL should remove the mod entry when the corresponding file is removed.

### Anything else?

Some examples:
L_Ender's Cataclysm is frequently updated, so I found many outdated entries
![image](https://github.com/user-attachments/assets/c8d9b466-5d29-4cb3-a653-dd135bb20082)

As DistantHorizons 2.2.x is incompatible with the current version of Oculus, I reverted to 2.1.2 but the 2.2.x entries are still in the DB
![image](https://github.com/user-attachments/assets/2e82e092-1986-4e49-ab99-03d65530d025)

**Comment by ci010** [comment]
That's kind of by design. XMCL will remember the sha1 with the parsed resource metadata.
