### ISSUE TITLE
<title>Error installing neoforge

### ISSUE THREAD

**Issue by kuzumada** [Voxelum/x-minecraft-launcher#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.47.11

### Operating System

Windows

### Architecture

x64

### Current Behavior

when downloading assemblies on forge/neoforge the launcher asks to download api, but they are not downloaded

### Expected Behavior

Error 404?

**Comment by kuzumada** [comment]
https://github.com/user-attachments/assets/0f9fd7ed-a82b-4ba4-9e27-ac72e9a28fbc

**Comment by kuzumada** [comment]
Кто то может помочь или подсказать в чем проблема
Can someone help or tell me what the problem is?

**Comment by ci010** [comment]
@kuzumada fixed in ae691742fcebab9478e637c1c009ad824619cf62
