### ISSUE TITLE
Java location problem

### ISSUE THREAD

**Issue by GyomeiHimejima9906** [Voxelum/x-minecraft-launcher#840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.47.11

### Operating System

Windows

### Architecture

x64

### Current Behavior

a specify modpack can not be louched dual invalid java path location (but is one modpack that don't start, other modpack start without eny errors)

### Expected Behavior

corretly louch

### Steps To Reproduce

start the modpack
probably it don't start

### Anything else?

https://github.com/user-attachments/assets/da8a519f-5ad5-49bb-a285-7ccc64ed7d97
https://github.com/user-attachments/assets/8595990a-0978-4457-afa2-fd4b8e7d4108 (ignore that minecraft don't louch daul incompatible mod set the problem is the modpack that don't start with current java location)

[report.zip](https://github.com/user-attachments/files/17669909/report.zip)
[-0.0.2.zip](https://github.com/user-attachments/files/17669966/-0.0.2.zip) (exported as modrinth modpack)

**Comment by ci010** [comment]
I see what's the issue. I should restrict the case user input the instance with space at the start or end of the name.

For your workaround, you can try to rename or duplicate (re-create) this instance, and make sure your instance name does not end with empty space.

**Comment by ci010** [comment]
fixed in b98efb99b940b55e34f8086c506472f30e59ede1 and 506a0e2e30dcbb32d0c995215eabd067d6f7d4ad
