### ISSUE TITLE
Provides the option to use System OpenAL in linux systems

### ISSUE THREAD

**Issue by mojujul** [Voxelum/x-minecraft-launcher#841]
As the title suggests, the option to use System OpenAL in Linux systems is provided.

Here's why: When I used the OpenAL library in the game instance, the game would not start, and the game log would output the following message: "Failed to set real-time priority for thread".
The same problem will occur when the System OpenAL is not checked in hmcl. After the check is made, the problem disappears and the game can be started normally.

**Comment by ci010** [comment]
@mojujul I think you can enable the replace native options to replace openAL. It's already implement in the current version. If that doesn't work, I will try to fix it.
