### ISSUE TITLE
The Windows version fails to run as administrator

### ISSUE THREAD

**Issue by owosoup** [Voxelum/x-minecraft-launcher#842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

047.11

### Operating System

Windows

### Architecture

x64, x86

### Current Behavior

The app doesn't start if it's run as administrator.

### Expected Behavior

The app runs (like the Microsoft store version)

### Steps To Reproduce

- Download the x64 or x86 .zip on windows 11
- Try to start it as admin (with a shortcut, by editing the properties of the binary or just with the right-click menu)

### Anything else?

This is important because both the JVM and the launcher which initializes it need to be run as admin if you want to enable large pages, a memory lookup optimisation that speeds up minecraft.

**Comment by ci010** [comment]
It's really strange... Can you send me the report zip? You can generate report from feedback button.

**Comment by owosoup** [comment]
Sorry for the delay. It probably was a problem with my windows installation. It works fine now!
