### ISSUE TITLE
Game launch failed when prepend command has multiple commands

### ISSUE THREAD

**Issue by hmeqo** [Voxelum/x-minecraft-launcher#857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

0.47.15

### Operating System

Linux

### Architecture

x64

### Current Behavior

The startup failed when set two and more prepend command.

![image](https://github.com/user-attachments/assets/a939c335-a199-4dec-8c02-ae6f5e62256e)

### Expected Behavior

I can use `mangohud --dlsym` in prepend command.

### Steps To Reproduce

Set `mangohud --dlsym` or `prime-run mangohud` in prepend command, then launch the game.

**Comment by v1mkss** [comment]
Which Linux are you using?
And the startup should be with the 'mangohud' command, if I'm not mistaken

**Comment by v1mkss** [comment]
![image](https://github.com/user-attachments/assets/ed19d1e7-cac4-4e94-9dd5-6eb12151db4d)
Okay, I realized the bug, I'll try to fix it in the next release

**Comment by hmeqo** [comment]
Okey, thanks
